/**
 * Wire forming company directory for USA and Canada.
 * Each company gets its own SEO page with lead capture.
 */

import type { DirectoryCompany } from "./directory-types";
import { extraDirectoryCompanies } from "./directory-extra";
import { fourslideDirectoryCompanies } from "./directory-fourslide";
import { applyDirectoryIron } from "./directory-iron";
import { moreDirectoryCompanies } from "./directory-more";
import { outreachDirectoryCompanies } from "./directory-outreach";
import { smiDirectoryCompanies } from "./directory-smi";
import { stateBoostCompanies } from "./directory-state-boost";
import { STATE_SHOPS } from "./state-shops";

export type { DirectoryCompany } from "./directory-types";

const REGION_BY_STATE: Record<string, DirectoryCompany["region"]> = {
  CT: "Northeast", ME: "Northeast", MA: "Northeast", NH: "Northeast",
  NJ: "Northeast", NY: "Northeast", PA: "Northeast", RI: "Northeast",
  VT: "Northeast", DE: "Northeast", MD: "Northeast", DC: "Northeast",
  AL: "Southeast", AR: "Southeast", FL: "Southeast", GA: "Southeast",
  KY: "Southeast", LA: "Southeast", MS: "Southeast", NC: "Southeast",
  SC: "Southeast", TN: "Southeast", VA: "Southeast", WV: "Southeast",
  IL: "Midwest", IN: "Midwest", IA: "Midwest", KS: "Midwest",
  MI: "Midwest", MN: "Midwest", MO: "Midwest", NE: "Midwest",
  ND: "Midwest", OH: "Midwest", SD: "Midwest", WI: "Midwest",
  AZ: "Southwest", NM: "Southwest", OK: "Southwest", TX: "Southwest",
  CA: "West", CO: "West", ID: "West", MT: "West", NV: "West",
  OR: "West", UT: "West", WA: "West", WY: "West", HI: "West", AK: "West",
};

const CORE_DIRECTORY_COMPANIES: DirectoryCompany[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // MIDWEST - Ohio, Michigan, Indiana, Illinois, Wisconsin, Minnesota, Missouri
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "ace-wire-spring-form",
    name: "Ace Wire Spring & Form Co., Inc.",
    location: "McKees Rocks, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    website: "https://www.acewirespring.com",
    description: "Family-operated, woman-owned company specializing in custom springs and wire forms since 1939. Produces custom wire forms and coil springs for bulk order customers across various industries.",
    capabilities: ["Custom springs", "Wire forms", "Coil springs", "Bulk production"],
    industries: ["Industrial", "Automotive", "Consumer products"],
    established: "1939",
  },
  {
    slug: "acme-wire-products",
    name: "Acme Wire Products",
    location: "Mystic, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    website: "https://www.acmewire.com",
    description: "American-owned company specializing in wire bending services using modern wire-bending technology. ISO 9001:2015 certified, ensuring quality solutions for various applications.",
    capabilities: ["Wire bending", "CNC wire forming", "Custom wire products"],
    certifications: ["ISO 9001:2015"],
  },
  {
    slug: "active-wireworks",
    name: "Active Wireworks",
    location: "Bartlett, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Custom wire forming and metal stamping with over 35 years of experience. Four-slide, bending, CNC, cutting, and straightening processes for 3/16\" diameter wire and larger.",
    capabilities: ["Four-slide", "Wire bending", "CNC forming", "Wire cutting", "Wire straightening", "Metal stamping"],
    industries: ["Automotive", "Lawn & garden", "Industrial"],
    wireDiameters: "3/16\" and larger",
  },
  {
    slug: "american-precision-spring",
    name: "American Precision Spring Corporation",
    location: "Santa Clara, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Manufactures custom precision springs and wire forms for diverse industries including aerospace, computing, electronic instruments, and medical equipment. Fast turnaround available.",
    capabilities: ["Precision springs", "Torsion springs", "Compression springs", "Extension springs", "Wire forms"],
    industries: ["Aerospace", "Computing", "Electronics", "Medical equipment"],
  },
  {
    slug: "angola-wire",
    name: "Angola Wire",
    location: "Angola, IN",
    state: "IN",
    country: "USA",
    region: "Midwest",
    description: "Custom fabricating steel wire, sheet, and tubing products. Design, engineer, and manufacture custom carbon and stainless steel wire products for OEM and retail clients using modern robotics.",
    capabilities: ["Wire fabrication", "Sheet fabrication", "Tubing", "Robotic manufacturing", "Custom design"],
    industries: ["OEM", "Retail"],
  },
  {
    slug: "apex-wire-products",
    name: "Apex Wire Products Co., Inc.",
    location: "Franklin Park, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    website: "https://www.apexwireproducts.com",
    description: "Precision CNC wire forming, custom welding, and wire straightening and cutting services with over 80 years of experience. Comprehensive wire fabrication including swaging and piercing.",
    capabilities: ["CNC wire forming", "Custom welding", "Wire straightening", "Wire cutting", "Swaging", "Piercing"],
    industries: ["Industrial", "Automotive", "Medical"],
    established: "1940s",
    wireDiameters: "0.015\" to 0.472\"",
  },
  {
    slug: "argo-spring-manufacturing",
    name: "Argo Spring Manufacturing Co., Inc.",
    location: "Norwalk, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Precision wire forms, springs, and metal stampings. Also provides fourslide products, screw machining, and mechanical assembly and packaging services.",
    capabilities: ["Wire forms", "Springs", "Metal stampings", "Fourslide", "Screw machining", "Assembly"],
  },
  {
    slug: "c-j-spring",
    name: "C & J Spring",
    location: "Lake Elsinore, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom spring and wire form manufacturer since 1985. Specializes in compression, extension, torsion, and flat springs, along with precision wire forms using CNC wire bending.",
    capabilities: ["Compression springs", "Extension springs", "Torsion springs", "Flat springs", "CNC wire bending"],
    established: "1985",
  },
  {
    slug: "california-wire-products",
    name: "California Wire Products, Inc.",
    location: "Corona, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Full-service custom wire forming company providing CNC wire bending, wire straightening and cutting, custom wire forms, stampings, and welded assemblies in various metals.",
    capabilities: ["CNC wire bending", "Wire straightening", "Wire cutting", "Stampings", "Welded assemblies"],
    industries: ["Industrial", "Commercial"],
  },
  {
    slug: "century-spring-corp",
    name: "Century Spring Corp",
    location: "Commerce, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Manufactures stock and custom springs for OEM and MRO applications. Custom manufactures wire forms with precision tolerances. Over 40,000 stock spring designs available.",
    capabilities: ["Stock springs", "Custom springs", "Wire forms", "Precision manufacturing"],
    certifications: ["AS9100D", "ISO 9001"],
    industries: ["OEM", "MRO"],
  },
  {
    slug: "cf-wire-products",
    name: "C&F Wire Products",
    location: "Stanton, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Manufactures custom springs, wire forms, and stampings for various industrial applications. Capabilities include compression, extension, and torsion springs, flat forms and prototypes.",
    capabilities: ["Compression springs", "Extension springs", "Torsion springs", "Wire forms", "Stampings", "Prototypes"],
  },
  {
    slug: "cove-west",
    name: "Cove West",
    location: "Fullerton, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom springs, wire forms, and fourslide products with over 40 years of experience. Specializes in precision metal stampings and forming services.",
    capabilities: ["Custom springs", "Wire forms", "Fourslide", "Metal stampings"],
    established: "1980s",
  },
  {
    slug: "custom-spring-manufacturing",
    name: "Custom Spring Manufacturing",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Fabricates custom springs and metal machine components including torsion, compression, equalizer springs, and wireforms. ISO 9001 certified, serving energy, oil & gas sectors.",
    capabilities: ["Torsion springs", "Compression springs", "Equalizer springs", "Wire forms", "Heat treatment"],
    certifications: ["ISO 9001"],
    industries: ["Energy", "Oil & gas"],
  },
  {
    slug: "dd-wire-co",
    name: "DD Wire Co.",
    location: "Temple City, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom and precision CNC wire forming and bending services using advanced 3D wire forming machines. Secondary operations include welding, drilling, and plating.",
    capabilities: ["CNC wire forming", "3D wire forming", "Welding", "Drilling", "Plating"],
  },
  {
    slug: "draco-spring",
    name: "Draco Spring Mfg. Co.",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Designs and manufactures custom springs, wire forms, and stampings using round, flat, or square materials. Hot and cold coiling for various diameters.",
    capabilities: ["Custom springs", "Wire forms", "Stampings", "Hot coiling", "Cold coiling"],
    industries: ["Automotive", "Medical", "Military", "Oil field", "Aerospace"],
  },
  {
    slug: "elyria-spring-stamping",
    name: "Elyria Spring & Stamping",
    location: "Elyria, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Custom wire forms from various round wire diameters. Specializes in simple to complex designs with tight tolerances for diverse applications.",
    capabilities: ["Custom wire forms", "Tight tolerances", "Complex designs"],
  },
  {
    slug: "gambit-corporation",
    name: "Gambit Corporation",
    location: "Rohnert Park, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Manufacturer specializing in fourslide/stamping and custom wire forming services. Produces precision metal components for diverse industrial needs.",
    capabilities: ["Fourslide", "Stamping", "Custom wire forming", "Precision components"],
  },
  {
    slug: "gemco-manufacturing",
    name: "GEMCO Manufacturing Co., Inc.",
    location: "Southington, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "ISO certified supplier of custom metal stampings and wire forms. High-volume orders using fourslide, multi-slide, and power press technologies with over 60 fourslide machines.",
    capabilities: ["Metal stampings", "Wire forms", "Fourslide", "Multi-slide", "Power press"],
    certifications: ["ISO certified"],
  },
  {
    slug: "houston-wire-works",
    name: "Houston Wire Works, Inc.",
    location: "South Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "International manufacturer of standard and custom storage and display solutions. Metal rack and wire products primarily for beverage and water bottling industries.",
    capabilities: ["Storage solutions", "Display solutions", "Metal racks", "Wire products"],
    industries: ["Beverage", "Water bottling", "Retail"],
  },
  {
    slug: "hqa-wire-products",
    name: "HQA Wire Products",
    location: "La Mirada, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "High-quality specialty wire products with over 35 years of experience. Precision wire forming, custom wire forms, welded rings, wire straightening, cutting, and spooling.",
    capabilities: ["Precision wire forming", "Custom wire forms", "Welded rings", "Wire straightening", "Wire cutting", "Spooling"],
    established: "1989",
  },
  {
    slug: "insteel-wire-products",
    name: "Insteel Wire Products",
    location: "Mount Airy, NC",
    state: "NC",
    country: "USA",
    region: "Southeast",
    description: "Major manufacturer of steel wire reinforcing products for concrete construction. Produces welded wire reinforcement, prestressed concrete strand, and wire rod.",
    capabilities: ["Welded wire reinforcement", "Prestressed concrete strand", "Wire rod", "Tire bead wire"],
    industries: ["Construction", "Concrete"],
  },
  {
    slug: "jnl-spring-manufacturing",
    name: "JNL Spring Manufacturing Co",
    location: "Ontario, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Wire formed springs with over 25 years of experience. Manufactures hyper-sensitive components for aircraft and aerospace applications.",
    capabilities: ["Wire formed springs", "Aerospace components", "Precision manufacturing"],
    certifications: ["ISO 9001:2015"],
    industries: ["Aircraft", "Aerospace"],
    established: "1999",
  },
  {
    slug: "katy-spring",
    name: "Katy Spring",
    location: "Katy, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Wire forms and medical wire forming services. Specializes in custom solutions for healthcare, medical, and dental industries with high-quality precision components.",
    capabilities: ["Wire forms", "Medical wire forming", "Precision components"],
    industries: ["Healthcare", "Medical", "Dental"],
  },
  {
    slug: "leeco-spring",
    name: "Leeco Spring International Inc",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Precision and custom spring manufacturing and design since 1959. Wire-formed springs including compression, extension, die, and torsion springs. Over 8,500 stock springs.",
    capabilities: ["Compression springs", "Extension springs", "Die springs", "Torsion springs", "Stock springs"],
    established: "1959",
  },
  {
    slug: "lee-spring",
    name: "Lee Spring",
    location: "Brooklyn, NY",
    state: "NY",
    country: "USA",
    region: "Northeast",
    website: "https://www.leespring.com",
    description: "Manufacturer and supplier of stock and custom springs, wireforms, fourslide parts, and stampings. Thousands of products in stock with custom solutions available.",
    capabilities: ["Stock springs", "Custom springs", "Wire forms", "Fourslide", "Stampings"],
  },
  {
    slug: "lockrey-manufacturing",
    name: "Lockrey Manufacturing",
    location: "Toledo, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Dedicated Wire Forming Division providing comprehensive services from material selection to high-quality finishes. ISO-certified with precision machining and fabrication.",
    capabilities: ["Wire forming", "Precision machining", "Fabrication", "Finishing"],
    certifications: ["ISO certified"],
    industries: ["Industrial", "Defense", "Aerospace", "Agricultural"],
  },
  {
    slug: "master-spring-wire-form",
    name: "Master Spring and Wire Form Co.",
    location: "Roselle, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "High-quality custom coil springs and wire forms. Creates unique and complex wire forms including S-hooks, J-hooks, and utility hooks for industrial and commercial customers.",
    capabilities: ["Coil springs", "Wire forms", "S-hooks", "J-hooks", "Utility hooks"],
  },
  {
    slug: "motion-dynamics",
    name: "Motion Dynamics",
    location: "Fruitport, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "High-quality fabricated wire products and services primarily for the medical device industry. Precision solutions for various applications with custom wire components.",
    capabilities: ["Wire fabrication", "Medical device components", "Precision forming"],
    industries: ["Medical devices"],
  },
  {
    slug: "mw-components",
    name: "MW Components",
    location: "Charlotte, NC",
    state: "NC",
    country: "USA",
    region: "Southeast",
    description: "Metal component manufacturing with custom wire forms, springs, fasteners, bellows, and shims. Over 20 US-based facilities with large inventory including NAS/MS/AN components.",
    capabilities: ["Wire forms", "Springs", "Fasteners", "Bellows", "Shims"],
  },
  {
    slug: "national-wire",
    name: "National Wire L.L.C.",
    location: "Conroe, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Welded wire manufacturer since 1995. Produces standard mesh, structurally engineered welded wire reinforcing, bright basic wire, and pencil rod for construction projects.",
    capabilities: ["Welded wire", "Standard mesh", "Wire reinforcing", "Bright basic wire", "Pencil rod"],
    industries: ["Commercial construction", "Infrastructure", "Residential"],
    established: "1995",
  },
  {
    slug: "newcomb-spring",
    name: "Newcomb Spring Corp.",
    location: "Stonecrest, GA",
    state: "GA",
    country: "USA",
    region: "Southeast",
    website: "https://www.newcombspring.com",
    description: "Experienced American manufacturer of custom springs and wire forms. State-of-the-art CNC wire bending machinery for precise metal forms from samples to large production. Runs plants in Georgia, California, Colorado, Connecticut, North Carolina, Tennessee, Texas and Ontario.",
    capabilities: ["Custom springs", "Wire forms", "CNC wire bending", "High volume production"],
  },
  {
    slug: "ohio-wire-form-spring",
    name: "Ohio Wire Form & Spring",
    location: "Columbus, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    website: "https://ohiowireform.com",
    description: "Custom wire form and spring company since 1947. Design consulting, wire forms, springs, hooks, racks, and rod forming with CNC machine optimization and four-slide forming.",
    capabilities: ["Wire forms", "Springs", "Hooks", "Racks", "Rod forming", "CNC optimization", "Four-slide"],
    established: "1947",
  },
  {
    slug: "oregon-wire",
    name: "Oregon Wire",
    location: "Portland, OR",
    state: "OR",
    country: "USA",
    region: "West",
    website: "https://www.oregonwire.co",
    description: "Custom wire forms and industrial steel wire products. Baling wire, structural and reinforcement wire, and trellis systems for commercial growers and farmers.",
    capabilities: ["Custom wire forms", "Baling wire", "Structural wire", "Reinforcement wire", "Trellis systems"],
    industries: ["Agriculture", "Commercial growing"],
  },
  {
    slug: "orlando-precision",
    name: "Orlando Precision",
    location: "Huntington Beach, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom precision wire forms using advanced CNC wire forming machinery and specialized tooling. Cost-effective solutions for diverse wire parts with limitless configurations.",
    capabilities: ["CNC wire forming", "Precision wire forms", "Custom tooling"],
  },
  {
    slug: "precision-coil-spring",
    name: "Precision Coil Spring Company",
    location: "El Monte, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom precision springs and formed metal parts with over 70 years of experience. Wire forms, flat forms, assemblies, and rings for aerospace, defense, energy, medical, and nuclear.",
    capabilities: ["Precision springs", "Wire forms", "Flat forms", "Assemblies", "Rings"],
    industries: ["Aerospace", "Defense", "Energy", "Medical", "Nuclear"],
    established: "1950s",
  },
  {
    slug: "precision-wire-products-pa",
    name: "Precision Wire Products, Inc.",
    location: "Blairsville, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "Third-generation family-owned manufacturer since 1978. CNC wire forming including baghouse filter cages, custom wire displays, and racks with competitive pricing.",
    capabilities: ["CNC wire forming", "Filter cages", "Wire displays", "Racks"],
    established: "1978",
  },
  {
    slug: "precision-wire-products-ca",
    name: "Precision Wire Products Inc",
    location: "Commerce, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Family-owned wire fabricator since 1946. Design, machining, welding, and complete fabrication including shopping carts, shelving, and back room equipment. Made in America.",
    capabilities: ["Wire fabrication", "Design", "Machining", "Welding", "Shopping carts", "Shelving"],
    established: "1946",
  },
  {
    slug: "pr-fasteners",
    name: "P&R Fasteners, Inc.",
    location: "Somerset, NJ",
    state: "NJ",
    country: "USA",
    region: "Northeast",
    description: "Custom wire forming and precision bending using high-speed fourslide and CNC wire formers. Secondary stamping, welding, and specialty fastening solutions.",
    capabilities: ["Wire forming", "Precision bending", "Fourslide", "CNC forming", "Stamping", "Welding"],
  },
  {
    slug: "progress-wire-products",
    name: "Progress Wire Products Inc.",
    location: "Ashland, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    website: "http://www.progresswire.com",
    description: "Custom wire forms, wire assemblies, and stampings with advanced CNC and multi-slide wire bending machines. Serves automotive, appliance, and medical sectors.",
    capabilities: ["Wire forms", "Wire assemblies", "Stampings", "CNC bending", "Multi-slide"],
    industries: ["Automotive", "Appliance", "Medical"],
  },
  {
    slug: "rives-manufacturing",
    name: "Rives Manufacturing, Inc.",
    location: "Rives Junction, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "CNC and precision wire forming, cold heading, and hot upsetting. Full in-house capabilities for tube forming, thread rolling, and machining across US, Mexico, and Canada.",
    capabilities: ["CNC wire forming", "Precision forming", "Cold heading", "Hot upsetting", "Tube forming", "Thread rolling"],
    industries: ["Automotive", "Lawn & garden", "Furniture", "Agricultural"],
  },
  {
    slug: "rl-spring",
    name: "R & L Spring Company",
    location: "Lake Geneva, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Complex wire forms, springs, and fourslide components using modern CNC wire forming machines. Wide range of sizes from micro-miniature medical springs to large vehicle suspension.",
    capabilities: ["Wire forms", "Springs", "Fourslide", "CNC forming", "Micro-miniature springs"],
    industries: ["Medical", "Automotive"],
  },
  {
    slug: "salco-engineering",
    name: "Salco Engineering & Manufacturing",
    location: "Jackson, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Professional CNC wire forming using Numalliance FTX10 3D wire bending machine. Steel fabrication, wire baskets, carts, dunnage inserts, design, and CNC milling.",
    capabilities: ["CNC wire forming", "3D wire bending", "Steel fabrication", "Wire baskets", "Carts", "CNC milling"],
  },
  {
    slug: "southern-spring-manufacturing",
    name: "Southern Spring Manufacturing Inc",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Custom spring and wire form manufacturing with precision wire coiling. Extension, compression, and torsion springs alongside intricate wire forms with four slide forming.",
    capabilities: ["Precision wire coiling", "Extension springs", "Compression springs", "Torsion springs", "Wire forms", "Four slide"],
  },
  {
    slug: "spiros-industries",
    name: "Spiros Industries",
    location: "West Bend, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "High-volume manufacturer of custom wire coils and precision wire forms. Wire-bending shapes like D-rings and S-hooks with prompt prototyping services.",
    capabilities: ["Wire coils", "Precision wire forms", "D-rings", "S-hooks", "Prototyping"],
    industries: ["Firearms", "Medical"],
  },
  {
    slug: "springfield-spring-stamping",
    name: "Springfield Spring & Stamping",
    location: "East Longmeadow, MA",
    state: "MA",
    country: "USA",
    region: "Northeast",
    description: "Engineering-centric manufacturer of custom wire forms, springs, and stampings. Partners with customers to design and produce critical-to-function components with unrivaled accuracy.",
    capabilities: ["Wire forms", "Springs", "Stampings", "Engineering design", "Prototyping"],
  },
  {
    slug: "spring-industries",
    name: "Spring Industries Inc",
    location: "Ventura, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom manufactures wire forms, springs, stampings, and other metal products. Wire forms from .004\" to .500\" in stainless and carbon steels with EDM cutting services.",
    capabilities: ["Wire forms", "Springs", "Stampings", "EDM cutting"],
    wireDiameters: ".004\" to .500\"",
  },
  {
    slug: "stanley-spring-stamping",
    name: "Stanley Spring & Stamping Corporation",
    location: "Chicago, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Custom spring fabrication, metal stamping, and CNC wire bending. Wire diameters from .008\" to .250\" with advanced techniques. ISO 9001:2015 and IATF 16949:2016 certified.",
    capabilities: ["Spring fabrication", "Metal stamping", "CNC wire bending"],
    certifications: ["ISO 9001:2015", "IATF 16949:2016"],
    wireDiameters: ".008\" to .250\"",
  },
  {
    slug: "suhm-spring-works",
    name: "Suhm Spring Works",
    location: "Dallas, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Custom metal manufacturer with over 130 years of experience. Mechanical springs, wire forms, stampings, machining, metal spinning, water jet and laser cutting, and hot wound springs.",
    capabilities: ["Mechanical springs", "Wire forms", "Stampings", "Machining", "Metal spinning", "Water jet cutting", "Laser cutting"],
    established: "1890s",
  },
  {
    slug: "superior-spring",
    name: "Superior Spring Company",
    location: "Anaheim, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom springs, wire forms, and assemblies for Aerospace, Defense, Medical, and Commercial industries. In-house machining, processing, inspection, and testing.",
    capabilities: ["Custom springs", "Wire forms", "Assemblies", "Machining", "Testing"],
    industries: ["Aerospace", "Defense", "Medical", "Commercial"],
  },
  {
    slug: "three-m-tool",
    name: "Three M Tool",
    location: "York, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "Wire baskets, rod, wire mesh, and perforated metal solutions with 75 years of experience. Custom-engineered designs for parts cleaning, sterilizing, and material handling.",
    capabilities: ["Wire baskets", "Wire mesh", "Perforated metal", "Parts cleaning solutions"],
    industries: ["Medical", "Automotive", "Aerospace", "Manufacturing"],
    established: "1950s",
  },
  {
    slug: "tj-wire-forming",
    name: "TJ Wire Forming",
    location: "Addison, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "ISO-9001:2015 certified manufacturer of custom wire bending and forming of varying thicknesses. Flat forms, light stampings, fixtures, tooling, and dies.",
    capabilities: ["Wire bending", "Wire forming", "Flat forms", "Stampings", "Fixtures", "Tooling"],
    certifications: ["ISO 9001:2015"],
  },
  {
    slug: "tomlinson-manufacturing",
    name: "Tomlinson Manufacturing Company",
    location: "Franklin, IN",
    state: "IN",
    country: "USA",
    region: "Midwest",
    description: "Wire forming services using hydraulic wire bender and Di-Acro bending equipment. Produces American Wire Kaddy line, trucking accessories, and safety products.",
    capabilities: ["Wire forming", "Hydraulic bending", "Di-Acro bending"],
    industries: ["Trucking", "Safety products"],
  },
  {
    slug: "universal-wire-works",
    name: "Universal Wire Works Inc.",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "ISO 9001:2015 certified manufacturer of custom wire forms, fourslide products, and coil springs including compression, extension, and torsion springs.",
    capabilities: ["Wire forms", "Fourslide", "Compression springs", "Extension springs", "Torsion springs"],
    certifications: ["ISO 9001:2015"],
  },
  {
    slug: "vogan-manufacturing",
    name: "Vogan Manufacturing",
    location: "Holland, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "Custom wire forming and bending creating precision wire forms for diverse applications. Tailored solutions to meet client specifications.",
    capabilities: ["Wire forming", "Wire bending", "Precision forms", "Custom design"],
  },
  {
    slug: "vulcan-wire",
    name: "Vulcan Wire",
    location: "Hayward, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Industrial wire products with specialized wire forming services. Custom wire straightening, cutting, and coiling for construction, agriculture, recycling, and manufacturing.",
    capabilities: ["Wire straightening", "Wire cutting", "Wire coiling", "Industrial wire products"],
    industries: ["Construction", "Agriculture", "Recycling", "Manufacturing"],
  },
  {
    slug: "wermke-spring",
    name: "Wermke Spring",
    location: "Fenton, MO",
    state: "MO",
    country: "USA",
    region: "Midwest",
    description: "Custom manufacturer of wire forms, compression springs, torsion springs, extension springs, and spring clips. Tailored solutions for industrial and commercial clients.",
    capabilities: ["Wire forms", "Compression springs", "Torsion springs", "Extension springs", "Spring clips"],
  },
  {
    slug: "western-spring-manufacturing",
    name: "Western Spring Manufacturing",
    location: "Hugo, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description: "Custom spring and wire form manufacturing producing precision coil springs and wire forms for North America. ISO 9001:2015 certified with same-day quotes.",
    capabilities: ["Custom springs", "Wire forms", "Precision coil springs"],
    certifications: ["ISO 9001:2015"],
  },
  {
    slug: "western-steel-wire",
    name: "Western Steel & Wire Inc",
    location: "San Francisco, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Wire distribution and forming services with over 80 years of experience. Straightening, cutting, coiling, spooling, bending, and grinding for medical, agricultural, and construction.",
    capabilities: ["Wire straightening", "Wire cutting", "Wire coiling", "Spooling", "Wire bending", "Grinding"],
    industries: ["Medical", "Agricultural", "Construction"],
    established: "1940s",
  },
  {
    slug: "wire-tech-manufacturing",
    name: "Wire-Tech Manufacturing Corporation",
    location: "San Antonio, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Full-service wire forming company with CNC and multi-slide wire forming. Custom components, clips, hooks, and rings with secondary operations including welding and powder coating.",
    capabilities: ["CNC wire forming", "Multi-slide", "Welding", "Plating", "Powder coating"],
  },
  {
    slug: "wisconsin-stamping-manufacturing",
    name: "Wisconsin Stamping & Manufacturing",
    location: "Germantown, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Diversified manufacturer with wire forming including 2D and 3D forms, guards, and thread rolling. Over six decades of experience with ISO 9001:2015 certification.",
    capabilities: ["2D wire forming", "3D wire forming", "Guards", "Thread rolling", "Stamping", "Machining"],
    certifications: ["ISO 9001:2015"],
    established: "1960s",
  },
  {
    slug: "wytech",
    name: "Wytech",
    location: "Rahway, NJ",
    state: "NJ",
    country: "USA",
    region: "Northeast",
    description: "Expert wire forming services with advanced technology for precision wire components in various shapes and sizes. Primarily serves medical applications sector.",
    capabilities: ["Wire forming", "Precision components", "Medical wire"],
    industries: ["Medical"],
  },
  {
    slug: "rpk-group",
    name: "RPK Group",
    location: "Rochester Hills, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "International manufacturer of complex wire forms, springs, stampings, plastic injection molding, and assemblies. Dedicated plant serving various industrial sectors.",
    capabilities: ["Wire forms", "Springs", "Stampings", "Plastic injection molding", "Assemblies"],
  },
  {
    slug: "precision-wire-forms-mi",
    name: "Precision Wire Forms, Inc.",
    location: "Three Rivers, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Wire forms, tube forms, and assemblies since 1997. In-house tooling minimizes costs and accelerates product launches with streamlined secondary operations.",
    capabilities: ["Wire forms", "Tube forms", "Assemblies", "In-house tooling"],
    established: "1997",
  },
  {
    slug: "wirefab",
    name: "Wirefab, Inc.",
    location: "Worcester, MA",
    state: "MA",
    country: "USA",
    region: "Northeast",
    website: "https://www.wirefab.com",
    description: "U.S. contract manufacturer of custom wire and metal fabrication with over 70 years of experience. 2D and 3D wire bending in 84,000 square foot facility with MIG, TIG, and resistance welding.",
    capabilities: ["2D wire bending", "3D wire bending", "Resistance welding", "MIG welding", "TIG welding"],
    established: "1950s",
  },
  {
    slug: "betts-spring-manufacturing",
    name: "Betts Spring Manufacturing",
    location: "Fresno, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Family-owned since 1868. Custom cold and hot wound coil springs, leaf springs, and wire forms including torsion, compression, and extension springs for trucking, agriculture, and automotive.",
    capabilities: ["Coil springs", "Leaf springs", "Wire forms", "Hot winding", "Cold winding"],
    industries: ["Trucking", "Agriculture", "Automotive"],
    established: "1868",
  },
  {
    slug: "coiling-technologies",
    name: "Coiling Technologies Inc",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Custom springs and wire forms for compression, extension, torsion, and flat wire springs. State-of-the-art technology with stainless steel, music wire, and exotic alloys.",
    capabilities: ["Compression springs", "Extension springs", "Torsion springs", "Flat wire springs", "Wire forms"],
  },
  {
    slug: "diamond-wire-spring",
    name: "Diamond Wire Spring Company",
    location: "Pittsburgh, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "ISO-certified custom design and manufacture of wire forms and springs. Engineering, prototyping, and manufacturing with advanced CNC wire forming technology.",
    capabilities: ["Wire forms", "Springs", "Engineering", "Prototyping", "CNC wire forming"],
    certifications: ["ISO certified"],
  },
  {
    slug: "illini-wire-works",
    name: "Illini Wire Works",
    location: "Olney, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Direct wire forming services processing stainless steel, bright basic, galvanized, aluminum, copper, and titanium. Custom wire solutions for industrial and commercial applications.",
    capabilities: ["Wire forming", "Multiple materials", "Custom solutions"],
  },
  {
    slug: "madsen-steel-wire",
    name: "Madsen Steel Wire Products",
    location: "Bronson, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Full-service wire company with custom wire fabrication, mesh welding, and wire forming. Comprehensive line of custom wire products for OEM and industrial applications.",
    capabilities: ["Wire fabrication", "Mesh welding", "Wire forming", "Custom products"],
    industries: ["Automotive", "Medical", "Consumer products"],
  },
  {
    slug: "marlin-steel",
    name: "Marlin Steel Wire Products LLC",
    location: "Baltimore, MD",
    state: "MD",
    country: "USA",
    region: "Northeast",
    website: "https://www.marlinwire.com",
    description: "Custom wire form manufacturer specializing in design and engineering of stainless steel baskets and material handling solutions. Quick-turn prototyping available.",
    capabilities: ["Wire forms", "Stainless steel baskets", "Material handling", "Custom design", "Prototyping"],
  },
  {
    slug: "novo-precision",
    name: "Novo Precision",
    location: "Bristol, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Precision wire forms including medical staples and wire forms for medical, automotive, and appliance fields. Produces specialized titanium clips for industrial clients.",
    capabilities: ["Precision wire forms", "Medical staples", "Titanium clips"],
    industries: ["Medical", "Automotive", "Appliance"],
  },
  {
    slug: "obrien-wire-products",
    name: "O'Brien Wire Products-TX Inc",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Custom wire fabrication, wire forms, and metal stampings. CNC wire bending, laser cutting, and robotic welding for industrial, OEM, medical, and consumer product industries.",
    capabilities: ["Wire fabrication", "Wire forms", "Metal stampings", "CNC bending", "Laser cutting", "Robotic welding"],
    industries: ["Industrial", "OEM", "Medical", "Consumer products"],
  },
  {
    slug: "peninsula-spring",
    name: "Peninsula Spring Corporation",
    location: "Gilroy, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Precision wire forms and custom springs including compression, extension, and torsion springs. Wide range of materials for diverse industrial applications.",
    capabilities: ["Wire forms", "Compression springs", "Extension springs", "Torsion springs"],
  },
  {
    slug: "rev-co-spring",
    name: "Rev-Co Spring Mfr Corporation",
    location: "Santa Fe Springs, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Custom springs, wire forms, stampings, and assemblies with over 50 years of experience. Serves aerospace, automotive, medical, and electronics industries.",
    capabilities: ["Custom springs", "Wire forms", "Stampings", "Assemblies"],
    industries: ["Aerospace", "Automotive", "Medical", "Electronics"],
    established: "1970s",
  },
  {
    slug: "rockford-specialties",
    name: "Rockford Specialties Inc.",
    location: "Rockford, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Custom wire forming manufacturer with over 40 years of experience. Custom-made wire and laser-cut components with welding, finishing, and product assembly.",
    capabilities: ["Wire forming", "Laser cutting", "Welding", "Finishing", "Assembly"],
    industries: ["OEM", "Point-of-Purchase", "Food Service", "Medical Supply"],
    established: "1980s",
  },
  {
    slug: "seisa-medical",
    name: "Seisa Medical",
    location: "El Paso, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Global contract manufacturer of Class II and Class III medical devices. Wire forming services with advanced technology for durable, efficient, and customized parts.",
    capabilities: ["Medical device manufacturing", "Wire forming", "Design to assembly"],
    industries: ["Medical devices"],
    certifications: ["FDA registered"],
  },
  {
    slug: "spring-products-international",
    name: "Spring Products International",
    location: "Navasota, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Custom spring products using specialty alloy metals with ISO compliant quality management. Design assistance and quality control throughout production.",
    capabilities: ["Custom springs", "Specialty alloys", "Design assistance"],
    certifications: ["ISO compliant"],
  },
  {
    slug: "tusco-manufacturing",
    name: "Tusco Manufacturing",
    location: "Gnadenhutten, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    website: "https://www.tuscomfg.com",
    description: "Comprehensive in-house metal fabrication including straightening, cutting, forming, and resistance welding of wire and wire frames. Fiber laser cutting available.",
    capabilities: ["Wire straightening", "Wire cutting", "Wire forming", "Resistance welding", "Laser cutting"],
  },
  {
    slug: "wald-wire-manufacturing",
    name: "Wald Wire and Manufacturing Co.",
    location: "Oshkosh, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Custom wire forming and fabrication with 70 years of experience. Fast turnarounds, short runs, no quantity minimums, plus sheet metal fabrication.",
    capabilities: ["Wire forming", "Wire fabrication", "Sheet metal fabrication"],
    established: "1950s",
  },
  {
    slug: "midwest-wire-products",
    name: "Midwest Wire Products, LLC",
    location: "Sturgeon Bay, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Full-service metal forming company specializing in custom wireforms and stampings. Engineers assist with design and development for effective manufacturing solutions.",
    capabilities: ["Wire forms", "Stampings", "Design assistance", "Engineering"],
  },
  {
    slug: "west-michigan-tube-wire",
    name: "West Michigan Tube & Wire Forming",
    location: "Muskegon, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "2D and 3D CNC wire forming and bending for wire widths from .062\" to .312\". Tube bending, assembly, welding, and straight & cut services for industrial applications.",
    capabilities: ["2D CNC wire forming", "3D CNC wire forming", "Tube bending", "Assembly", "Welding"],
    wireDiameters: ".062\" to .312\"",
  },
  {
    slug: "rowley-spring-stamping",
    name: "Rowley Spring and Stamping",
    location: "Bristol, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Wire form manufacturer using CNC and Fourslide methods for diverse configurations. Custom tool design, springs, and metal stampings for PCB assembly and more.",
    capabilities: ["Wire forms", "CNC forming", "Fourslide", "Custom tooling", "Springs", "Stampings"],
    industries: ["Electronics", "PCB assembly"],
  },
  {
    slug: "yost-superior",
    name: "The Yost Superior Co.",
    location: "Springfield, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    website: "https://www.yostsuperior.com",
    description: "Leading manufacturer of compression, extension, torsion, wire, stampings and custom wireforms for over 100 years. Family owned operation with ISO 9001:2015 certification.",
    capabilities: ["Compression springs", "Extension springs", "Torsion springs", "Wire forms", "Stampings"],
    certifications: ["ISO 9001:2015"],
    established: "1920s",
  },
  {
    slug: "wire-products-company",
    name: "Wire Products Company",
    location: "Cleveland, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    website: "https://wire-products.com",
    description: "Family-owned since 1951. Over 20 four-slides and bending department for wire forms .005\" to .500\". AS 9100 D / ISO 9001:2015 registered with ITAR compliance.",
    capabilities: ["Four-slide", "Wire forms", "Springs", "Stampings", "Welded assemblies"],
    certifications: ["AS 9100 D", "ISO 9001:2015", "ITAR"],
    wireDiameters: ".005\" to .500\"",
    established: "1951",
  },
  {
    slug: "crawford-manufacturing",
    name: "Crawford Wire Form Manufacturing",
    location: "Baltic, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "High volume stampings and custom wire forms. In-house tooling with wire EDM. Carbon steel, brass, copper, stainless steel products for electronics, appliance, and automotive.",
    capabilities: ["Wire forms", "Stampings", "In-house tooling", "Wire EDM"],
    industries: ["Electronics", "Appliance", "Automotive", "Agricultural", "OEM"],
  },
  {
    slug: "keats-manufacturing",
    name: "Keats Manufacturing Co.",
    location: "Wheeling, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    website: "https://www.keatsmfg.com",
    description: "Wire forming services including drawing, bending, stretching, flattening, straightening, and cutting. Multi-slide, four-slide, and CNC equipment with in-house tooling.",
    capabilities: ["Wire forming", "Wire bending", "Multi-slide", "Four-slide", "CNC forming", "In-house tooling"],
    certifications: ["ISO 9001", "ISO 14001", "TS 16949"],
  },
  {
    slug: "multitech-industries",
    name: "Multitech Industries",
    location: "Carol Stream, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    website: "https://www.multitechind.com",
    description: "Custom wire forms and wire form assemblies using state-of-the-art CNC processes. Trusted partner for industrial and automotive OEMs and Tier 1 suppliers.",
    capabilities: ["CNC wire forming", "Wire form assemblies", "Design engineering", "Testing"],
    industries: ["Industrial", "Automotive", "OEM"],
  },
  {
    slug: "james-spring-wire",
    name: "James Spring & Wire Company",
    location: "Malvern, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    website: "https://www.jamesspring.com",
    description: "Custom springs, wire forms, and light stampings. Precision manufacturing for demanding applications with comprehensive engineering support.",
    capabilities: ["Custom springs", "Wire forms", "Stampings", "Engineering support"],
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // CANADA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "omnicoil-spring-works",
    name: "OmniCoil Spring Works Inc.",
    location: "Ontario",
    state: "ON",
    country: "Canada",
    region: "Canada",
    website: "https://www.omnicoil.com",
    description: "Canada's leading provider of custom wire forms and flat forms. In-house design and manufacturing with shot peening, painting, stress relieving, and special packaging.",
    capabilities: ["Wire forms", "Flat forms", "Shot peening", "Painting", "Stress relieving"],
  },
  {
    slug: "centennial-wire",
    name: "Centennial Wire Products Ltd.",
    location: "Winnipeg, MB",
    state: "MB",
    country: "Canada",
    region: "Canada",
    website: "https://www.centennialwire.com",
    description: "Leader in wire formed products with bending up to 0.500 inches diameter on multiple axes. CNC technology for complex 2D and 3D parts, rings, spirals, and frames.",
    capabilities: ["CNC wire bending", "2D forming", "3D forming", "Rings", "Spirals", "Frames"],
    wireDiameters: "Up to 0.500\"",
  },
  {
    slug: "gateway-wire-products",
    name: "Gateway Wire Products Ltd.",
    location: "Ontario",
    state: "ON",
    country: "Canada",
    region: "Canada",
    website: "https://www.gatewaywire.ca",
    description: "Complete range of OEM and custom wire forms and bending. State-of-the-art 3D CNC custom bender with capacity of .125 to .312 diameters plus in-house tool room.",
    capabilities: ["OEM wire forms", "Custom wire forms", "3D CNC bending", "Pop displays", "Store fixtures"],
    wireDiameters: ".125 to .312",
  },
  {
    slug: "s3-wireform",
    name: "S3 Wireform",
    location: "Western Canada",
    state: "AB",
    country: "Canada",
    region: "Canada",
    website: "https://s3wireform.com",
    description: "One of the largest industrial spring and wire form facilities in North America. Extension springs, compression springs, torsion springs, and wire forming with powder coating.",
    capabilities: ["Extension springs", "Compression springs", "Torsion springs", "Wire forming", "Powder coating", "Robotic welding"],
  },
  {
    slug: "springs-and-things",
    name: "Springs & Things Inc.",
    location: "Toronto, ON",
    state: "ON",
    country: "Canada",
    region: "Canada",
    website: "https://springsandthings.com",
    description: "Rush delivery of wire forms in days, not weeks. Custom wire forms from basic tempers to full spring material with traditional and modern CNC equipment.",
    capabilities: ["Wire forms", "Rush delivery", "CNC wire forming", "Custom springs"],
  },
  {
    slug: "bohne-spring-industries",
    name: "Bohne Spring Industries Limited",
    location: "Toronto, ON",
    state: "ON",
    country: "Canada",
    region: "Canada",
    description: "Custom springs and wire forms manufacturer serving Canadian and international markets. Comprehensive spring manufacturing capabilities.",
    capabilities: ["Custom springs", "Wire forms", "Industrial components"],
  },
  {
    slug: "canadian-threadall",
    name: "Canadian Threadall Limited",
    location: "Cambridge, ON",
    state: "ON",
    country: "Canada",
    region: "Canada",
    description: "Wire forming and threading services. Custom threaded products and wire forms for industrial applications across Canada.",
    capabilities: ["Wire forming", "Threading", "Custom fasteners"],
  },
  {
    slug: "zb-wire-works",
    name: "ZB Wire Works, Inc.",
    location: "Ontario, CA",
    state: "CA",
    country: "USA",
    region: "West",
    website: "https://www.zbsweldedmesh.com",
    description: "Custom pattern welded wire mesh and metal mesh up to 9'-6\" wide panels, plus mesh framing, wire baskets, shelves and racks. Ontario, California — mesh fabrication, not CNC wire from coil.",
    capabilities: ["Welded wire mesh", "Metal mesh", "Mesh framing", "Wire baskets"],
  },
];

/** Official sites for directory listings that were missing a `website` field. */
const DIRECTORY_SITES: Record<string, string> = {
  "active-wireworks": "https://www.activewireworks.com",
  "american-precision-spring": "https://americanprecspring.com",
  "angola-wire": "https://www.angolawire.com",
  "argo-spring-manufacturing": "https://argospringmfg.com",
  "c-j-spring": "https://www.candjspring.com",
  "california-wire-products": "https://cawire.com",
  "century-spring-corp": "https://www.centuryspring.com",
  "cf-wire-products": "https://www.cfwireproducts.com",
  "dd-wire-co": "https://www.ddwire.com",
  "draco-spring": "https://www.dracospring.com",
  "elyria-spring-stamping": "https://www.elyriaspring.com",
  "gemco-manufacturing": "https://gemcomfg.com",
  "houston-wire-works": "https://houstonwirework.com/home",
  "insteel-wire-products": "https://insteel.com",
  "katy-spring": "https://katyspring.com",
  "leeco-spring": "https://leecospring.com",
  "lockrey-manufacturing": "https://www.lockreymanufacturing.com",
  "master-spring-wire-form": "https://www.masterspring.com",
  "motion-dynamics": "https://motiondc.com",
  "mw-components": "https://www.mwcomponents.com",
  "national-wire": "https://nationalwirellc.com",
  "oregon-wire": "https://www.oregonwire.co",
  "precision-coil-spring": "https://pcspring.com",
  "precision-wire-products-pa": "https://www.precisionwire.net",
  "pr-fasteners": "https://prfast.com",
  "progress-wire-products": "https://progresswire.com",
  "rives-manufacturing": "https://rivesmfg.com",
  "rl-spring": "https://rlspring.com",
  "salco-engineering": "https://salcoeng.com",
  "spiros-industries": "https://spirosind.com",
  "springfield-spring-stamping": "https://www.springfieldspring.com",
  "stanley-spring-stamping": "https://stanleyspring.com",
  "suhm-spring-works": "https://suhm.net",
  "superior-spring": "https://superiorspring.com",
  "tj-wire-forming": "https://tjwireforming.com",
  "tomlinson-manufacturing": "https://tomlinsonmfg.com",
  "wermke-spring": "https://wermkespring.com",
  "western-spring-manufacturing": "https://www.westernspring.com",
  "wisconsin-stamping-manufacturing": "https://www.wisconsinstamping.com",
  "wytech": "https://www.wytech.com",
  "betts-spring-manufacturing": "https://bettsspring.com",
  "coiling-technologies": "https://www.coilingtech.com",
  "diamond-wire-spring": "https://diamondwire.com",
  "illini-wire-works": "https://illiniwire.com",
  "novo-precision": "https://novoprecision.com",
  "peninsula-spring": "https://peninsulaspring.com",
  "rockford-specialties": "https://rswire.com",
  "wald-wire-manufacturing": "https://waldwire.com",
  "midwest-wire-products": "https://wireforming.com",
  "west-michigan-tube-wire": "https://wmtubewire.com",
  "rowley-spring-stamping": "https://rowleyspring.com",
  "seisa-medical": "https://www.seisamedical.com",
  "vulcan-wire": "https://www.vulcanwire.com",
  "cove-west": "https://covewestusa.com",
  "hqa-wire-products": "https://hqawp.com",
  "orlando-precision": "https://orlandoprecision.com",
  "precision-wire-products-ca": "https://precisionwireproducts.com",
  "vogan-manufacturing": "https://www.voganmfg.com",
  "rpk-group": "https://rpk-global.com",
  "three-m-tool": "https://www.threemtool.com",
  "madsen-steel-wire": "https://madsenwire.com",
  "jnl-spring-manufacturing": "https://jnlspring.com",
  "obrien-wire-products": "https://www.obrienwire.com",
  "crawford-manufacturing": "https://crawfordmfg.com",
  "tusco-manufacturing": "https://www.tuscomfg.com",
  "bohne-spring-industries": "https://www.bohnespring.ca",
  "canadian-threadall": "https://threadall.com",
  "wire-tech-manufacturing": "https://wiretechmfg.com",
  "rev-co-spring": "https://www.revcospring.com",
  "gambit-corporation": "https://www.gambitcorp.com",
  "spring-industries": "https://www.springind.com",
  "spring-products-international": "https://www.spring-products.com",
  "southern-spring-manufacturing": "https://southernspring.net",
};

for (const company of CORE_DIRECTORY_COMPANIES) {
  if (!company.website) {
    const site = DIRECTORY_SITES[company.slug];
    if (site) company.website = site;
  }
}

function normName(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function hostOf(url?: string) {
  if (!url) return "";
  try {
    return new URL(url).hostname.replace(/^www\./, "").toLowerCase();
  } catch {
    return "";
  }
}

/** Host, or host+path for plant pages so Corry and Farmington are not the same listing. */
function listingKey(url?: string) {
  if (!url) return "";
  try {
    const u = new URL(url);
    const host = u.hostname.replace(/^www\./, "").toLowerCase();
    const path = u.pathname.replace(/\/$/, "").toLowerCase();
    const hash = u.hash.replace(/^#/, "").toLowerCase();
    if (path || hash) return `${host}${path}${hash ? `#${hash}` : ""}`;
    return host;
  } catch {
    return "";
  }
}

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function fromStateShops(): DirectoryCompany[] {
  const skip =
    /mill|drawer|service center|not a coil|not 4–14|fence|buy formed wire|they draw/i;
  const out: DirectoryCompany[] = [];
  const seenHost = new Set<string>();
  for (const shop of STATE_SHOPS) {
    if (skip.test(shop.capacity)) continue;
    if (/^serves /i.test(shop.city)) continue;
    const host = hostOf(shop.website);
    if (host && seenHost.has(host)) continue;
    if (host) seenHost.add(host);
    const region = REGION_BY_STATE[shop.state];
    if (!region) continue;
    out.push({
      slug: slugify(shop.name),
      name: shop.name,
      location: `${shop.city}, ${shop.state}`,
      state: shop.state,
      country: "USA",
      region,
      website: shop.website,
      description: `${shop.name} in ${shop.city}, ${shop.state}. ${shop.capacity}`,
      capabilities: shop.capacity.split(/,|;/).slice(0, 4).map((s) => s.trim()).filter(Boolean),
    });
  }
  return out;
}

function mergeDirectory(groups: DirectoryCompany[][]) {
  const seenSlug = new Set<string>();
  const seenName = new Set<string>();
  const seenHost = new Set<string>();
  const merged: DirectoryCompany[] = [];
  for (const group of groups) {
    for (const company of group) {
      const nameKey = normName(company.name);
      const host = listingKey(company.website);
      if (seenSlug.has(company.slug) || seenName.has(nameKey)) continue;
      if (host && seenHost.has(host)) continue;
      seenSlug.add(company.slug);
      seenName.add(nameKey);
      if (host) seenHost.add(host);
      merged.push(company);
    }
  }
  return merged;
}

export const directoryCompanies = mergeDirectory([
  CORE_DIRECTORY_COMPANIES,
  extraDirectoryCompanies,
  stateBoostCompanies,
  smiDirectoryCompanies,
  fourslideDirectoryCompanies,
  moreDirectoryCompanies,
  outreachDirectoryCompanies,
  fromStateShops(),
]).map(applyDirectoryIron);

const CANADA_PROVINCES = new Set([
  "ON", "QC", "BC", "AB", "MB", "SK", "NS", "NB", "NL", "PE", "NT", "YT", "NU",
]);

export function directoryRegionForState(
  state: string,
): DirectoryCompany["region"] {
  const key = state.trim().toUpperCase();
  if (CANADA_PROVINCES.has(key)) return "Canada";
  return REGION_BY_STATE[key] ?? "Midwest";
}

export function publicHost(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return url;
  }
}

export function getDirectoryCompany(slug: string): DirectoryCompany | undefined {
  return directoryCompanies.find((c) => c.slug === slug);
}

export function getCompaniesByRegion(region: DirectoryCompany["region"]): DirectoryCompany[] {
  return directoryCompanies.filter((c) => c.region === region);
}

export function getCompaniesByState(state: string): DirectoryCompany[] {
  return directoryCompanies.filter((c) => c.state === state);
}

export function getCompaniesByCountry(country: "USA" | "Canada"): DirectoryCompany[] {
  return directoryCompanies.filter((c) => c.country === country);
}

export const DIRECTORY_REGIONS = ["Northeast", "Southeast", "Midwest", "Southwest", "West", "Canada"] as const;

export const DIRECTORY_STATES = [...new Set(directoryCompanies.map((c) => c.state))].sort();
