import type { DirectoryCompany } from "./directory-types";

/**
 * Extra plants and job shops for coverage states.
 * Unique slug + name. Plant pages use a location path so they do not
 * collapse into the parent brand already in the directory.
 * Do not add invented "City Spring" names — only shops we can point at.
 */
const REGION: Record<string, DirectoryCompany["region"]> = {
  PA: "Northeast",
  NJ: "Northeast",
  NY: "Northeast",
  MD: "Northeast",
  WI: "Midwest",
  IN: "Midwest",
  IL: "Midwest",
  KY: "Southeast",
  NC: "Southeast",
  SC: "Southeast",
  FL: "Southeast",
  VA: "Southeast",
  TN: "Southeast",
};

function shop(
  slug: string,
  name: string,
  city: string,
  state: string,
  description: string,
  capabilities: string[],
  website?: string,
): DirectoryCompany {
  return {
    slug,
    name,
    location: `${city}, ${state}`,
    state,
    country: "USA",
    region: REGION[state] ?? "Midwest",
    description,
    capabilities,
    ...(website ? { website } : {}),
  };
}

export const stateBoostCompanies: DirectoryCompany[] = [
  // ── Pennsylvania ──────────────────────────────────────────────────────────
  shop(
    "vulcan-spring",
    "Vulcan Spring & Mfg. Co.",
    "Telford",
    "PA",
    "Constant-force, power, and spiral torsion springs plus round- and flat-wire forms. Telford, PA plant since 1967. ISO 13485.",
    ["Constant-force springs", "Wire forms", "Power springs"],
    "https://www.vulcanspring.com",
  ),
  shop(
    "iowa-spring-northeast",
    "Iowa Spring Northeast",
    "Reading",
    "PA",
    "Former Northeast Spring plant at 506 South 5th Street, Reading, PA. Iowa Spring acquired it in 2023. Custom springs and wire forms about 0.080–0.625 in, overhead-door work, dedicated truck fleet.",
    ["Springs", "Wire forms", "Overhead door springs"],
    "https://iowaspring.com/northeast-facility/",
  ),
  shop(
    "hendrick-manufacturing",
    "Hendrick Manufacturing",
    "Carbondale",
    "PA",
    "Perforated metal and fabrication at 1 Seventh Avenue, Carbondale, PA. Sister to Hendrick Screen in Owensboro, KY. Not a CNC round-wire job shop.",
    ["Perforated metal", "Metal fabrication"],
    "https://www.hendrickcorp.com",
  ),
  shop(
    "st-marys-spring",
    "St. Marys Spring Company",
    "St. Marys",
    "PA",
    "Springs, flat forms, wire forms, and stampings since 1946. CNC coilers, CNC wire formers, heat treat, grinders. St. Marys, PA.",
    ["Springs", "Wire forms", "Stampings", "Flat springs"],
    "https://www.stmarysspring.com",
  ),
  shop(
    "penn-elkco-spring",
    "Penn-Elkco Spring Company",
    "St. Marys",
    "PA",
    "Compression, extension, torsion, wire forms, fourslide, and stampings since 1956. St. Marys, PA. ISO 9001.",
    ["Springs", "Wire forms", "Fourslide", "Stampings"],
    "https://www.pespring.com",
  ),
  shop(
    "hunter-spring-hatfield",
    "AMETEK Hunter Spring",
    "Hatfield",
    "PA",
    "Hunter Spring in Hatfield, PA. Constant-force springs, spring motors, and reels. AMETEK brand — not a generic CNC job shop.",
    ["Constant-force springs", "Spring motors", "Reels"],
    "https://www.ametek.com/brands/hunter-spring",
  ),
  shop(
    "associated-spring-corry",
    "Associated Spring (Corry)",
    "Corry",
    "PA",
    "Barnes / Associated Spring plant in Corry, PA. CNC wire forming, slide forming, and springs for transportation and industrial programs.",
    ["Springs", "Wire forms", "Fourslide"],
    "https://www.associatedspring.com/products/wire-forms.aspx",
  ),
  shop(
    "insteel-hazleton",
    "Insteel Wire Products (Hazleton)",
    "Hazleton",
    "PA",
    "Welded wire reinforcement plant in Hazleton, PA. Construction mesh and strand — not CNC 3D from coil.",
    ["Welded wire reinforcement", "Drawn wire"],
    "https://insteel.com/about-us/locations/#hazleton-pa",
  ),

  // ── Wisconsin ─────────────────────────────────────────────────────────────
  shop(
    "brunner-wire-products",
    "Brunner Wire Products, Inc.",
    "Elroy",
    "WI",
    "Custom wire forms and assemblies since 1963. Outdoor power, ag, and sporting goods. Elroy, WI.",
    ["Wire forms", "Welded assemblies", "OEM forms"],
    "https://bwp-us.com",
  ),
  shop(
    "badger-precision-spring",
    "Badger Precision Spring, Inc.",
    "Genoa City",
    "WI",
    "Custom precision springs, wire forms, and stampings since 1983. Genoa City, WI. Prototype to production.",
    ["Springs", "Wire forms", "Stampings"],
    "http://www.badgerspring.com",
  ),
  shop(
    "madison-precision-springs",
    "Madison Precision Springs",
    "Menomonee Falls",
    "WI",
    "Custom compression, extension, and torsion springs and wire forms. Menomonee Falls, WI.",
    ["Compression springs", "Extension springs", "Torsion springs", "Wire forms"],
    "https://madisonprecisionsprings.com",
  ),
  shop(
    "exacto-spring",
    "Exacto Spring Corp.",
    "Grafton",
    "WI",
    "Precision springs and wire forms since the 1950s. About 0.001–0.156 in wire. Grafton, WI. 125,000 sq ft.",
    ["Compression springs", "Torsion springs", "Extension springs", "Wire forms"],
    "https://exacto.com",
  ),
  shop(
    "wcs-industries",
    "WCS Industries",
    "Muskego",
    "WI",
    "Wisconsin Coil Spring dba WCS Industries. Mechanical springs, wire forms, and flat forms since 1958. Muskego, WI. Also headed parts in Minnesota.",
    ["Mechanical springs", "Wire forms", "Flat forms"],
    "https://www.wcsindustries.com",
  ),
  shop(
    "fox-valley-spring",
    "Fox Valley Spring",
    "Greenville",
    "WI",
    "MW Components plant in Greenville (Appleton), WI. Springs, wire forms, and flat springs since 1989. 10-piece minimum on their site.",
    ["Springs", "Wire forms", "Flat springs"],
    "https://www.mwcomponents.com/locations/fox-valley-spring",
  ),
  shop(
    "k-tek-wisconsin",
    "K-TEK Wisconsin",
    "Baldwin",
    "WI",
    "K-TEK plant at 750 Vandeberg Street, Baldwin, WI. Stampings, laser, weldments, and CNC wire forms. Sister plant in Charlotte, NC.",
    ["CNC wire forming", "Stampings", "Weldments"],
    "https://www.ktek-net.com/resources/examples-gallery/",
  ),
  shop(
    "jagemann-stamping",
    "Jagemann Stamping Company",
    "Manitowoc",
    "WI",
    "Deep-draw, fineblank, and progressive stampings. Manitowoc, WI. 200,000 sq ft, 15–700 ton presses. Not a round-wire CNC job shop.",
    ["Deep draw", "Progressive stampings", "Fineblanking"],
    "https://jagemann.com",
  ),
  shop(
    "custom-wire-technologies",
    "Custom Wire Technologies",
    "Port Washington",
    "WI",
    "Medical OEM wire: coiling, grinding, fine wire forms, compression springs. 1123 Mineral Springs Drive, Port Washington, WI. ISO 13485. Fine medical wire — not 4–14 mm frames.",
    ["Medical wire", "Coiling", "Wire forms", "Compression springs"],
    "https://customwiretech.com",
  ),

  // ── Indiana ───────────────────────────────────────────────────────────────
  shop(
    "hoosier-spring",
    "Hoosier Spring Company, Inc.",
    "South Bend",
    "IN",
    "Precision helical springs and wire forms since 1954. Aerospace, nuclear, military, and industrial. South Bend, IN.",
    ["Helical springs", "Wire forms", "Clock springs"],
    "https://www.hoosierspring.com",
  ),
  shop(
    "circle-m-spring",
    "Circle M Spring, Inc.",
    "Warsaw",
    "IN",
    "Springs, wire forms, stampings, and precision machining. Warsaw, IN. Orthopedic and industrial work.",
    ["Springs", "Wire forms", "Stampings", "Precision machining"],
    "https://circlemspring.com",
  ),
  shop(
    "kewanna-metal-specialties",
    "Kewanna Metal Specialties, Inc.",
    "Kewanna",
    "IN",
    "Wire forms and welded assemblies since 1960. Racks, motor mounts, powder coat, stainless baskets. Kewanna, IN.",
    ["Wire forms", "Welded assemblies", "Powder coating", "Baskets"],
    "https://kmswire.com",
  ),
  shop(
    "myers-spring",
    "Myers Spring Company",
    "Logansport",
    "IN",
    "Custom springs and wire forms since 1946. About 0.005–0.750 in hard, heavier annealed. IATF 16949 and ISO 9001. Logansport, IN.",
    ["Compression springs", "Extension springs", "Torsion springs", "Wire forms"],
    "https://myersspring.com",
  ),
  shop(
    "fort-wayne-metals",
    "Fort Wayne Metals",
    "Fort Wayne",
    "IN",
    "Medical wire melting, drawing, and some forming. Fort Wayne, IN. Fine medical wire — not 4–14 mm frames.",
    ["Medical wire", "Wire drawing"],
    "https://www.fwmetals.com",
  ),
  shop(
    "advance-wire-form-south-bend",
    "Advance Wire Form",
    "South Bend",
    "IN",
    "Custom extension, compression, torsion springs and wire forms. 3702 W. Sample St, South Bend, IN. In-house paint, oxidize, heat treat. Not Advance Wire Forming in Cleveland.",
    ["Springs", "Wire forms", "Heat treating"],
    "https://advwireform.com",
  ),
  shop(
    "midwest-spring-mentone",
    "Mid-West Spring & Stamping (Mentone)",
    "Mentone",
    "IN",
    "Corporate HQ and manufacturing at 105 Etna St, Mentone, IN. Springs, stampings, wire forms, fourslide, vertislide. About 0.00–0.750 in. Romeoville, IL plant is listed separately.",
    ["Springs", "Stampings", "Wire forms", "Fourslide"],
    "https://www.mwspring.com/contact-us/",
  ),

  // ── Illinois ──────────────────────────────────────────────────────────────
  shop(
    "rockford-spring",
    "Rockford Spring Company",
    "Rockford",
    "IL",
    "Custom precision springs, wire forms, and assemblies since 1952. About 0.004–0.312 in wire. Rockford, IL. Separate from Rockford Specialties.",
    ["Springs", "Wire forms", "Assemblies"],
    "https://www.rockfordspring.com",
  ),
  shop(
    "gilbert-spring",
    "Gilbert Spring Corporation",
    "Chicago",
    "IL",
    "Springs, fourslide wire and strip, wire forms, welded rings, and stampings since 1964. Chicago, IL.",
    ["Springs", "Fourslide", "Wire forms", "Stampings"],
    "https://www.gilbertspring.com",
  ),
  shop(
    "all-rite-spring",
    "All-Rite Spring Company",
    "Spring Grove",
    "IL",
    "Clock, compression, extension, torsion springs and shaped wire forms. Spring Grove, IL. IATF 16949. High-volume automotive.",
    ["Clock springs", "Compression springs", "Wire forms"],
    "https://allrite.com",
  ),
  shop(
    "lewis-spring",
    "Lewis Spring & Manufacturing",
    "Niles",
    "IL",
    "Custom springs, rings, stampings, and wire forms since 1945. Niles, IL (Chicago).",
    ["Springs", "Wire forms", "Stampings", "Rings"],
    "https://lewisspring.com",
  ),
  shop(
    "patrick-manufacturing",
    "Patrick Manufacturing",
    "Elk Grove Village",
    "IL",
    "Compression, extension, torsion, magazine, drawbar springs and wire forms. Elk Grove Village, IL.",
    ["Springs", "Wire forms", "Assemblies"],
    "https://patrickspring.com",
  ),
  shop(
    "pj-spring",
    "P.J. Spring Company, Inc.",
    "West Chicago",
    "IL",
    "Custom spring manufacturing in West Chicago, IL.",
    ["Springs", "Wire forms"],
    "https://pjspring.com",
  ),
  shop(
    "rr-spring",
    "R-R Spring Corporation",
    "Addison",
    "IL",
    "Family spring manufacturer since 1970. 100 Laura Drive, Addison, IL. ISO 9001. Separate from S & W Manufacturing in the same city.",
    ["Springs", "Wire forms"],
    "https://rrspring.com",
  ),
  shop(
    "sterling-spring-bedford-park",
    "Sterling Spring (Bedford Park)",
    "Bedford Park",
    "IL",
    "Sterling’s second roof at 7171 W. 65th Street, Bedford Park, IL. Custom springs, wire forms, fourslide, stampings. ISO 9001 and AS9100D. Chicago plant is listed separately.",
    ["Springs", "Wire forms", "Fourslide", "Stampings"],
    "https://www.sterlingspring.com/custom-wire-forms",
  ),

  // ── Kentucky ──────────────────────────────────────────────────────────────
  shop(
    "wb-jones-spring",
    "W.B. Jones Spring Co.",
    "Wilder",
    "KY",
    "Stock and custom compression, extension, torsion springs and CNC wire forms. Wilder, KY. Family-owned. Fast catalog and custom.",
    ["Stock springs", "Custom springs", "Wire forms", "CNC forming"],
    "https://springsfast.com",
  ),
  shop(
    "ken-tron",
    "Ken-Tron Mfg., Inc.",
    "Owensboro",
    "KY",
    "Stampings, fourslide / multi-slide, wire forms (clips, pins, rings, springs), and redrawn wire. Owensboro, KY. ISO / AS9100.",
    ["Fourslide", "Stampings", "Wire forms", "Drawn wire"],
    "https://www.ken-tron.com",
  ),
  shop(
    "insteel-hickman",
    "Insteel Wire Products (Hickman)",
    "Hickman",
    "KY",
    "Welded wire reinforcement plant on the Mississippi in Hickman, KY. Construction mesh mill — not CNC 3D from coil.",
    ["Welded wire reinforcement", "Drawn wire"],
    "https://insteel.com/about-us/locations/#hickman-ky",
  ),
  shop(
    "nashville-wire-kentucky",
    "Nashville Wire Products (Kentucky)",
    "Kentucky plants",
    "KY",
    "Nashville Wire lists Kentucky in the plant footprint for welded material-handling wire and CNC to about 0.375 in. Confirm which KY roof before you ship a print.",
    ["CNC wire forming", "Welded baskets", "Material handling"],
    "https://www.nashvillewire.com/#kentucky",
  ),
  shop(
    "beneke-wire",
    "Beneke Wire Company",
    "Louisville",
    "KY",
    "Aluminum wire drawing in Louisville, KY. Mill — they draw, they do not CNC-form frames.",
    ["Drawn aluminum wire"],
    "https://www.benekewire.com",
  ),
  shop(
    "hendrick-screen",
    "Hendrick Screen Company",
    "Owensboro",
    "KY",
    "Wedge wire and profile-bar screens at 3074 Medley Road, Owensboro, KY. Sister to Hendrick Manufacturing in Carbondale, PA. Industrial screening — not a generic spring job shop.",
    ["Wedge wire screens", "Profile bar screens"],
    "https://hendrickcorp.com/screen",
  ),

  // ── North Carolina ────────────────────────────────────────────────────────
  shop(
    "newcomb-spring-north-carolina",
    "Newcomb Spring of North Carolina",
    "Gastonia",
    "NC",
    "Newcomb plant at 2633 Plastics Drive, Gastonia, NC. Compression, extension, wire forms, and stampings. ISO 9001. Covers the Carolinas, Virginia, and the Mid-Atlantic.",
    ["Springs", "Wire forms", "Stampings"],
    "https://www.newcombspring.com/locations/north-carolina",
  ),
  shop(
    "southern-precision-spring",
    "Southern Precision Spring",
    "Charlotte",
    "NC",
    "Custom compression, extension, torsion springs and wire forms including mattress retainers. Charlotte, NC. Motion furniture and industrial.",
    ["Extension springs", "Wire forms", "Compression springs"],
    "https://www.spspring.com",
  ),
  shop(
    "marvel-springs",
    "Marvel Springs",
    "Flat Rock",
    "NC",
    "High-volume precision springs, clips, and wire forms. Flat Rock, NC, plus a South Africa plant. CNC coilers with in-line gauging.",
    ["Micro springs", "Wire forms", "Compression springs"],
    "https://marvelsprings.com",
  ),
  shop(
    "k-tek-charlotte",
    "K-TEK Charlotte",
    "Charlotte",
    "NC",
    "Precision stampings, laser, weldments, and CNC wire forms. 10240 Industrial Drive, Charlotte, NC. Sister plant in Baldwin, WI.",
    ["CNC wire forming", "Stampings", "Laser", "Weldments"],
    "https://www.ktek-net.com",
  ),
  shop(
    "southern-spring-stokesdale",
    "Southern Spring (Stokesdale)",
    "Stokesdale",
    "NC",
    "Southern Spring & Stamping lists Stokesdale, NC in addition to the Venice, FL plant. Confirm which roof runs the part.",
    ["Springs", "Stampings", "Wire forms"],
    "https://www.southernspring.com/springs-wire-forms",
  ),
  shop(
    "red-tail-group",
    "Red Tail Group LLC",
    "Asheville",
    "NC",
    "Veteran-owned CNC 2D/3D wire bending, 0.044–0.500 in forms, straighten-and-cut to 0.625 in, powder-coat hooks, racks, welded assemblies. 120 Lyman Street, Asheville, NC.",
    ["CNC 2D/3D wire", "Straighten and cut", "Welded assemblies", "Powder coating"],
    "https://redtailwire.com",
  ),

  // ── South Carolina ────────────────────────────────────────────────────────
  shop(
    "springmasters-greer",
    "Springmasters (MW Components)",
    "Greer",
    "SC",
    "MW Components plant in Greer, SC. Wire forms about 0.040–0.500 in, springs, machined parts, and assemblies since 1961. Separate from Duer / Greer: Springs.",
    ["Wire forms", "Springs", "Machined parts"],
    "https://www.mwcomponents.com/locations/springmasters",
  ),
  shop(
    "diamond-wire-spring-southeast",
    "Diamond Wire Spring (Southeast)",
    "Taylors",
    "SC",
    "ISO Southeast plant at 150 Landmark Dr, Taylors, SC. CNC coil and wire forms about 0.008–0.312 in. Opened 1971.",
    ["Springs", "Wire forms", "CNC coiling"],
    "https://diamondwire.com/location/southeast-plant/",
  ),
  shop(
    "metal-and-wire-ridgeway",
    "Metal and Wire Products (Ridgeway)",
    "Ridgeway",
    "SC",
    "SC plant at 300 Tillessen Blvd, Ridgeway, SC. CNC wire forms to 12 mm, compression/torsion/extension springs. Corporate offices are Salem, OH.",
    ["CNC wire forming", "Springs", "Tube forms"],
    "https://metalandwire.com/capabilities/spring-and-wire-forms",
  ),

  // ── Florida ───────────────────────────────────────────────────────────────
  shop(
    "gilco-spring-florida",
    "Gilco Spring of Florida",
    "Oldsmar",
    "FL",
    "Gilco’s remaining plant: 3991 Tampa Road, Oldsmar, FL. Compression, extension, torsion, flat springs, wire forms, and fourslide. ISO 9001. About 0.007–0.315 in wire.",
    ["Springs", "Wire forms", "Fourslide"],
    "https://gilcospring.com/about-us/",
  ),
  shop(
    "optimum-spring",
    "Optimum Spring Manufacturing",
    "Ponte Vedra",
    "FL",
    "Custom coil springs in exotic alloys (nickel, Elgiloy, titanium, copper). About 0.004–0.500 in. Ponte Vedra, FL. Fine / corrosive service — not heavy frames.",
    ["Custom springs", "Exotic alloys", "Compression springs"],
    "https://optimumspring.com",
  ),
  shop(
    "southern-spring-stamping",
    "Southern Spring & Stamping, Inc.",
    "Venice",
    "FL",
    "Family shop in Venice, FL. Springs, stampings, sheet, robotic weld, in-line heat treat. ISO 9001. Wire about 0.004–0.472 in.",
    ["Springs", "Wire forms", "Stampings", "Sheet metal"],
    "https://southernspring.com",
  ),
  shop(
    "insteel-jacksonville",
    "Insteel Wire Products (Jacksonville)",
    "Jacksonville",
    "FL",
    "WWR plant at 3050 Melson Avenue, Jacksonville, FL. Construction mesh mill. Separate from Jacksonville Spring already listed.",
    ["Welded wire reinforcement"],
    "https://insteel.com/about-us/locations/#jacksonville-fl",
  ),
  shop(
    "insteel-sanderson",
    "Insteel Wire Products (Sanderson)",
    "Sanderson",
    "FL",
    "Insteel plant in Sanderson, FL. Prestressed strand / WWR. Mill — not CNC 3D from coil.",
    ["Prestressed strand", "Welded wire reinforcement"],
    "https://insteel.com/about-us/locations/#sanderson-fl",
  ),

  // ── Maryland ──────────────────────────────────────────────────────────────
  shop(
    "maryland-precision-spring",
    "Maryland Precision Spring",
    "Essex",
    "MD",
    "MW Components plant in Essex, MD (8900 Kelso Dr). Disc springs, constant-force, coiled springs, stampings, fourslide and rotary forming. ISO 9001 and AS9100D. About 0.312 in max coil wire on their site.",
    ["Disc springs", "Constant-force springs", "Fourslide", "Wire forms"],
    "https://www.mwcomponents.com/locations/maryland-precision-spring",
  ),

  // ── New Jersey ────────────────────────────────────────────────────────────
  shop(
    "phillips-enterprises",
    "Phillips Enterprises, Inc.",
    "Ocean",
    "NJ",
    "Made-to-order wire forming, fourslide, multislide, and stampings. 3600 Sunset Ave, Ocean, NJ. Hardware, electronics, automotive, medical.",
    ["Wire forming", "Fourslide", "Multislide", "Stampings"],
    "https://www.phillipsentinc.com",
  ),
  shop(
    "durex-inc",
    "DureX Incorporation",
    "Union",
    "NJ",
    "120,000 sq ft in Union, NJ. Progressive stampings plus wire forming, welding, and assembly. 50+ presses, 5–400 tons. Not a dedicated CNC wire cell.",
    ["Metal stamping", "Wire forming", "Tool and die"],
    "https://durexinc.com",
  ),
  shop(
    "newark-wire-cloth",
    "Newark Wire Cloth",
    "Cedar Grove",
    "NJ",
    "Woven wire cloth, filters, strainers, and fabricated mesh parts since 1911. Cedar Grove, NJ. Mesh — not CNC 3D from coil.",
    ["Wire cloth", "Filters", "Fabricated mesh"],
    "https://newarkwire.com",
  ),
  shop(
    "gj-steel-tubing",
    "G & J Steel & Tubing, Inc.",
    "Hillsborough",
    "NJ",
    "Tube cutting, bending, coiling, and end forming since 1976. Hillsborough, NJ. Tube — not round-wire CNC frames.",
    ["Tube bending", "Tube forming", "Coiling"],
    "https://gjsteel.com",
  ),

  // ── New York ──────────────────────────────────────────────────────────────
  shop(
    "better-wire-press",
    "Better Wire and Press",
    "Buffalo",
    "NY",
    "Wire forms, fourslide / multi-slide, CNC 3D bending, straighten-and-cut about 0.062–0.438 in. Buffalo, NY. Formerly Better Wire Products / Forsyth. Powder, weld, heat treat.",
    ["CNC 3D wire", "Fourslide", "Multi-slide", "Stampings"],
    "https://betterwire.com",
  ),
  shop(
    "cuddeback-machining",
    "Cuddeback Machining, Inc.",
    "Hilton",
    "NY",
    "ISO 9001. Wire-formed parts, stampings, CNC machining, in-house tool and die. Hilton, NY (Rochester). Nilson fourslide on the floor.",
    ["Wire forms", "Fourslide", "Stampings", "CNC machining"],
    "https://cuddebackmachining.com",
  ),
  shop(
    "angelica-spring",
    "Angelica Spring Company, Inc.",
    "Angelica",
    "NY",
    "Family custom springs and wire forms since 1981. Angelica, NY. Short-run and prototype. Western New York.",
    ["Custom springs", "Wire forms", "Short run"],
    "https://www.anyspring.com",
  ),

  // ── Tennessee ─────────────────────────────────────────────────────────────
  shop(
    "newcomb-spring-tennessee",
    "Newcomb Spring of Tennessee",
    "Ooltewah",
    "TN",
    "Newcomb plant in Ooltewah, TN (Chattanooga). Springs, wire forms, and stampings. ISO 9001 network.",
    ["Springs", "Wire forms", "Stampings"],
    "https://www.newcombspring.com/locations/tennessee",
  ),
  shop(
    "spring-concepts",
    "Spring Concepts",
    "Bartlett",
    "TN",
    "Compression, extension, torsion springs, stampings, and wire forms since the 1960s. Bartlett, TN (Memphis). Rush quotes.",
    ["Springs", "Stampings", "Wire forms"],
    "https://www.springconcepts.net",
  ),
  shop(
    "insteel-gallatin",
    "Insteel Wire Products (Gallatin)",
    "Gallatin",
    "TN",
    "WWR / strand plant at 630 National Drive, Gallatin, TN. Construction mesh mill — not CNC 3D from coil.",
    ["Welded wire reinforcement"],
    "https://insteel.com/about-us/locations/#gallatin-tn",
  ),
];
