import type { DirectoryCompany } from "./directory-types";

/**
 * Plants from ThomasNet wire-form lists that were not already in the
 * directory. USA forming floors only. No reps, distributors, mills, or
 * sourcing desks. RFC is intentionally not listed.
 */

function shop(
  slug: string,
  name: string,
  city: string,
  state: string,
  country: DirectoryCompany["country"],
  region: DirectoryCompany["region"],
  description: string,
  capabilities: string[],
  website?: string,
): DirectoryCompany {
  return {
    slug,
    name,
    location: `${city}, ${state}`,
    state,
    country,
    region,
    description,
    capabilities,
    ...(website ? { website } : {}),
  };
}

export const moreDirectoryCompanies: DirectoryCompany[] = [
  // ── California forming plants ──
  shop(
    "tru-form-tool-manufacturing",
    "Tru-Form Tool & Manufacturing",
    "Santa Fe Springs",
    "CA",
    "USA",
    "West",
    "Fourslide, CNC tube/wire bending, laser, and robotic welding. 14511 Anson Ave, Santa Fe Springs, CA. Their site names 100+ fourslide machines plus in-house tool-and-die.",
    ["Fourslide", "CNC wire forming", "Tube bending", "Stampings"],
    "https://www.tru-form.com/",
  ),
  shop(
    "speedy-springs",
    "Speedy Springs",
    "La Puente",
    "CA",
    "USA",
    "West",
    "Custom compression, extension, torsion springs, die springs, wire forms, light stampings, and assemblies. La Puente, CA.",
    ["Compression springs", "Wire forms", "Stampings"],
    "https://speedysprings.com/",
  ),
  shop(
    "ancar-international",
    "Ancar International",
    "Lemon Grove",
    "CA",
    "USA",
    "West",
    "Custom springs, wire forming, tube forming, and metal fabrication. 7890 Lester Avenue, Lemon Grove, CA.",
    ["Springs", "Wire forms", "Tube forming", "Metal fabrication"],
    "https://www.ancarinc.com/",
  ),
  shop(
    "rb-wire-products",
    "R&B Wire Products",
    "Santa Ana",
    "CA",
    "USA",
    "West",
    "Family wire plant making commercial laundry carts, hampers, shelving, and custom wire products. Santa Ana, CA.",
    ["Wire forming", "Welded wire products", "Wire carts"],
    "https://www.rbwire.com/",
  ),
  shop(
    "schellinger-spring",
    "Schellinger Spring, Inc.",
    "Rancho Cucamonga",
    "CA",
    "USA",
    "West",
    "CNC wire forms including spring and square wire. 8477 Utica Avenue, Rancho Cucamonga, CA. Est. 1945.",
    ["CNC wire forming", "Springs", "Wire forms"],
    "https://www.schellingerspring.com/",
  ),
  shop(
    "hn-tool-and-die",
    "HN Tool & Die Co.",
    "Corona",
    "CA",
    "USA",
    "West",
    "Fourslide and punch-press stampings, coil springs, and wire forms since 1973. 201 Jason Court, Unit B, Corona, CA.",
    ["Fourslide", "Stampings", "Coil springs", "Wire forms"],
    "http://hnspringnstampings.com/",
  ),
  shop(
    "continental-precision-stamping",
    "Continental Precision Stamping",
    "Pomona",
    "CA",
    "USA",
    "West",
    "Precision stampings, clips, rings, custom springs, and formed wire parts. 102 Exchange Place, Pomona, CA.",
    ["Stampings", "Springs", "Wire forms"],
    "https://www.cpsstamping.com/",
  ),
  shop(
    "mgm-manufacturing-alliance",
    "MGM Manufacturing Alliance Corp.",
    "Simi Valley",
    "CA",
    "USA",
    "West",
    "Build-to-print CNC machining, sheet metal, tube bending, custom springs, and wire forming. 4511 Ish Drive, Simi Valley, CA.",
    ["CNC machining", "Wire forming", "Custom springs", "Tube bending"],
    "https://www.mgmmfg.com/",
  ),
  shop(
    "walker-manufacturing-group",
    "Walker Manufacturing Group",
    "Ontario",
    "CA",
    "USA",
    "West",
    "Metal stampings, fabrication, constant-force springs, and wire forms since 1954. 1555 S Vintage Ave, Ontario, CA.",
    ["Stampings", "Springs", "Wire forms", "Fabrication"],
    "https://www.walkermanufacturing.com/",
  ),
  shop(
    "ftr-associates",
    "FTR Associates, Inc.",
    "Santa Fe Springs",
    "CA",
    "USA",
    "West",
    "CNC springs, wire forms, fourslide, and stampings. 11862 Burke Street, Santa Fe Springs, CA. Their page names Herndon CSX-20 and HAX-40 cells, wire about 0.016–0.412 in.",
    ["CNC wire forming", "Springs", "Fourslide", "Stampings"],
    "https://ftrmetalproducts.com/",
  ),
  shop(
    "centerline-precision-tube-bending",
    "CenterLine Precision Tube Bending, Inc.",
    "Dublin",
    "CA",
    "USA",
    "West",
    "Mandrel and roll tube bending plus wire and rod forming. 6355 Scarlett Court Suite 5, Dublin, CA. 1/16–2.0 in OD tube.",
    ["Tube bending", "Wire forming", "Rod forming"],
    "https://www.clptbi.com/",
  ),
  shop(
    "aranki-spring-manufacturing",
    "Aranki Spring Manufacturing",
    "Santa Fe Springs",
    "CA",
    "USA",
    "West",
    "Mechanical compression, extension, and torsion springs plus secondary looping, bending, and forming. Santa Fe Springs, CA. Est. 1989.",
    ["Compression springs", "Extension springs", "Torsion springs", "Wire forms"],
    "https://arankispring.com/",
  ),

  // ── Other USA plants from the wire-forming supplier list ──
  shop(
    "connor-manufacturing-services",
    "Connor Manufacturing Services",
    "Fairview",
    "OR",
    "USA",
    "West",
    "US plant at 22867 NE Townsend Way, Fairview, OR. CNC wire and rod forming, coiling, fourslide, stampings, and assemblies. Asia plants are separate; this listing is the Oregon floor.",
    ["CNC wire forming", "Fourslide", "Springs", "Stampings"],
    "https://www.connorms.com/",
  ),
  shop(
    "gall-machine",
    "Gall Machine Company, Inc.",
    "Countryside",
    "IL",
    "USA",
    "Midwest",
    "Wire forming, straighten-and-cut, cold heading, and plating since 1982. 9640 Joliet Road, Countryside, IL. About 0.062–0.500 in wire.",
    ["Wire forming", "Straighten and cut", "Cold heading", "Plating"],
    "https://gallmachine.com/",
  ),
  shop(
    "advanex-americas",
    "Advanex Americas, Inc.",
    "White House",
    "TN",
    "USA",
    "Southeast",
    "US plant for precision springs, wire forms, pins, stampings, and molded sub-assemblies. 514 Hester Drive, White House, TN. Parent is Japan; Cypress, CA is sales, not this floor.",
    ["Springs", "Wire forms", "Stampings", "Pins"],
    "https://www.advanexusa.com/",
  ),
  shop(
    "e-tube-and-wire",
    "E Tube & Wire",
    "Shrewsbury",
    "PA",
    "USA",
    "Northeast",
    "CNC wire forming, mandrel tube bending, laser, and fabrication from an 86,000 sq ft plant. Shrewsbury, PA. Baskets, guards, racks, and custom wire forms. About 0.080–1.25 in wire.",
    ["CNC wire forming", "Tube bending", "Wire baskets", "Fabrication"],
    "https://www.etubeandwire.com/",
  ),
  shop(
    "clips-and-clamps-industries",
    "Clips & Clamps Industries",
    "Plymouth",
    "MI",
    "USA",
    "Midwest",
    "CNC wire forming, strip and wire slide forming, progressive stampings, and welded assemblies. 15050 Keel Street, Plymouth, MI. Wire about 0.8–8.0 mm.",
    ["CNC wire forming", "Fourslide", "Stampings", "Welding"],
    "https://clipsclamps.com/",
  ),
  shop(
    "associated-fastening-products",
    "Associated Fastening Products, Inc.",
    "Itasca",
    "IL",
    "USA",
    "Midwest",
    "Custom wire forms and threaded wire products from the Itasca plant. 690 Hilltop Drive, Itasca, IL. About 1/32–3/4 in by 100 in. They also sell imported catalog fasteners — this listing is the US forming cell.",
    ["Wire forms", "Threaded wire products", "Fasteners"],
    "https://www.associatedfastening.com/",
  ),
  shop(
    "aristo-tec-metal-forms",
    "Aristo-Tec Metal Forms",
    "Connellsville",
    "PA",
    "USA",
    "Northeast",
    "CNC wire bending, fourslide, threading, coining, punching, and flattening. 401 Ridge Blvd, Connellsville, PA. About 0.095–0.500 in stainless, galvanized, and mild steel.",
    ["CNC wire forming", "Fourslide", "Wire forms"],
    "https://aristo-tec.com/",
  ),
  shop(
    "clark-engineering",
    "Clark Engineering Co., Inc.",
    "Owosso",
    "MI",
    "USA",
    "Midwest",
    "CNC wire forming, cold heading, tube, and machining since 1946. 1470 McMillan Road, Owosso, MI. Rod, wire, and tube parts for auto, ag, defense, and lawn-and-garden.",
    ["CNC wire forming", "Cold heading", "Tube forming", "Machining"],
    "https://clarkengineering.net/",
  ),
];
