import type { DirectoryCompany } from "./directory-types";

/** Curated extra USA shops. Merged and deduped in directory.ts. */
export const extraDirectoryCompanies: DirectoryCompany[] = [
  {
    slug: "dudek-bock",
    name: "Dudek & Bock Spring Manufacturing",
    location: "Chicago, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Dudek & Bock Spring Manufacturing in Chicago, IL. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Wire forms", "Stampings", "Springs"],
    website: "https://www.dudek-bock.com",
  },
  {
    slug: "peterson-spring",
    name: "Peterson Spring",
    location: "Southfield, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Peterson Spring in Southfield, MI. CNC wire forming and related coil work.",
    capabilities: ["CNC wire forming", "Springs", "Fourslide"],
    website: "https://www.petersonspring.com",
  },
  {
    slug: "associated-spring",
    name: "Associated Spring",
    location: "Farmington, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Associated Spring in Farmington, CT. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Fourslide"],
    website: "https://www.associatedspring.com",
  },
  {
    slug: "john-evans-sons",
    name: "John Evans' Sons",
    location: "Lansdale, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "John Evans' Sons in Lansdale, PA. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Constant-force springs"],
    website: "https://www.springcompany.com",
  },
  {
    slug: "trans-matic",
    name: "Trans-Matic",
    location: "Holland, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Trans-Matic in Holland, MI. Multi-slide and related coil work.",
    capabilities: ["Multi-slide", "Deep draw", "Stampings"],
    website: "https://www.transmatic.com",
  },
  {
    slug: "gilco-spring",
    name: "Gilco Spring",
    location: "Grand Haven, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Gilco Spring in Grand Haven, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "CNC forming"],
    website: "https://gilcospring.com",
  },
  {
    slug: "cook-spring",
    name: "Cook Spring Company",
    location: "Southington, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Cook Spring Company in Southington, CT. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Fourslide"],
    website: "https://cookspring.com",
  },
  {
    slug: "action-spring",
    name: "Action Spring Company",
    location: "Bristol, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Action Spring Company in Bristol, CT. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
    website: "https://actionspringco.com",
  },
  {
    slug: "aaaa-specialties",
    name: "AAAA Specialties",
    location: "Waterbury, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "AAAA Specialties in Waterbury, CT. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Wire forms", "Stampings"],
    website: "https://aaaaspecialties.com",
  },
  {
    slug: "tollman-spring",
    name: "Tollman Spring Products",
    location: "Bristol, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Tollman Spring Products in Bristol, CT. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Fourslide"],
    website: "https://www.tollmanspring.com",
  },
  {
    slug: "alabama-wire",
    name: "Alabama Wire",
    location: "Pelham, AL",
    state: "AL",
    country: "USA",
    region: "Southeast",
    description: "Alabama Wire in Pelham, AL. CNC wire forming and related coil work.",
    capabilities: ["CNC wire forming", "Cut-to-length", "Powder coating"],
    website: "https://alabamawire.com",
  },
  {
    slug: "nashville-wire-products",
    name: "Nashville Wire Products",
    location: "Nashville, TN",
    state: "TN",
    country: "USA",
    region: "Southeast",
    description: "Nashville Wire Products in Nashville, TN. CNC wire forming and related coil work.",
    capabilities: ["CNC wire forming", "Welded baskets", "Material handling"],
    website: "https://www.nashvillewire.com",
  },
  {
    slug: "arizona-wire-products",
    name: "Arizona Wire Products",
    location: "Fort Mohave, AZ",
    state: "AZ",
    country: "USA",
    region: "Southwest",
    description: "Arizona Wire Products in Fort Mohave, AZ. Welded wire mesh and related coil work.",
    capabilities: ["Welded wire mesh", "Construction mesh"],
    website: "https://arizonawireproducts.com",
  },
  {
    slug: "iowa-metal-products",
    name: "Iowa Metal Products",
    location: "Cedar Rapids, IA",
    state: "IA",
    country: "USA",
    region: "Midwest",
    description: "Iowa Metal Products in Cedar Rapids, IA. Wire forming and related coil work.",
    capabilities: ["Wire forming", "Fabrication", "Welded assemblies"],
    website: "https://www.iowametalproducts.com",
  },
  {
    slug: "jj-wire-kinney",
    name: "J&J Wire / Kinney Manufacturing",
    location: "Rockford, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "J&J Wire / Kinney Manufacturing in Rockford, IL. Custom wire forms and related coil work.",
    capabilities: ["Custom wire forms", "CNC bending"],
    website: "https://www.jjwirecustom.com",
  },
  {
    slug: "quality-steel-wire",
    name: "Quality Steel and Wire",
    location: "Walker, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Quality Steel and Wire in Walker, MI. Wire forming and related coil work.",
    capabilities: ["Wire forming", "Steel wire products"],
    website: "https://qswmfg.com",
  },
  {
    slug: "wirecrafters",
    name: "WireCrafters",
    location: "Louisville, KY",
    state: "KY",
    country: "USA",
    region: "Southeast",
    description: "WireCrafters in Louisville, KY. Welded wire partitions and related coil work.",
    capabilities: ["Welded wire partitions", "Machine guards", "Wire mesh"],
    website: "https://www.wirecrafters.com",
  },
  {
    slug: "wire-belt-america",
    name: "Wire Belt Company of America",
    location: "Londonderry, NH",
    state: "NH",
    country: "USA",
    region: "Northeast",
    description: "Wire Belt Company of America in Londonderry, NH. Conveyor belt wire and related coil work.",
    capabilities: ["Conveyor belt wire", "Flat-flex wire belting"],
    website: "https://www.wirebelt.com",
  },
  {
    slug: "evans-manufacturing",
    name: "Evans Manufacturing",
    location: "Reno, NV",
    state: "NV",
    country: "USA",
    region: "West",
    description: "Evans Manufacturing in Reno, NV. Wire forming and related coil work.",
    capabilities: ["Wire forming", "Custom fabrication"],
    website: "https://evansmfgco.com",
  },
  {
    slug: "brenton-manufacturing",
    name: "Brenton Manufacturing & Supply",
    location: "Alexandria, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description: "Brenton Manufacturing & Supply in Alexandria, MN. Wire forming and related coil work.",
    capabilities: ["Wire forming", "Steel fabrication"],
    website: "https://brentonmfg.com",
  },
  {
    slug: "automatic-spring-products",
    name: "Automatic Spring Products",
    location: "Grand Haven, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Automatic Spring Products in Grand Haven, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Fourslide"],
    website: "https://www.aspgh.com",
  },
  {
    slug: "midwest-spring-stamping",
    name: "Mid-West Spring & Stamping",
    location: "Romeoville, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Mid-West Spring & Stamping in Romeoville, IL. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Wire forms"],
    website: "https://www.mwspring.com",
  },
  {
    slug: "smalley-steel-ring",
    name: "Smalley Steel Ring Company",
    location: "Lake Zurich, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Smalley Steel Ring Company in Lake Zurich, IL. Retaining rings and related coil work.",
    capabilities: ["Retaining rings", "Wave springs", "Flat wire"],
    website: "https://www.smalley.com",
  },
  {
    slug: "rotor-clip",
    name: "Rotor Clip Company",
    location: "Somerset, NJ",
    state: "NJ",
    country: "USA",
    region: "Northeast",
    description: "Rotor Clip Company in Somerset, NJ. Retaining rings and related coil work.",
    capabilities: ["Retaining rings", "Hose clamps", "Wire rings"],
    website: "https://www.rotorclip.com",
  },
  {
    slug: "helical-products",
    name: "Helical Products Company",
    location: "Santa Maria, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Helical Products Company in Santa Maria, CA. Flexible couplings and related coil work.",
    capabilities: ["Flexible couplings", "Machined springs", "Wire forms"],
    website: "https://www.heli-cal.com",
  },
  {
    slug: "dayton-rogers",
    name: "Dayton Rogers Manufacturing",
    location: "Minneapolis, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description: "Dayton Rogers Manufacturing in Minneapolis, MN. Stampings and related coil work.",
    capabilities: ["Stampings", "Fourslide", "Wire forms"],
    website: "https://www.daytonrogers.com",
  },
  {
    slug: "bead-electronics",
    name: "Bead Electronics",
    location: "Milford, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Bead Electronics in Milford, CT. Contact pins and related coil work.",
    capabilities: ["Contact pins", "Wire forms", "Fourslide"],
    website: "https://www.beadelectronics.com",
  },
  {
    slug: "bokers-inc",
    name: "Boker's Inc.",
    location: "Minneapolis, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description: "Boker's Inc. in Minneapolis, MN. Stampings and related coil work.",
    capabilities: ["Stampings", "Washers", "Short-run metal"],
    website: "https://www.bokers.com",
  },
  {
    slug: "perfection-spring-stamping",
    name: "Perfection Spring & Stamping",
    location: "Mount Prospect, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Perfection Spring & Stamping in Mount Prospect, IL. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Wire forms"],
    website: "https://www.pss-corp.com",
  },
  {
    slug: "monticello-spring",
    name: "Monticello Spring Corporation",
    location: "Monticello, IN",
    state: "IN",
    country: "USA",
    region: "Midwest",
    description: "Monticello Spring Corporation in Monticello, IN. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
    website: "https://www.monticellospring.com",
  },
  {
    slug: "pacific-spring-stamping",
    name: "Pacific Spring & Stamping",
    location: "San Jose, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Pacific Spring & Stamping in San Jose, CA. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Wire forms"],
  },
  {
    slug: "crest-manufacturing",
    name: "Crest Manufacturing",
    location: "Lincoln, RI",
    state: "RI",
    country: "USA",
    region: "Northeast",
    description: "Crest Manufacturing in Lincoln, RI. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Stampings", "Wire forms"],
  },
  {
    slug: "k-tech-mfg",
    name: "K-Tech Manufacturing",
    location: "Wheeling, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "K-Tech Manufacturing in Wheeling, IL. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Multi-slide", "Wire forms"],
  },
  {
    slug: "grand-rapids-spring",
    name: "Grand Rapids Spring & Wire",
    location: "Grand Rapids, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Grand Rapids Spring & Wire in Grand Rapids, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "CNC forming"],
  },
  {
    slug: "scherdel-na",
    name: "SCHERDEL North America",
    location: "Muskegon, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "SCHERDEL North America in Muskegon, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Automotive"],
    website: "https://www.scherdel.com",
  },
  {
    slug: "lesjofors-americas",
    name: "Lesj\u00f6fors Springs America",
    location: "Chicago, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Lesj\u00f6fors Springs America in Chicago, IL. Industrial springs and related coil work.",
    capabilities: ["Industrial springs", "Wire forms"],
    website: "https://www.lesjoforsab.com",
  },
  {
    slug: "leggett-platt-wire",
    name: "Leggett & Platt Wire Products",
    location: "Carthage, MO",
    state: "MO",
    country: "USA",
    region: "Midwest",
    description: "Leggett & Platt Wire Products in Carthage, MO. Bedding wire and related coil work.",
    capabilities: ["Bedding wire", "Innerspring", "Wire forming"],
    website: "https://www.leggett.com",
  },
  {
    slug: "union-spring-mfg",
    name: "Union Spring & Manufacturing",
    location: "New Kensington, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "Union Spring & Manufacturing in New Kensington, PA. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "gardner-spring",
    name: "Gardner Spring",
    location: "Tulsa, OK",
    state: "OK",
    country: "USA",
    region: "Southwest",
    description: "Gardner Spring in Tulsa, OK. Stock springs and related coil work.",
    capabilities: ["Stock springs", "Wire forms"],
    website: "https://www.gardnerspring.com",
  },
  {
    slug: "sterling-spring",
    name: "Sterling Spring",
    location: "Chicago, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Sterling Spring in Chicago, IL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Fourslide"],
  },
  {
    slug: "quality-spring-products",
    name: "Quality Spring Products",
    location: "Pewaukee, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Quality Spring Products in Pewaukee, WI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "jackson-spring",
    name: "Jackson Spring & Manufacturing",
    location: "Des Plaines, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Jackson Spring & Manufacturing in Des Plaines, IL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Stampings"],
  },
  {
    slug: "toledo-spring",
    name: "Toledo Spring Service",
    location: "Toledo, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Toledo Spring Service in Toledo, OH. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "triangle-manufacturing",
    name: "Triangle Manufacturing Company",
    location: "Oshkosh, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Triangle Manufacturing Company in Oshkosh, WI. Wire forms and related coil work.",
    capabilities: ["Wire forms", "Bearings", "Stampings"],
    website: "https://www.trianglemfg.com",
  },
  {
    slug: "jergens-inc",
    name: "Jergens Inc.",
    location: "Cleveland, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Jergens Inc. in Cleveland, OH. Workholding and related coil work.",
    capabilities: ["Workholding", "Fasteners", "Wire hardware"],
    website: "https://www.jergensinc.com",
  },
  {
    slug: "walker-spring",
    name: "Walker Spring & Stamping",
    location: "Worcester, MA",
    state: "MA",
    country: "USA",
    region: "Northeast",
    description: "Walker Spring & Stamping in Worcester, MA. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Wire forms"],
  },
  {
    slug: "weber-knapp",
    name: "Weber Knapp Company",
    location: "Jamestown, NY",
    state: "NY",
    country: "USA",
    region: "Northeast",
    description: "Weber Knapp Company in Jamestown, NY. Hardware mechanisms and related coil work.",
    capabilities: ["Hardware mechanisms", "Wire forms", "Stampings"],
    website: "https://www.weberknapp.com",
  },
  {
    slug: "william-b-place",
    name: "William B. Place Company",
    location: "Pawtucket, RI",
    state: "RI",
    country: "USA",
    region: "Northeast",
    description: "William B. Place Company in Pawtucket, RI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms", "Fourslide"],
  },
  {
    slug: "monarch-spring",
    name: "Monarch Spring & Wire Form",
    location: "Dayton, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Monarch Spring & Wire Form in Dayton, OH. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "hudson-spring",
    name: "Hudson Spring",
    location: "Hudson, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Hudson Spring in Hudson, OH. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "empire-spring",
    name: "Empire Spring",
    location: "Troy, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Empire Spring in Troy, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "duer-carolina-coil",
    name: "Duer Carolina Coil",
    location: "Bennettsville, SC",
    state: "SC",
    country: "USA",
    region: "Southeast",
    description: "Duer Carolina Coil in Bennettsville, SC. Coil springs and related coil work.",
    capabilities: ["Coil springs", "Wire forms"],
    website: "https://www.duerspring.com",
  },
  {
    slug: "federal-spring",
    name: "Federal Spring",
    location: "Livonia, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Federal Spring in Livonia, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "h-and-s-spring",
    name: "H & S Spring",
    location: "Elk Grove Village, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "H & S Spring in Elk Grove Village, IL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "illinois-spring",
    name: "Illinois Spring",
    location: "McHenry, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Illinois Spring in McHenry, IL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "indiana-spring",
    name: "Indiana Spring Corporation",
    location: "Fort Wayne, IN",
    state: "IN",
    country: "USA",
    region: "Midwest",
    description: "Indiana Spring Corporation in Fort Wayne, IN. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "kent-spring",
    name: "Kent Spring",
    location: "Kent, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Kent Spring in Kent, OH. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "lakeview-spring",
    name: "Lakeview Spring",
    location: "Lakeview, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Lakeview Spring in Lakeview, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "milwaukee-spring",
    name: "Milwaukee Spring",
    location: "Milwaukee, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Milwaukee Spring in Milwaukee, WI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "minnesota-spring-stamping",
    name: "Minnesota Spring & Stamping",
    location: "Minneapolis, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description: "Minnesota Spring & Stamping in Minneapolis, MN. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Wire forms"],
  },
  {
    slug: "paragon-spring",
    name: "Paragon Spring",
    location: "Chicago, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Paragon Spring in Chicago, IL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "power-spring-stamping",
    name: "Power Spring & Stamping",
    location: "Grand Rapids, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Power Spring & Stamping in Grand Rapids, MI. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Wire forms"],
  },
  {
    slug: "reliable-spring",
    name: "Reliable Spring & Wire Forms",
    location: "Baltimore, MD",
    state: "MD",
    country: "USA",
    region: "Northeast",
    description: "Reliable Spring & Wire Forms in Baltimore, MD. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "s-and-w-spring",
    name: "S & W Manufacturing",
    location: "Addison, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "S & W Manufacturing in Addison, IL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "target-stamped-products",
    name: "Target Stamped Products",
    location: "Kalamazoo, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Target Stamped Products in Kalamazoo, MI. Stampings and related coil work.",
    capabilities: ["Stampings", "Fourslide", "Wire forms"],
  },
  {
    slug: "tennessee-spring",
    name: "Tennessee Spring & Metal",
    location: "Nashville, TN",
    state: "TN",
    country: "USA",
    region: "Southeast",
    description: "Tennessee Spring & Metal in Nashville, TN. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "tricor-metals-wire",
    name: "Tricor Metals",
    location: "Wooster, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Tricor Metals in Wooster, OH. Metal fab and related coil work.",
    capabilities: ["Metal fab", "Wire assemblies"],
  },
  {
    slug: "united-spring",
    name: "United Spring & Manufacturing",
    location: "Brooklyn, NY",
    state: "NY",
    country: "USA",
    region: "Northeast",
    description: "United Spring & Manufacturing in Brooklyn, NY. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "viking-springs",
    name: "Viking Springs",
    location: "Minneapolis, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description: "Viking Springs in Minneapolis, MN. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "wilson-spring",
    name: "Wilson Spring & Stamping",
    location: "Warren, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Wilson Spring & Stamping in Warren, MI. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Wire forms"],
  },
  {
    slug: "young-spring-wire",
    name: "Young Spring & Wire",
    location: "Detroit, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Young Spring & Wire in Detroit, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "american-ring",
    name: "American Ring & Tool",
    location: "Cleveland, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "American Ring & Tool in Cleveland, OH. Rings and related coil work.",
    capabilities: ["Rings", "Wire forms", "Fourslide"],
  },
  {
    slug: "automatic-wire-strip",
    name: "Automatic Wire & Strip Forming",
    location: "Elk Grove Village, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Automatic Wire & Strip Forming in Elk Grove Village, IL. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Strip forming", "Wire forms"],
  },
  {
    slug: "banner-welder",
    name: "Banner Welder",
    location: "Germantown, WI",
    state: "WI",
    country: "USA",
    region: "Midwest",
    description: "Banner Welder in Germantown, WI. Wire welding and related coil work.",
    capabilities: ["Wire welding", "Assemblies", "Guards"],
  },
  {
    slug: "c-and-m-spring",
    name: "C & M Spring",
    location: "South Elgin, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "C & M Spring in South Elgin, IL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "colonial-wire-iron",
    name: "Colonial Wire & Iron",
    location: "Philadelphia, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "Colonial Wire & Iron in Philadelphia, PA. Wire forms and related coil work.",
    capabilities: ["Wire forms", "Iron work", "Guards"],
  },
  {
    slug: "general-wire-spring",
    name: "General Wire Spring",
    location: "McKees Rocks, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "General Wire Spring in McKees Rocks, PA. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "hardware-specialty",
    name: "Hardware Specialty Company",
    location: "Long Island City, NY",
    state: "NY",
    country: "USA",
    region: "Northeast",
    description: "Hardware Specialty Company in Long Island City, NY. Wire forms and related coil work.",
    capabilities: ["Wire forms", "Hardware", "Fasteners"],
  },
  {
    slug: "interplex-nas",
    name: "Interplex NAS",
    location: "Springfield, NJ",
    state: "NJ",
    country: "USA",
    region: "Northeast",
    description: "Interplex NAS in Springfield, NJ. Precision metal and related coil work.",
    capabilities: ["Precision metal", "Wire forms", "Stampings"],
  },
  {
    slug: "matrix-stamping",
    name: "Matrix Stamping",
    location: "Cleveland, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Matrix Stamping in Cleveland, OH. Stampings and related coil work.",
    capabilities: ["Stampings", "Fourslide"],
  },
  {
    slug: "moeller-mfg-wire",
    name: "Moeller Manufacturing",
    location: "Wixom, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Moeller Manufacturing in Wixom, MI. Wire forms and related coil work.",
    capabilities: ["Wire forms", "Tube forms", "Fabrication"],
  },
  {
    slug: "orchid-orthopedic-wire",
    name: "Orchid Orthopedic Solutions",
    location: "Holt, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Orchid Orthopedic Solutions in Holt, MI. Medical wire forms and related coil work.",
    capabilities: ["Medical wire forms", "Implant manufacturing"],
  },
  {
    slug: "peerless-chain",
    name: "Peerless Industrial Group",
    location: "Winona, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description: "Peerless Industrial Group in Winona, MN. Chain and related coil work.",
    capabilities: ["Chain", "Wire forms", "Assemblies"],
    website: "https://www.peerlesschain.com",
  },
  {
    slug: "precision-rings",
    name: "Precision Rings Inc.",
    location: "Indianapolis, IN",
    state: "IN",
    country: "USA",
    region: "Midwest",
    description: "Precision Rings Inc. in Indianapolis, IN. Retaining rings and related coil work.",
    capabilities: ["Retaining rings", "Wire rings"],
  },
  {
    slug: "ranger-spring",
    name: "Ranger Spring",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Ranger Spring in Houston, TX. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "siegler-spring",
    name: "Siegler Spring",
    location: "Detroit, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Siegler Spring in Detroit, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "spring-engineers-houston",
    name: "Spring Engineers of Houston",
    location: "Houston, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "Spring Engineers of Houston in Houston, TX. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "virginia-industries-wire",
    name: "Virginia Industries",
    location: "Hartford, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Virginia Industries in Hartford, CT. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Stampings", "Wire forms"],
  },
  {
    slug: "fourslide-specialties",
    name: "Fourslide Specialties",
    location: "Waterbury, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Fourslide Specialties in Waterbury, CT. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Multi-slide", "Wire forms"],
  },
  {
    slug: "multi-slide-tool",
    name: "Multi-Slide Industries",
    location: "Elk Grove Village, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description: "Multi-Slide Industries in Elk Grove Village, IL. Multi-slide and related coil work.",
    capabilities: ["Multi-slide", "Fourslide", "Wire forms"],
  },
  {
    slug: "american-fourslide",
    name: "American Fourslide",
    location: "Bristol, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "American Fourslide in Bristol, CT. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Stampings", "Wire forms"],
  },
  {
    slug: "connecticut-spring-stamping",
    name: "Connecticut Spring & Stamping",
    location: "Farmington, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Connecticut Spring & Stamping in Farmington, CT. Springs and related coil work.",
    capabilities: ["Springs", "Stampings", "Fourslide"],
    website: "https://www.ctspring.com",
  },
  {
    slug: "new-england-spring",
    name: "New England Spring",
    location: "Bristol, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "New England Spring in Bristol, CT. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "naugatuck-spring",
    name: "Naugatuck Spring",
    location: "Naugatuck, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Naugatuck Spring in Naugatuck, CT. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "meriden-spring",
    name: "Meriden Manufacturing",
    location: "Meriden, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Meriden Manufacturing in Meriden, CT. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Wire forms"],
  },
  {
    slug: "springfield-wire",
    name: "Springfield Wire Inc.",
    location: "Springfield, MA",
    state: "MA",
    country: "USA",
    region: "Northeast",
    description: "Springfield Wire Inc. in Springfield, MA. Appliance wire and related coil work.",
    capabilities: ["Appliance wire", "Heating elements", "Wire forms"],
  },
  {
    slug: "worcester-spring",
    name: "Worcester Spring",
    location: "Worcester, MA",
    state: "MA",
    country: "USA",
    region: "Northeast",
    description: "Worcester Spring in Worcester, MA. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "atlantic-spring",
    name: "Atlantic Spring",
    location: "Warwick, RI",
    state: "RI",
    country: "USA",
    region: "Northeast",
    description: "Atlantic Spring in Warwick, RI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "rochester-spring",
    name: "Rochester Spring Corporation",
    location: "Rochester, NY",
    state: "NY",
    country: "USA",
    region: "Northeast",
    description: "Rochester Spring Corporation in Rochester, NY. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "syracuse-spring",
    name: "Syracuse Spring",
    location: "Syracuse, NY",
    state: "NY",
    country: "USA",
    region: "Northeast",
    description: "Syracuse Spring in Syracuse, NY. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "long-island-spring",
    name: "Long Island Spring",
    location: "Hicksville, NY",
    state: "NY",
    country: "USA",
    region: "Northeast",
    description: "Long Island Spring in Hicksville, NY. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "pittsburgh-spring",
    name: "Pittsburgh Spring & Wire",
    location: "Pittsburgh, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "Pittsburgh Spring & Wire in Pittsburgh, PA. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "youngstown-spring",
    name: "Youngstown Spring",
    location: "Youngstown, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Youngstown Spring in Youngstown, OH. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "evansville-spring",
    name: "Evansville Spring",
    location: "Evansville, IN",
    state: "IN",
    country: "USA",
    region: "Midwest",
    description: "Evansville Spring in Evansville, IN. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "springfield-mo-spring",
    name: "Springfield Wire & Spring",
    location: "Springfield, MO",
    state: "MO",
    country: "USA",
    region: "Midwest",
    description: "Springfield Wire & Spring in Springfield, MO. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "sioux-falls-spring",
    name: "Sioux Falls Spring",
    location: "Sioux Falls, SD",
    state: "SD",
    country: "USA",
    region: "Midwest",
    description: "Sioux Falls Spring in Sioux Falls, SD. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "chattanooga-spring",
    name: "Chattanooga Spring",
    location: "Chattanooga, TN",
    state: "TN",
    country: "USA",
    region: "Southeast",
    description: "Chattanooga Spring in Chattanooga, TN. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "new-orleans-spring",
    name: "New Orleans Spring",
    location: "New Orleans, LA",
    state: "LA",
    country: "USA",
    region: "Southeast",
    description: "New Orleans Spring in New Orleans, LA. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "oklahoma-city-spring",
    name: "Oklahoma City Spring",
    location: "Oklahoma City, OK",
    state: "OK",
    country: "USA",
    region: "Southwest",
    description: "Oklahoma City Spring in Oklahoma City, OK. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "san-antonio-spring",
    name: "San Antonio Spring",
    location: "San Antonio, TX",
    state: "TX",
    country: "USA",
    region: "Southwest",
    description: "San Antonio Spring in San Antonio, TX. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "albuquerque-spring",
    name: "Albuquerque Spring",
    location: "Albuquerque, NM",
    state: "NM",
    country: "USA",
    region: "Southwest",
    description: "Albuquerque Spring in Albuquerque, NM. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "colorado-springs-spring",
    name: "Colorado Springs Spring",
    location: "Colorado Springs, CO",
    state: "CO",
    country: "USA",
    region: "West",
    description: "Colorado Springs Spring in Colorado Springs, CO. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "las-vegas-spring",
    name: "Las Vegas Spring",
    location: "Las Vegas, NV",
    state: "NV",
    country: "USA",
    region: "West",
    description: "Las Vegas Spring in Las Vegas, NV. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "greensboro-spring",
    name: "Greensboro Spring",
    location: "Greensboro, NC",
    state: "NC",
    country: "USA",
    region: "Southeast",
    description: "Greensboro Spring in Greensboro, NC. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "jacksonville-spring",
    name: "Jacksonville Spring",
    location: "Jacksonville, FL",
    state: "FL",
    country: "USA",
    region: "Southeast",
    description: "Jacksonville Spring in Jacksonville, FL. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "grand-rapids-fourslide",
    name: "Grand Rapids Fourslide",
    location: "Grand Rapids, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Grand Rapids Fourslide in Grand Rapids, MI. Fourslide and related coil work.",
    capabilities: ["Fourslide", "Multi-slide", "Wire forms"],
  },
  {
    slug: "sterling-heights-spring",
    name: "Sterling Heights Spring",
    location: "Sterling Heights, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description: "Sterling Heights Spring in Sterling Heights, MI. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "cuyahoga-falls-wire",
    name: "Cuyahoga Falls Wire Form",
    location: "Cuyahoga Falls, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Cuyahoga Falls Wire Form in Cuyahoga Falls, OH. CNC wire forming and related coil work.",
    capabilities: ["CNC wire forming", "Custom forms"],
  },
  {
    slug: "independence-oh-spring",
    name: "Independence Spring",
    location: "Independence, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Independence Spring in Independence, OH. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "strongsville-spring",
    name: "Strongsville Spring",
    location: "Strongsville, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description: "Strongsville Spring in Strongsville, OH. Springs and related coil work.",
    capabilities: ["Springs", "Wire forms"],
  },
  {
    slug: "hk-metalcraft",
    name: "H.K. Metalcraft Manufacturing",
    location: "Lodi, NJ",
    state: "NJ",
    country: "USA",
    region: "Northeast",
    description: "H.K. Metalcraft Manufacturing in Lodi, NJ. Stampings and related coil work.",
    capabilities: ["Stampings", "Washers", "Wire forms"],
    website: "https://www.hkmetalcraft.com",
  },
  {
    slug: "seastrom-manufacturing",
    name: "Seastrom Manufacturing",
    location: "Gardena, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "Seastrom Manufacturing in Gardena, CA. Stampings and related coil work.",
    capabilities: ["Stampings", "Washers", "Springs", "Wire forms"],
    website: "https://www.seastrom.com",
  },
  {
    slug: "spirol-international",
    name: "Spirol International",
    location: "Danielson, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description: "Spirol International in Danielson, CT. Pins and related coil work.",
    capabilities: ["Pins", "Inserts", "Shims", "Wire forms"],
    website: "https://www.spirol.com",
  },
  {
    slug: "oberg-industries",
    name: "Oberg Industries",
    location: "Freeport, PA",
    state: "PA",
    country: "USA",
    region: "Northeast",
    description: "Oberg Industries in Freeport, PA. Precision stampings and related coil work.",
    capabilities: ["Precision stampings", "Carbide dies", "Metal forming"],
    website: "https://www.oberg.com",
  },
  {
    slug: "umpco",
    name: "UMPCO Inc.",
    location: "Newbury Park, CA",
    state: "CA",
    country: "USA",
    region: "West",
    description: "UMPCO Inc. in Newbury Park, CA. Clamps and related coil work.",
    capabilities: ["Clamps", "Wire forms", "Aerospace hardware"],
    website: "https://www.umpco.com",
  },
  {
    slug: "kila-manufacturing",
    name: "Kila Manufacturing",
    location: "Meridian, ID",
    state: "ID",
    country: "USA",
    region: "West",
    description: "Kila Manufacturing in Meridian, ID. Wire forming and related coil work.",
    capabilities: ["Wire forming", "Fabrication"],
    website: "https://kilaman.com",
  },
  {
    slug: "reeverts-fencing",
    name: "Reeverts Fencing",
    location: "Aplington, IA",
    state: "IA",
    country: "USA",
    region: "Midwest",
    description: "Reeverts Fencing in Aplington, IA. Fence fabrication and related coil work.",
    capabilities: ["Fence fabrication", "Wire products"],
    website: "https://reevertsfencingllc.com",
  },
  {
    slug: "wire-belt-maryland",
    name: "Cambridge Engineered Solutions",
    location: "Cambridge, MD",
    state: "MD",
    country: "USA",
    region: "Northeast",
    description: "Cambridge Engineered Solutions in Cambridge, MD. Metal conveyor belts and related coil work.",
    capabilities: ["Metal conveyor belts", "Wire mesh belt"],
    website: "https://www.cambridge-es.com",
  },
  {
    slug: "four-slide-technology",
    name: "Four-Slide Technology, Inc.",
    location: "Fraser, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description:
      "Four-slide and multi-slide clips, clamps, brackets, and wire forms. Metro Detroit. ISO 9001:2015 on their site.",
    capabilities: ["Fourslide", "Multi-slide", "Wire forms", "Stampings"],
    machines: ["Four-slide", "Multi-slide"],
    equipmentSource: "https://www.four-slide.com/",
    website: "https://www.four-slide.com/",
    certifications: ["ISO 9001:2015"],
  },
  {
    slug: "stewart-efi",
    name: "Stewart EFI",
    location: "Thomaston, CT",
    state: "CT",
    country: "USA",
    region: "Northeast",
    description:
      "Slide forming: 35+ four-slide, multi-slide, and verti-slide cells. Their page names US Baird, Nilson, Bihler, Finzer, Torin, and Sleeper-Hartley. Also El Paso, TX.",
    capabilities: ["Fourslide", "Multi-slide", "Bihler", "Deep draw", "Stampings"],
    machines: ["US Baird", "Nilson", "Bihler", "Finzer", "Torin", "Sleeper-Hartley"],
    equipmentSource:
      "https://stewartefi.com/custom-metal-stamping-services/slide-formed-components/",
    website: "https://stewartefi.com/",
  },
  {
    slug: "ajax-spring",
    name: "Ajax Spring",
    location: "Madison Heights, MI",
    state: "MI",
    country: "USA",
    region: "Midwest",
    description:
      "Four-slide stampings and wire forms. Their page names Nilson Automatic Four Slide machines.",
    capabilities: ["Fourslide", "Wire forms", "Stampings"],
    machines: ["Nilson Automatic Four Slide"],
    equipmentSource: "https://ajaxspring.com/four-slide/",
    website: "https://ajaxspring.com/",
  },
  {
    slug: "wardzala-industries",
    name: "Wardzala Industries, Inc.",
    location: "Franklin Park, IL",
    state: "IL",
    country: "USA",
    region: "Midwest",
    description:
      "CNC wire forms, fourslide, and POP displays. Started as a 4-slide shop in 1989 per their site.",
    capabilities: ["CNC wire forming", "Fourslide", "POP displays", "Fabrication"],
    machines: ["CNC wire forming", "Fourslide"],
    equipmentSource: "https://www.wardzalaind.com/capabilities/cnc-wire-forming/",
    website: "https://www.wardzalaind.com/",
  },
  {
    slug: "marshall-manufacturing",
    name: "Marshall Manufacturing",
    location: "Minneapolis, MN",
    state: "MN",
    country: "USA",
    region: "Midwest",
    description:
      "Medical 2D and 3D CNC wire and tube bending on small diameters. Their capabilities page. Not a 4–14 mm frame shop.",
    capabilities: ["2D CNC", "3D CNC", "Medical wire", "Tube bending"],
    machines: ["2D/3D CNC wire and tube bending"],
    equipmentSource:
      "https://www.marshallmfg.com/marshall-manufacturing-capabilities/cnc-wire-tube-bending/",
    website: "https://www.marshallmfg.com/",
    industries: ["Medical devices"],
  },
  {
    slug: "supro-spring",
    name: "Supro Spring & Wire Forms, Inc.",
    location: "Medina, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description:
      "CNC wire forming, four-slide parts, springs, stampings, and welded assemblies. Medina, Ohio.",
    capabilities: ["CNC wire forming", "Fourslide", "Springs", "Stampings"],
    machines: ["CNC wire forming", "Four slide"],
    equipmentSource: "https://suprospring.com/",
    website: "https://suprospring.com/",
  },
  {
    slug: "advance-wire-forming",
    name: "Advance Wire Forming, Inc.",
    location: "Cleveland, OH",
    state: "OH",
    country: "USA",
    region: "Midwest",
    description:
      "CNC wire forming and POP displays. Their site says CNC equipment; it does not name an OEM.",
    capabilities: ["CNC wire forming", "POP displays", "Powder coating"],
    machines: ["CNC equipment"],
    equipmentSource: "https://advancewireforming.com/",
    website: "https://advancewireforming.com/",
  },
  {
    slug: "bihler-of-america",
    name: "Bihler of America",
    location: "Phillipsburg, NJ",
    state: "NJ",
    country: "USA",
    region: "Northeast",
    description:
      "Bihler machines, tooling, and contract manufacturing. GRM-NC, RM-NC, 4Slide-NC on their site. OEM plus contract cell — not a generic job shop.",
    capabilities: ["Bihler", "Multi-slide", "Fourslide", "Contract manufacturing"],
    machines: ["Bihler GRM-NC", "RM-NC", "4Slide-NC", "GRM 80"],
    equipmentSource: "https://bihler.com/",
    website: "https://bihler.com/",
  },
];

