import type { DirectoryCompany } from "./directory-types";

/**
 * SMI Find-a-Springmaker members not already in the directory.
 * USA and Canada plants only. Unique slug + name. Same-brand plants
 * use a location path or hash so they do not collapse into the parent.
 */

function shop(
  slug: string,
  name: string,
  city: string,
  state: string,
  country: DirectoryCompany["country"],
  region: DirectoryCompany["region"],
  description: string,
  capabilities: string[],
  website?: string,
): DirectoryCompany {
  return {
    slug,
    name,
    location: `${city}, ${state}`,
    state,
    country,
    region,
    description,
    capabilities,
    ...(website ? { website } : {}),
  };
}

export const smiDirectoryCompanies: DirectoryCompany[] = [
  // ── AZ (Southwest) ──
  shop(
    "idc-spring-mesa",
    "IDC Spring (Mesa)",
    "Mesa",
    "AZ",
    "USA",
    "Southwest",
    "Custom springs. Mesa, AZ.",
    ["Springs", "Torsion springs"],
    "https://www.idcspring.com/#mesa-az",
  ),
  shop(
    "phoenix-spring",
    "Phoenix Spring Company",
    "Tempe",
    "AZ",
    "USA",
    "Southwest",
    "Custom springs and wire forms. Tempe, AZ.",
    ["Springs", "Wire forms"],
    "https://www.phoenix-spring.com/",
  ),

  // ── CA (West) ──
  shop(
    "aard-spring-and-stamping",
    "AARD Spring & Stamping",
    "Temecula",
    "CA",
    "USA",
    "West",
    "Custom springs. Temecula, CA.",
    ["Springs", "Torsion springs"],
    "https://www.aard.com/",
  ),
  shop(
    "bandb-hemphill-springs-clio",
    "B&B/Hemphill Springs (Clio)",
    "Cerritos",
    "CA",
    "USA",
    "West",
    "Custom springs and wire forms. Cerritos, CA.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.cliosprings.com",
  ),
  shop(
    "diversified-spring-tech",
    "Diversified Spring Tech. Inc.",
    "Santa Fe Springs",
    "CA",
    "USA",
    "West",
    "Custom springs, wire forms, stampings, and constant-force springs. Santa Fe Springs, CA.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.diversifiedspring.com/",
  ),
  shop(
    "foremost-spring-co",
    "Foremost Spring Co., Inc.",
    "Santa Fe Springs",
    "CA",
    "USA",
    "West",
    "Custom springs, wire forms, stampings, and constant-force springs. Santa Fe Springs, CA.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.foremostspring.com/",
  ),
  shop(
    "j-howard-service-group",
    "J Howard Service Group Inc",
    "Los Alamitos",
    "CA",
    "USA",
    "West",
    "Custom springs, wire forms, and stampings. Los Alamitos, CA.",
    ["Wire forms", "Spring washers", "Stampings", "Torsion springs"],
    "https://jhservicegroup.com/",
  ),
  shop(
    "quick-spring",
    "Quick Spring",
    "Santa Fe Springs",
    "CA",
    "USA",
    "West",
    "Custom springs and wire forms. Santa Fe Springs, CA.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.quickspring.com/",
  ),
  shop(
    "scandic-springs",
    "Scandic Springs, Inc.",
    "San Leandro",
    "CA",
    "USA",
    "West",
    "Custom springs, wire forms, stampings, and constant-force springs. San Leandro, CA.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.scandic.com/",
  ),

  // ── CT (Northeast) ──
  shop(
    "acme-monaco",
    "Acme Monaco Corporation",
    "Plainville",
    "CT",
    "USA",
    "Northeast",
    "Custom springs, wire forms, and stampings. Plainville, CT.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.acmemonaco.com/",
  ),
  shop(
    "arrow-manufacturing",
    "Arrow Manufacturing Co",
    "Bristol",
    "CT",
    "USA",
    "Northeast",
    "Custom springs, wire forms, and stampings. Bristol, CT.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.arrowmfg.com/",
  ),
  shop(
    "century-spring-bristol",
    "Century Spring (Bristol)",
    "Bristol",
    "CT",
    "USA",
    "Northeast",
    "Custom springs, wire forms, and stampings. Bristol, CT.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.mwcomponents.com/locations/century-spring",
  ),
  shop(
    "fourslide-spring-and-stamping",
    "Fourslide Spring and Stamping, Inc.",
    "Bristol",
    "CT",
    "USA",
    "Northeast",
    "Wire forms and stampings. Bristol, CT.",
    ["Wire forms", "Stampings"],
    "https://www.fourslide.com/",
  ),

  // ── ID (West) ──
  shop(
    "titan-spring-company",
    "Titan Spring Company Inc.",
    "Hayden",
    "ID",
    "USA",
    "West",
    "Custom springs, wire forms, and stampings. Hayden, ID.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.titanspring.com/",
  ),

  // ── IL (Midwest) ──
  shop(
    "ark-technologies",
    "Ark Technologies Inc.",
    "St. Charles",
    "IL",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. St. Charles, IL.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.arktechno.com/",
  ),
  shop(
    "capitol-coil",
    "Capitol Coil",
    "Franklin Park",
    "IL",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Franklin Park, IL.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.capitolcoil.com/",
  ),
  shop(
    "taylor-spring",
    "Taylor Spring",
    "Monee",
    "IL",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Monee, IL.",
    ["Springs", "Wire forms", "Torsion springs"],
    "https://www.taylorspring.com/",
  ),

  // ── IN (Midwest) ──
  shop(
    "ironmonger-spring-division",
    "Ironmonger Spring Division",
    "Walton",
    "IN",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Walton, IN.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.ironmongerspringdiv.com/",
  ),
  shop(
    "matthew-warren-spring-logansport",
    "Matthew Warren Spring (Logansport)",
    "Logansport",
    "IN",
    "USA",
    "Midwest",
    "Custom springs, wire forms, stampings, and hot-wound springs. Logansport, IN.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.mwcomponents.com/locations/matthew-warren-spring",
  ),
  shop(
    "winamac-coil-spring",
    "Winamac Coil Spring, Inc.",
    "Kewanna",
    "IN",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Kewanna, IN.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.winamaccoilspring.com/",
  ),

  // ── KY (Southeast) ──
  shop(
    "mid-continent-spring",
    "Mid-Continent Spring",
    "Hopkinsville",
    "KY",
    "USA",
    "Southeast",
    "Custom springs and wire forms. Hopkinsville, KY.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.mcspring.com/",
  ),

  // ── MA (Northeast) ──
  shop(
    "jon-spring-co",
    "Jon Spring Co., Inc.",
    "Springfield",
    "MA",
    "USA",
    "Northeast",
    "Custom springs and wire forms. Springfield, MA.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.jonspring.com/",
  ),
  shop(
    "spring-manufacturing",
    "Spring Manufacturing Corp.",
    "Tewksbury",
    "MA",
    "USA",
    "Northeast",
    "Custom springs, wire forms, and stampings. Tewksbury, MA.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.springmancorp.com/",
  ),

  // ── MI (Midwest) ──
  shop(
    "apex-spring-and-stamping",
    "Apex Spring & Stamping Corp.",
    "Grand Rapids",
    "MI",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Grand Rapids, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.apexspring.com/",
  ),
  shop(
    "associated-metal-forming-technologies-brighton",
    "Associated Metal Forming Technologies (Brighton)",
    "Brighton",
    "MI",
    "USA",
    "Midwest",
    "Custom springs, wire forms, stampings, and constant-force springs. Brighton, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.amft.com/",
  ),
  shop(
    "hytech-spring-and-machine",
    "HyTech Spring and Machine",
    "Plainwell",
    "MI",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Plainwell, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.hytechspring.com/",
  ),
  shop(
    "m-and-s-spring",
    "M & S Spring",
    "Fraser",
    "MI",
    "USA",
    "Midwest",
    "Custom springs, wire forms, stampings, hot-wound springs, and constant-force springs. Fraser, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.msspring.com/",
  ),
  shop(
    "michigan-steel-spring",
    "Michigan Steel Spring Co.",
    "Detroit",
    "MI",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Detroit, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.michigansteelspring.com/",
  ),
  shop(
    "novi-spring",
    "Novi Spring Inc.",
    "Brighton",
    "MI",
    "USA",
    "Midwest",
    "Custom springs. Brighton, MI.",
    ["Springs"],
    "https://www.novispring.com/",
  ),
  shop(
    "p-j-wallbank-springs",
    "P.J. Wallbank Springs, Inc.",
    "Port Huron",
    "MI",
    "USA",
    "Midwest",
    "Custom springs. Port Huron, MI.",
    ["Springs"],
    "https://www.pjws.com/",
  ),
  shop(
    "spring-design-and-manufacturing",
    "Spring Design & Manufacturing, Inc.",
    "Shelby Township",
    "MI",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Shelby Township, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spiral torsion and power"],
    "https://www.springdesignmfg.com/",
  ),
  shop(
    "spring-dynamics",
    "Spring Dynamics, Inc.",
    "Almont",
    "MI",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Almont, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spiral torsion and power"],
    "https://www.springdynamics.com/",
  ),
  shop(
    "sss-spring-and-wire",
    "SSS Spring & Wire LLC",
    "Grand Rapids",
    "MI",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Grand Rapids, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spiral torsion and power"],
    "https://www.sss-sw.com/",
  ),
  shop(
    "wolverine-coil-spring",
    "Wolverine Coil Spring Co.",
    "Grand Rapids",
    "MI",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Grand Rapids, MI.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.wolverinecoilspring.com/",
  ),

  // ── MN (Midwest) ──
  shop(
    "idc-spring-coon-rapids",
    "IDC Spring (Coon Rapids)",
    "Coon Rapids",
    "MN",
    "USA",
    "Midwest",
    "Custom springs. Coon Rapids, MN.",
    ["Springs", "Torsion springs"],
    "https://www.idcspring.com/",
  ),
  shop(
    "springs-inc",
    "Springs, Inc.",
    "Forest Lake",
    "MN",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Forest Lake, MN.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.springsinc.com/",
  ),

  // ── MO (Midwest) ──
  shop(
    "industrial-spring",
    "Industrial Spring",
    "North Kansas City",
    "MO",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. North Kansas City, MO.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.isckc.com/",
  ),
  shop(
    "industrial-spring-of-st-louis",
    "Industrial Spring of St. Louis, Inc.",
    "Pacific",
    "MO",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Pacific, MO.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.indspring.com/",
  ),

  // ── NC (Southeast) ──
  shop(
    "southern-atlantic-spring",
    "Southern Atlantic Spring",
    "Granite Quarry",
    "NC",
    "USA",
    "Southeast",
    "Springs and wire forms. Granite Quarry, NC.",
    ["Springs", "Wire forms"],
    "https://www.southernatlanticspring.com/",
  ),

  // ── NY (Northeast) ──
  shop(
    "fennell-spring",
    "Fennell Spring Company",
    "Horseheads",
    "NY",
    "USA",
    "Northeast",
    "Custom springs and wire forms. Horseheads, NY.",
    ["Springs", "Torsion springs", "Wire forms", "Spiral torsion and power"],
    "https://www.fennellspring.com",
  ),
  shop(
    "marni-spring",
    "Marni Spring Corporation",
    "Rochester",
    "NY",
    "USA",
    "Northeast",
    "Custom springs and wire forms. Rochester, NY.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.marnispring.com/",
  ),
  shop(
    "midstate-spring",
    "Midstate Spring, Inc.",
    "Syracuse",
    "NY",
    "USA",
    "Northeast",
    "Custom springs, wire forms, and stampings. Syracuse, NY.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.midstatespring.com/",
  ),

  // ── OH (Midwest) ──
  shop(
    "amw-springs",
    "AMW Springs",
    "Rock Creek",
    "OH",
    "USA",
    "Midwest",
    "Custom springs, wire forms, stampings, and constant-force springs. Rock Creek, OH.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.amwsprings.com/",
  ),
  shop(
    "bloomingburg-spring-and-wire-form-co",
    "Bloomingburg Spring & Wire Form Co. Inc.",
    "Bloomingburg",
    "OH",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Bloomingburg, OH.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.bloomingburgspring.com/",
  ),
  shop(
    "capital-spring-columbus",
    "Capital Spring (Columbus)",
    "Columbus",
    "OH",
    "USA",
    "Midwest",
    "Custom springs, wire forms, stampings, and constant-force springs. Columbus, OH.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.mwcomponents.com/locations/capital-spring",
  ),
  shop(
    "euclid-spring",
    "Euclid Spring",
    "Wickliffe",
    "OH",
    "USA",
    "Midwest",
    "Custom springs. Wickliffe, OH.",
    ["Springs"],
    "https://www.euclidspring.com/",
  ),
  shop(
    "kern-liebers-usa",
    "Kern-Liebers USA",
    "Holland",
    "OH",
    "USA",
    "Midwest",
    "Custom springs, wire forms, stampings, and constant-force springs. Holland, OH.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.kern-liebers.com/",
  ),
  shop(
    "marik-spring",
    "Marik Spring",
    "Tallmadge",
    "OH",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Tallmadge, OH.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.marikspring.com/",
  ),
  shop(
    "spring-team",
    "Spring Team, Inc.",
    "Austinburg",
    "OH",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Austinburg, OH.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.springteam.com/",
  ),
  shop(
    "stalder-spring-works",
    "Stalder Spring Works, Inc.",
    "Springfield",
    "OH",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Springfield, OH.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.stalderspring.com/",
  ),
  shop(
    "twist-inc",
    "Twist, Inc.",
    "Jamestown",
    "OH",
    "USA",
    "Midwest",
    "Custom springs, wire forms, and stampings. Jamestown, OH.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.twistinc.com/",
  ),
  shop(
    "western-wire-products",
    "Western Wire Products",
    "Fenton",
    "OH",
    "USA",
    "Midwest",
    "Springs and wire forms. Fenton, OH.",
    ["Springs", "Wire forms"],
    "https://westernwireprod.com/",
  ),

  // ── OK (Southwest) ──
  shop(
    "cannon-spring",
    "Cannon Spring Company",
    "Oklahoma City",
    "OK",
    "USA",
    "Southwest",
    "Custom springs and wire forms. Oklahoma City, OK.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.cannonspring.com",
  ),

  // ── OR (West) ──
  shop(
    "anderson-quality-spring",
    "Anderson Quality Spring",
    "Canby",
    "OR",
    "USA",
    "West",
    "Custom springs, wire forms, and stampings. Canby, OR.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.andersonqualityspring.com/",
  ),

  // ── PA (Northeast) ──
  shop(
    "mercer-spring-and-wire",
    "Mercer Spring & Wire",
    "Townville",
    "PA",
    "USA",
    "Northeast",
    "Custom springs and wire forms. Townville, PA.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.mercerspringandwire.com/",
  ),
  shop(
    "navarro-spring-co",
    "Navarro Spring Co., Inc.",
    "Yeadon",
    "PA",
    "USA",
    "Northeast",
    "Custom springs and wire forms. Yeadon, PA.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.navarrospring.com/",
  ),

  // ── SC (Southeast) ──
  shop(
    "greer-springs-mw-components",
    "Greer Springs (MW Components)",
    "Greer",
    "SC",
    "USA",
    "Southeast",
    "Custom springs and hot-wound springs. Greer, SC.",
    ["Springs", "Torsion springs", "Hot wound springs"],
    "https://www.mwcomponents.com/locations/greer-springs",
  ),

  // ── TN (Southeast) ──
  shop(
    "tri-matic-spring",
    "Tri-Matic Spring, Inc.",
    "Savannah",
    "TN",
    "USA",
    "Southeast",
    "Custom springs, wire forms, and stampings. Savannah, TN.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.trimaticspring.com/",
  ),

  // ── TX (Southwest) ──
  shop(
    "engineered-spring-products-houston",
    "Engineered Spring Products (Houston)",
    "Houston",
    "TX",
    "USA",
    "Southwest",
    "Custom springs, wire forms, and stampings. Houston, TX.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.mw-ind.com/divisions/esp.html",
  ),
  shop(
    "gulf-coast-spring",
    "Gulf Coast Spring",
    "Houston",
    "TX",
    "USA",
    "Southwest",
    "Custom springs, wire forms, and stampings. Houston, TX.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.gulfcoastspring.com/",
  ),
  shop(
    "integrity-spring-and-fab",
    "Integrity Spring & Fab. LLC",
    "Houston",
    "TX",
    "USA",
    "Southwest",
    "Custom springs and wire forms. Houston, TX.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.integrityspring.com/",
  ),
  // ── WA (West) ──
  shop(
    "renton-coil-spring",
    "Renton Coil Spring Co.",
    "Renton",
    "WA",
    "USA",
    "West",
    "Custom springs, wire forms, and stampings. Renton, WA.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.rentoncoilspring.com/",
  ),

  // ── WI (Midwest) ──
  shop(
    "automated-wire-products",
    "Automated Wire Products Inc.",
    "Germantown",
    "WI",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Germantown, WI.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.automatedwire.com/",
  ),
  shop(
    "medicoil",
    "Medicoil Inc",
    "Lake Geneva",
    "WI",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Lake Geneva, WI.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.medicoil.com/",
  ),
  shop(
    "northern-wire-merrill",
    "Northern Wire (Merrill)",
    "Merrill",
    "WI",
    "USA",
    "Midwest",
    "Springs and wire forms. Merrill, WI.",
    ["Springs", "Wire forms"],
    "https://www.mwcomponents.com/locations/northern-wire",
  ),
  shop(
    "oshkosh-coil-spring",
    "Oshkosh Coil Spring, Inc",
    "Oshkosh",
    "WI",
    "USA",
    "Midwest",
    "Custom springs and wire forms. Oshkosh, WI.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.oshkoshcoilspring.com/",
  ),

  // ── BC (Canada) ──
  shop(
    "dendoff-springs",
    "Dendoff Springs Ltd.",
    "Surrey",
    "BC",
    "Canada",
    "Canada",
    "Custom springs, wire forms, stampings, hot-wound springs, and constant-force springs. Surrey, BC.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.dendoff.com/",
  ),
  shop(
    "mcallister-industries",
    "McAllister Industries Ltd",
    "Surrey",
    "BC",
    "Canada",
    "Canada",
    "Custom springs, wire forms, hot-wound springs, and constant-force springs. Surrey, BC.",
    ["Springs", "Torsion springs", "Wire forms", "Hot wound springs"],
    "https://www.macspring.com/",
  ),

  // ── MB (Canada) ──
  shop(
    "western-spring-and-wire-winnipeg",
    "Western Spring & Wire (Winnipeg)",
    "Winnipeg",
    "MB",
    "Canada",
    "Canada",
    "Custom springs, wire forms, and stampings. Winnipeg, MB.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.wsw.ca/#winnipeg",
  ),

  // ── ON (Canada) ──
  shop(
    "commercial-spring-and-tool-co",
    "Commercial Spring & Tool Co., Ltd.",
    "Mississauga",
    "ON",
    "Canada",
    "Canada",
    "Custom springs, wire forms, and stampings. Mississauga, ON.",
    ["Springs", "Torsion springs", "Wire forms", "Spring washers"],
    "https://www.commercialspring.com/",
  ),
  shop(
    "desantis-industrial-spring-stampings",
    "DeSantis Industrial Spring Stampings",
    "Brantford",
    "ON",
    "Canada",
    "Canada",
    "Custom springs, wire forms, and stampings. Brantford, ON.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.diss.on.ca/",
  ),
  shop(
    "maverick-spring-makers",
    "Maverick Spring Makers Ltd",
    "Brantford",
    "ON",
    "Canada",
    "Canada",
    "Custom springs and wire forms. Brantford, ON.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.maverickspring.com/",
  ),
  shop(
    "ridge-nassau",
    "Ridge Nassau Ltd.",
    "Hawkesbury",
    "ON",
    "Canada",
    "Canada",
    "Springs and wire forms. Hawkesbury, ON.",
    ["Springs", "Wire forms"],
    "https://www.ridgenassau.com/",
  ),
  shop(
    "western-spring-and-wire-st-george",
    "Western Spring & Wire (St. George)",
    "St. George",
    "ON",
    "Canada",
    "Canada",
    "Custom springs, wire forms, and stampings. St. George, ON.",
    ["Springs", "Torsion springs", "Wire forms", "Stampings"],
    "https://www.wsw.ca/",
  ),

  // ── QC (Canada) ──
  shop(
    "liberty-spring",
    "Liberty Spring",
    "Montmagny",
    "QC",
    "Canada",
    "Canada",
    "Custom springs and wire forms. Montmagny, QC.",
    ["Springs", "Torsion springs", "Wire forms"],
    "https://www.libertyspring.com/",
  ),

];
