/** Ranked U.S. wire-forming metros for the cities hub and later heat map. */

export const METRO_HUB_PATH = "/directory/areas";

export type WireFormingMetro = {
  rank: number;
  slug: string;
  city: string;
  metro: string;
  stateSlug: string;
  stateAbbr: string;
  lat: number;
  lng: number;
  /** Cluster strength 1–10. Not a Google ranking. */
  heat: number;
  /** USA Wire Form directory listings in this metro. Nashville can rank on plant scale at 0. */
  directoryShops: number;
  why: string;
  /** City names used later to match directory / state-shop rows. */
  aliases: string[];
  /** USA Wire Form production cell. */
  hq?: boolean;
};

export const WIRE_FORMING_METROS: WireFormingMetro[] = [
  {
    rank: 1,
    slug: "los-angeles",
    city: "Los Angeles",
    metro: "LA / Inland Empire",
    stateSlug: "california",
    stateAbbr: "CA",
    lat: 34.0522,
    lng: -118.2437,
    heat: 10,
    directoryShops: 16,
    why: "Densest fourslide, CNC, and spring job-shop belt in the country. Ontario, Commerce, Corona, Stanton, El Monte, Santa Fe Springs.",
    aliases: [
      "los angeles",
      "ontario",
      "commerce",
      "corona",
      "stanton",
      "el monte",
      "santa fe springs",
      "inland empire",
    ],
  },
  {
    rank: 2,
    slug: "chicago",
    city: "Chicago",
    metro: "Chicago / northwest suburbs",
    stateSlug: "illinois",
    stateAbbr: "IL",
    lat: 41.8781,
    lng: -87.6298,
    heat: 9,
    directoryShops: 8,
    why: "Midwest coil belt: Franklin Park, Bartlett, Roselle, Addison, Wheeling, Carol Stream. Auto, appliance, lawn-and-garden.",
    aliases: [
      "chicago",
      "franklin park",
      "bartlett",
      "roselle",
      "addison",
      "wheeling",
      "carol stream",
    ],
  },
  {
    rank: 3,
    slug: "cleveland",
    city: "Cleveland",
    metro: "Northeast Ohio",
    stateSlug: "ohio",
    stateAbbr: "OH",
    lat: 41.4993,
    lng: -81.6944,
    heat: 9,
    directoryShops: 5,
    why: "Steel mills, wire drawers, short-haul coil. Elyria, Cleveland, Ashland — Toledo next door. USA Wire Form sits here.",
    aliases: ["cleveland", "elyria", "ashland", "toledo", "lorain", "akron"],
    hq: true,
  },
  {
    rank: 4,
    slug: "houston",
    city: "Houston",
    metro: "Houston / Gulf",
    stateSlug: "texas",
    stateAbbr: "TX",
    lat: 29.7604,
    lng: -95.3698,
    heat: 8,
    directoryShops: 10,
    why: "Energy springs, heavy coiling, mesh mills. Katy, Conroe, South Houston, Navasota.",
    aliases: ["houston", "katy", "conroe", "navasota", "south houston"],
  },
  {
    rank: 5,
    slug: "grand-rapids",
    city: "Grand Rapids",
    metro: "West Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    lat: 42.9634,
    lng: -85.6681,
    heat: 8,
    directoryShops: 4,
    why: "Furniture, auto, and CNC tube/wire. Muskegon, Fruitport, Jackson, Rives Junction.",
    aliases: ["grand rapids", "muskegon", "fruitport", "jackson", "rives junction"],
  },
  {
    rank: 6,
    slug: "milwaukee",
    city: "Milwaukee",
    metro: "Eastern Wisconsin",
    stateSlug: "wisconsin",
    stateAbbr: "WI",
    lat: 43.0389,
    lng: -87.9065,
    heat: 7,
    directoryShops: 5,
    why: "Oshkosh, West Bend, Lake Geneva, Germantown, Sturgeon Bay. Formed wire, weld, and fourslide for OEM.",
    aliases: [
      "milwaukee",
      "oshkosh",
      "west bend",
      "lake geneva",
      "germantown",
      "sturgeon bay",
    ],
  },
  {
    rank: 7,
    slug: "detroit",
    city: "Detroit",
    metro: "Southeast Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    lat: 42.3314,
    lng: -83.0458,
    heat: 7,
    directoryShops: 3,
    why: "Auto OEM and Tier-1 wire. Rochester Hills, Three Rivers, Bronson.",
    aliases: ["detroit", "rochester hills", "three rivers", "bronson"],
  },
  {
    rank: 8,
    slug: "hartford",
    city: "Hartford",
    metro: "Central Connecticut",
    stateSlug: "connecticut",
    stateAbbr: "CT",
    lat: 41.7658,
    lng: -72.6734,
    heat: 7,
    directoryShops: 4,
    why: "Historic U.S. spring and fourslide belt. Bristol, Southington, Mystic.",
    aliases: ["hartford", "bristol", "southington", "mystic"],
  },
  {
    rank: 9,
    slug: "pittsburgh",
    city: "Pittsburgh",
    metro: "Western Pennsylvania",
    stateSlug: "pennsylvania",
    stateAbbr: "PA",
    lat: 40.4406,
    lng: -79.9959,
    heat: 6,
    directoryShops: 3,
    why: "McKees Rocks, Glenshaw, Blairsville. Springs, CNC forms, filter cages. Ohio Valley freight.",
    aliases: ["pittsburgh", "mckees rocks", "glenshaw", "blairsville"],
  },
  {
    rank: 10,
    slug: "dallas",
    city: "Dallas",
    metro: "Dallas–Fort Worth",
    stateSlug: "texas",
    stateAbbr: "TX",
    lat: 32.7767,
    lng: -96.797,
    heat: 6,
    directoryShops: 1,
    why: "North Texas OEM lane. Thinner job-shop density than Houston; still the DFW plant corridor.",
    aliases: ["dallas", "fort worth", "arlington", "plano"],
  },
  {
    rank: 11,
    slug: "minneapolis",
    city: "Minneapolis",
    metro: "Twin Cities",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    lat: 44.9778,
    lng: -93.265,
    heat: 6,
    directoryShops: 1,
    why: "Upper Midwest OEM. Medical and industrial. Serves the Dakotas.",
    aliases: ["minneapolis", "st paul", "saint paul", "hugo"],
  },
  {
    rank: 12,
    slug: "st-louis",
    city: "St. Louis",
    metro: "St. Louis metro",
    stateSlug: "missouri",
    stateAbbr: "MO",
    lat: 38.627,
    lng: -90.1994,
    heat: 6,
    directoryShops: 1,
    why: "Gateway OEM and construction mesh. Insteel up the river at St. Joseph.",
    aliases: ["st louis", "saint louis", "st. louis", "st joseph"],
  },
  {
    rank: 13,
    slug: "philadelphia",
    city: "Philadelphia",
    metro: "Eastern PA / South Jersey",
    stateSlug: "pennsylvania",
    stateAbbr: "PA",
    lat: 39.9526,
    lng: -75.1652,
    heat: 6,
    directoryShops: 3,
    why: "Malvern, York, New Holland. Mid-Atlantic LTL.",
    aliases: ["philadelphia", "malvern", "york", "new holland"],
  },
  {
    rank: 14,
    slug: "nashville",
    city: "Nashville",
    metro: "Middle Tennessee",
    stateSlug: "tennessee",
    stateAbbr: "TN",
    lat: 36.1627,
    lng: -86.7816,
    heat: 7,
    directoryShops: 0,
    why: "Nashville Wire is one of the largest U.S. formed-wire plants. Thin in our directory — fat in the real trade.",
    aliases: ["nashville", "ooltewah", "gallatin", "murfreesboro"],
  },
  {
    rank: 15,
    slug: "charlotte",
    city: "Charlotte",
    metro: "Carolinas",
    stateSlug: "north-carolina",
    stateAbbr: "NC",
    lat: 35.2271,
    lng: -80.8431,
    heat: 6,
    directoryShops: 2,
    why: "Auto and construction mesh. Insteel, MW Components, Newcomb Gastonia — not a 1/2 in frame belt.",
    aliases: ["charlotte", "mount airy", "gastonia"],
  },
  {
    rank: 16,
    slug: "baltimore",
    city: "Baltimore",
    metro: "Baltimore / Delmarva",
    stateSlug: "maryland",
    stateAbbr: "MD",
    lat: 39.2904,
    lng: -76.6122,
    heat: 5,
    directoryShops: 1,
    why: "Stainless baskets and robotic forms. Serves DE, D.C., VA docks.",
    aliases: ["baltimore", "sparrows point"],
  },
  {
    rank: 17,
    slug: "indianapolis",
    city: "Indianapolis",
    metro: "Central / northern Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    lat: 39.7684,
    lng: -86.1581,
    heat: 5,
    directoryShops: 2,
    why: "Auto and retail fixtures. Angola Wire and Franklin.",
    aliases: ["indianapolis", "angola", "franklin"],
  },
  {
    rank: 18,
    slug: "portland",
    city: "Portland",
    metro: "Portland, OR",
    stateSlug: "oregon",
    stateAbbr: "OR",
    lat: 45.5152,
    lng: -122.6784,
    heat: 5,
    directoryShops: 1,
    why: "The real Pacific Northwest former. Serves Seattle from Oregon.",
    aliases: ["portland", "hillsboro", "vancouver"],
  },
  {
    rank: 19,
    slug: "san-jose",
    city: "San Jose",
    metro: "San Francisco Bay Area",
    stateSlug: "california",
    stateAbbr: "CA",
    lat: 37.3382,
    lng: -121.8863,
    heat: 6,
    directoryShops: 5,
    why: "Precision, aerospace, medical. Santa Clara, Hayward, Gilroy, Rohnert Park. Light wire — not 4–14 mm frames.",
    aliases: [
      "san jose",
      "santa clara",
      "hayward",
      "gilroy",
      "rohnert park",
      "san francisco",
      "bay area",
    ],
  },
  {
    rank: 20,
    slug: "worcester",
    city: "Worcester",
    metro: "New England (MA / RI)",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    lat: 42.2626,
    lng: -71.8023,
    heat: 5,
    directoryShops: 2,
    why: "Serves Boston, Providence, Vermont freight. Worcester and East Longmeadow.",
    aliases: ["worcester", "east longmeadow", "springfield"],
  },
];

export function getMetro(slug: string) {
  return WIRE_FORMING_METROS.find((metro) => metro.slug === slug);
}

export function clevelandMetro() {
  return WIRE_FORMING_METROS.find((metro) => metro.hq) ?? WIRE_FORMING_METROS[2];
}

export function metroPath(metro: WireFormingMetro) {
  return `${METRO_HUB_PATH}/${metro.slug}`;
}
