/** Shared terms. Google largely ignores meta keywords; they still help other crawlers and consistency. */
export const CORE_KEYWORDS = [
  "USA Wire Form",
  "wire form suppliers",
  "wire form manufacturers",
  "CNC wire forming",
  "3D CNC wire forming",
  "wire forming",
  "4-14 mm wire",
  "3/8 inch wire",
  "7/16 inch wire",
  "1/2 inch wire",
  "wire forming resource",
  "wire forming directory",
  "CNC wire forming machines",
  "coil steel",
  "wire baskets",
  "wire frames",
  "wire guards",
  "USA made wire baskets",
  "USA made D-rings",
  "USA made cable trays",
  "USA made wire racks",
  "USA made security fencing",
  "USA made heat treat baskets",
  "USA made ground staples",
  "USA made ground samples",
  "USA made wire stakes",
  "USA made L hitch pins",
  "USA made hitch pins",
  "L hitch pins",
  "heavy-duty L hitch pins",
  "custom CNC wire forming services",
  "lowest price wire forming",
  "powder coating hooks",
  "V-hooks",
  "C-hooks",
  "CV-hooks",
  "S-hooks",
  "90 degree hooks",
  "custom powder coating hooks",
  "powder coating V-hooks",
  "heavy-duty V-hooks",
  "USA made heavy-duty powder coat V-hooks",
  "steel V-hooks",
  "stainless steel V-hooks",
];
