import Link from "next/link";
import { BlogBody } from "@/components/BlogBody";
import { BreadcrumbJsonLd } from "@/components/JsonLd";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { Page, PageHero, TextLink } from "@/components/ui";
import {
  allBriefings,
  ohioDateLabel,
  postPath,
  todaysBriefing,
} from "@/lib/blog";
import { pageMeta } from "@/lib/seo";

export const metadata = pageMeta({
  title: "Daily Wire Forming Briefing",
  description:
    "A daily wire forming briefing that rotates automatically: design, weld, mesh, 330, and structures in 4–14 mm. Ohio calendar.",
  path: "/blog/daily",
  keywords: [
    "daily wire forming",
    "wire forming blog",
    "wire form structures",
  ],
});

export const revalidate = 3600;

export default function DailyBlogPage() {
  const today = todaysBriefing();
  const pool = allBriefings();
  const dateLabel = ohioDateLabel();

  return (
    <Page>
      <BreadcrumbJsonLd
        items={[
          { name: "Blog", url: "/blog" },
          { name: "Daily briefing", url: "/blog/daily" },
        ]}
      />
      <Breadcrumbs
        items={[
          { label: "Blog", href: "/blog" },
          { label: "Daily" },
        ]}
      />
      <PageHero
        kicker="Daily · automatic"
        title={today.title}
        lede={`${dateLabel}, America/New_York. This page picks briefing ${pool.indexOf(today) + 1} of ${pool.length} from a curated pool. Tomorrow a different piece sits here. Each briefing also has a stable URL.`}
      >
        <TextLink href="/blog">All articles</TextLink>
        <span className="text-muted"> · </span>
        <TextLink href={postPath(today)}>Permanent link</TextLink>
        <span className="text-muted"> · </span>
        <TextLink href="/blog/feed.xml">RSS</TextLink>
      </PageHero>

      <BlogBody blocks={today.blocks} />

      {today.related.length > 0 ? (
        <ul className="article mt-8">
          {today.related.map((item) => (
            <li key={item.href}>
              <Link href={item.href}>{item.label}</Link>
            </li>
          ))}
        </ul>
      ) : null}

      <p className="mt-12 max-w-2xl text-sm leading-6 text-muted">
        Nothing is generated by a model overnight. The rotation is the
        automation: Ohio date modulo {pool.length}. Shop articles live on{" "}
        <Link href="/blog" className="text-copper hover:underline">
          /blog
        </Link>
        . To add a day, add a briefing in the repo and ship.
      </p>
    </Page>
  );
}
