import { TOOLING } from "@/lib/price";
import { COMMON_SIZES, WIRE } from "@/lib/range";
import type {
  CollisionScenarioRow,
  MachineCapabilityRow,
  MachineHeadRow,
  MachineRow,
  MachineRuleRow,
  MachineToolingRow,
  MaterialFamilyRow,
  Provenance,
  TwinTables,
} from "./types";

const MACHINE_ID = "robomac-214tf";

const asOf = "2026-09-30";

function catalog(source: string, notes?: string): Provenance {
  return { kind: "published_catalog", source, asOf, notes };
}

function shop(source: string, notes?: string): Provenance {
  return { kind: "shop_practice", source, asOf, notes };
}

function estimated(source: string, notes?: string): Provenance {
  return { kind: "estimated", source, asOf, notes };
}

function unknown(source: string, notes?: string): Provenance {
  return { kind: "unknown", source, asOf, notes };
}

const NUMALLIANCE_TF =
  "Numalliance Robomac TF plate — R214TF G4, 4–14 mm at 600 N/mm² (85 ksi). https://www.numalliance.com/en/machines/robomac-tf-en/";

export const ROBOMAC_214TF: MachineRow = {
  id: MACHINE_ID,
  oem: "Numalliance",
  model: "R214TF",
  series: "Robomac TF",
  plateName: "Robomac 214TF",
  cellKind: "3D CNC",
  location: "Northeast Ohio — USA Wire Form floor",
  feedFrom: "coil",
  headCount: 2,
  tensileRatingNmm2: 600,
  orbitHead: true,
  notes:
    "This floor runs one Robomac 214TF with two heads: a wipe / pin head for regular angle bends (about 20–180°), and a push head for rings. Instant estimate and production quotes are this cell.",
  provenance: catalog(
    NUMALLIANCE_TF,
    "Two heads and location are shop_practice. Catalog family allows 1–3 heads.",
  ),
};

/** Shop: push-head min ring radius on 1/2 in. Encoded as centerline R. */
export const PUSH_RING_MIN_RADIUS_IN = 6;
export const PUSH_RING_MIN_RADIUS_MM = PUSH_RING_MIN_RADIUS_IN * 25.4;
export const PUSH_RING_WIRE_IN = 0.5;
export const PUSH_RING_WIRE_MM = 12.7;
export const WIPE_ANGLE_MIN_DEG = 20;
export const WIPE_ANGLE_MAX_DEG = 180;

export const HEADS: MachineHeadRow[] = [
  {
    id: "head-wipe",
    machineId: MACHINE_ID,
    kind: "wipe",
    label: "Wipe / pin head — regular angle bends",
    angleMinDeg: WIPE_ANGLE_MIN_DEG,
    angleMaxDeg: WIPE_ANGLE_MAX_DEG,
    notes:
      "Everyday corners: about 20–180°. Eyes / S-hook wraps (~240°) still run on this head. Not the ring head.",
    provenance: shop(
      "Shop floor — Robomac 214TF wipe head",
      "Typical angle-bend range, not a measured axis stop. Wraps above 180° stay on this head until 270° Phase 1 ceiling.",
    ),
  },
  {
    id: "head-push",
    machineId: MACHINE_ID,
    kind: "push",
    label: "Push head — rings / large radius",
    minRingRadiusIn: PUSH_RING_MIN_RADIUS_IN,
    minRingRadiusMm: PUSH_RING_MIN_RADIUS_MM,
    minRingRadiusWireIn: PUSH_RING_WIRE_IN,
    minRingRadiusWireMm: PUSH_RING_WIRE_MM,
    notes:
      "Push bending for rings. Minimum ring radius 6 in on 1/2 in wire. Other diameters are not stated — do not scale.",
    provenance: shop(
      "Shop floor — Robomac 214TF push head",
      "6 in is centerline radius on 1/2 in (12.7 mm). Confirm if the floor meant inside diameter.",
    ),
  },
];

export const CAPABILITIES: MachineCapabilityRow[] = [
  {
    id: "cap-wire-band",
    machineId: MACHINE_ID,
    key: "wire_diameter_mm",
    label: "Wire diameter at 600 N/mm²",
    unit: "mm",
    min: WIRE.minMm,
    max: WIRE.maxMm,
    tensileNmm2: 600,
    phase: 1,
    confidence: "high",
    provenance: catalog(
      NUMALLIANCE_TF,
      "Shop production band matches the plate. Higher tensile is not derated here — no shop table yet.",
    ),
  },
  {
    id: "cap-wire-band-in",
    machineId: MACHINE_ID,
    key: "wire_diameter_in",
    label: "Wire diameter at 600 N/mm²",
    unit: "in",
    min: WIRE.minIn,
    max: WIRE.maxIn,
    tensileNmm2: 600,
    phase: 1,
    confidence: "high",
    provenance: catalog(NUMALLIANCE_TF),
  },
  {
    id: "cap-from-coil",
    machineId: MACHINE_ID,
    key: "feed_from",
    label: "Feed",
    unit: "enum",
    value: "coil",
    phase: 1,
    confidence: "high",
    provenance: catalog(NUMALLIANCE_TF),
  },
  {
    id: "cap-orbit-head",
    machineId: MACHINE_ID,
    key: "orbit_head",
    label: "Bending head orbits the wire",
    unit: "bool",
    value: true,
    phase: 1,
    confidence: "high",
    provenance: catalog(
      NUMALLIANCE_TF,
      "Published: bending head moves freely around the wire.",
    ),
  },
  {
    id: "cap-3d",
    machineId: MACHINE_ID,
    key: "spatial_bends",
    label: "3D forming",
    unit: "bool",
    value: true,
    phase: 1,
    confidence: "high",
    provenance: catalog(NUMALLIANCE_TF),
  },
  {
    id: "cap-max-bend-angle",
    machineId: MACHINE_ID,
    key: "max_bend_angle_deg",
    label: "Maximum wrap on a single pin",
    unit: "deg",
    max: 270,
    phase: 1,
    confidence: "medium",
    provenance: shop(
      "src/lib/hook-builder.ts S-hook / C-hook eyes (~240°); design guide loops",
      "Shop forms 240° eyes. 270° is the Phase 1 ceiling. Above that is REVIEW, not a measured machine stop.",
    ),
  },
  {
    id: "cap-min-straight-xd",
    machineId: MACHINE_ID,
    key: "min_straight_xd",
    label: "Minimum straight between bends",
    unit: "× diameter",
    min: 2,
    max: 3,
    phase: 1,
    confidence: "medium",
    provenance: shop(
      "/guide/design-for-wire-forming and /processes/3d-cnc-wire-forming",
      "Fail below 2×D. Review 2–3×D. Pass at ≥ 3×D. Not a tape-measured head dimension.",
    ),
  },
  {
    id: "cap-cutoff-leg-xd",
    machineId: MACHINE_ID,
    key: "min_end_leg_xd",
    label: "Minimum first/last leg for cutoff",
    unit: "× diameter",
    min: 2,
    phase: 1,
    confidence: "low",
    provenance: estimated(
      "Cutoff needs room to shear. Conservative 2×D until the cutoff tool is measured.",
    ),
  },
  {
    id: "cap-developed-review-mm",
    machineId: MACHINE_ID,
    key: "developed_review_mm",
    label: "Developed length that needs a desk look",
    unit: "mm",
    max: 2000,
    phase: 1,
    confidence: "low",
    provenance: estimated(
      "Coil feed can run longer parts. 2 m is a workspace-review tripwire, not a plate limit.",
    ),
  },
  {
    id: "cap-developed-fail-mm",
    machineId: MACHINE_ID,
    key: "developed_fail_mm",
    label: "Developed length refused without a cell walk",
    unit: "mm",
    max: 6000,
    phase: 1,
    confidence: "low",
    provenance: estimated(
      "No published max developed length. 6 m is a hard stop until decoiler / fence is measured.",
    ),
  },
  {
    id: "cap-work-envelope",
    machineId: MACHINE_ID,
    key: "work_envelope_mm",
    label: "Formed-part work envelope",
    unit: "mm",
    phase: 2,
    confidence: "none",
    provenance: unknown(
      "Bend-head and fence geometry are not on the plate. Measure before collision DFM.",
    ),
  },
  {
    id: "cap-bend-head-clearance",
    machineId: MACHINE_ID,
    key: "bend_head_clearance_mm",
    label: "Bend-head clearance envelope",
    unit: "mm",
    phase: 2,
    confidence: "none",
    provenance: unknown(
      "Required vs available clearance (brief example 28 vs 19 mm) needs the real head and tool solids.",
    ),
  },
  {
    id: "cap-feed-limits",
    machineId: MACHINE_ID,
    key: "feed_limits",
    label: "Feed increment and stroke",
    unit: "mm",
    phase: 2,
    confidence: "none",
    provenance: unknown("Measure on the 214TF program / axis limits."),
  },
  {
    id: "cap-rotation-limits",
    machineId: MACHINE_ID,
    key: "rotation_limits_deg",
    label: "Rotation / plane-change limits",
    unit: "deg",
    phase: 2,
    confidence: "low",
    provenance: catalog(
      NUMALLIANCE_TF,
      "Orbit head is free around the wire. Formed-leg collisions, not a rotation stop, are the real limit.",
    ),
  },
  {
    id: "cap-new-tool-lead",
    machineId: MACHINE_ID,
    key: "new_tooling_lead_days",
    label: "New pin / bushing lead",
    unit: "business days",
    min: 7,
    max: 10,
    phase: 1,
    confidence: "high",
    provenance: shop(`src/lib/price.ts TOOLING.newLead = ${TOOLING.newLead}`),
  },
  {
    id: "cap-new-tool-cost",
    machineId: MACHINE_ID,
    key: "new_tooling_cost_usd",
    label: "New tooling for a wire size",
    unit: "USD",
    value: TOOLING.newCostUsd,
    phase: 1,
    confidence: "high",
    provenance: shop(`src/lib/price.ts TOOLING.newCostUsd = ${TOOLING.newCostUsd}`),
  },
  {
    id: "cap-head-count",
    machineId: MACHINE_ID,
    key: "head_count",
    label: "Bending heads on this cell",
    unit: "count",
    value: 2,
    phase: 1,
    confidence: "high",
    provenance: shop("Shop floor — Robomac 214TF has a wipe head and a push head."),
  },
  {
    id: "cap-wipe-angle",
    machineId: MACHINE_ID,
    key: "wipe_angle_deg",
    label: "Wipe head typical angle-bend range",
    unit: "deg",
    min: WIPE_ANGLE_MIN_DEG,
    max: WIPE_ANGLE_MAX_DEG,
    phase: 1,
    confidence: "high",
    provenance: shop(
      "Shop floor — wipe head",
      "Regular corners. Eyes still wrap past 180° on this head.",
    ),
  },
  {
    id: "cap-push-ring-min-1-2",
    machineId: MACHINE_ID,
    key: "push_min_ring_radius_mm",
    label: "Push-head min ring radius on 1/2 in",
    unit: "mm",
    min: PUSH_RING_MIN_RADIUS_MM,
    phase: 1,
    confidence: "high",
    provenance: shop(
      "Shop floor — push head, 1/2 in wire",
      "6 in centerline. Not measured for 3/8 or 7/16.",
    ),
  },
];

const stock3_8 = COMMON_SIZES[0];
const stock7_16 = COMMON_SIZES[1];
const stock1_2 = COMMON_SIZES[2];

export const TOOLING_ROWS: MachineToolingRow[] = [
  {
    id: "tool-stock-3-8",
    machineId: MACHINE_ID,
    label: '3/8 in stock pin',
    wireDiameterMm: stock3_8.mmValue,
    wireDiameterIn: 0.375,
    stock: true,
    use: "general",
    pinDiameterMm: 10.16,
    pinDiameterIn: 0.4,
    insideRadiusMm: 5.08,
    insideRadiusIn: 0.2,
    notes:
      "Stock production size. 0.400 in pin / 0.200 in IR is the staple-crown wrap on this wire — general forms still want ≥ 1×D unless the print is a staple.",
    provenance: shop(
      "src/lib/ground-staple-builder.ts STAPLE_PINS 3/8 in; COMMON_SIZES; TOOLING.stock",
    ),
  },
  {
    id: "tool-stock-7-16",
    machineId: MACHINE_ID,
    label: "7/16 in stock pin",
    wireDiameterMm: stock7_16.mmValue,
    wireDiameterIn: 0.4375,
    stock: true,
    use: "general",
    pinDiameterMm: 12.7,
    pinDiameterIn: 0.5,
    insideRadiusMm: 6.35,
    insideRadiusIn: 0.25,
    notes: "Stock. 1/2 in bending pin. Inside R 0.250 in on staple crowns.",
    provenance: shop("src/lib/ground-staple-builder.ts STAPLE_PINS 7/16 in"),
  },
  {
    id: "tool-stock-1-2",
    machineId: MACHINE_ID,
    label: "1/2 in stock",
    wireDiameterMm: stock1_2.mmValue,
    wireDiameterIn: 0.5,
    stock: true,
    use: "general",
    insideRadiusMm: 15.85,
    insideRadiusIn: 0.624,
    notes:
      "Stock. Inside R 0.624 in is documented for staple crowns. Pin diameter is not on the card — measure it.",
    provenance: shop("src/lib/ground-staple-builder.ts STAPLE_PINS 1/2 in"),
  },
  {
    id: "tool-staple-3-8",
    machineId: MACHINE_ID,
    label: "3/8 in staple crown wrap",
    wireDiameterMm: stock3_8.mmValue,
    wireDiameterIn: 0.375,
    stock: true,
    use: "staple_crown",
    pinDiameterMm: 10.16,
    pinDiameterIn: 0.4,
    insideRadiusMm: 5.08,
    insideRadiusIn: 0.2,
    notes:
      "Do not treat 0.53×D as a general min-radius override. Staple crowns only.",
    provenance: shop("src/lib/ground-staple-builder.ts STAPLE_PINS 3/8 in"),
  },
  {
    id: "tool-new-size",
    machineId: MACHINE_ID,
    label: `Other size in ${WIRE.short}`,
    wireDiameterMm: 0,
    wireDiameterIn: 0,
    stock: false,
    use: "general",
    newLeadDays: { min: 7, max: 10 },
    newCostUsd: TOOLING.newCostUsd,
    notes: `${TOOLING.newLead}, ${TOOLING.newCostLabel}. Diameter must still sit in ${WIRE.short}.`,
    provenance: shop("src/lib/price.ts TOOLING"),
  },
];

export const MATERIALS: MaterialFamilyRow[] = [
  {
    id: "1018",
    label: "Low-carbon steel (1010 / 1018 / 1008)",
    alloys: ["1010", "1018", "1006", "1008", "galvanized"],
    coilOk: true,
    minInsideRadiusXd: 1,
    springbackDegAt1xD: { min: 2, max: 4 },
    notes:
      "Default carbon. 1×D inside radius on mild coil. Galvanized marks in the straightener and burns back at welds.",
    provenance: shop(
      "/guide/design-for-wire-forming; src/lib/materials.ts lowCarbon",
    ),
  },
  {
    id: "spring",
    label: "Medium / high-carbon spring",
    alloys: ["1030", "1045", "1050", "1060", "1070", "1095", "A229", "A228", "6150", "5160"],
    coilOk: true,
    minInsideRadiusXd: 1.5,
    springbackDegAt1xD: { min: 6, max: 12 },
    notes:
      "More snap than 1018. A228 music-wire diameters are usually under 4 mm — name and refuse those. Confirm the head at 3/8–1/2 in.",
    provenance: shop("src/lib/materials.ts carbonAndSpring; design guide"),
  },
  {
    id: "304",
    label: "300-series stainless (301 / 302 / 304 / 304L)",
    alloys: ["301", "302", "304", "304L", "305"],
    coilOk: true,
    minInsideRadiusXd: 1.5,
    springbackDegAt1xD: { min: 6, max: 10 },
    notes: "Often 1.5–2×D. Work-hardens. Do not copy a 1018 radius.",
    provenance: shop("/guide/design-for-wire-forming; /materials/300-series-stainless"),
  },
  {
    id: "316",
    label: "316 / 316L stainless",
    alloys: ["316", "316L", "317", "317L"],
    coilOk: true,
    minInsideRadiusXd: 2,
    springbackDegAt1xD: { min: 8, max: 12 },
    notes: "More springback than 304. Marine and chemical.",
    provenance: shop("src/lib/materials.ts stainless300"),
  },
  {
    id: "330",
    label: "330 high-temp (N08330)",
    alloys: ["330", "N08330"],
    coilOk: true,
    minInsideRadiusXd: 2,
    springbackDegAt1xD: { min: 8, max: 14 },
    notes: "Heat-treat baskets. Its own animal — not 304 with a bigger number.",
    provenance: shop("src/lib/materials.ts; /guide/design-for-wire-forming"),
  },
  {
    id: "6061",
    label: "Aluminum coil (incl. 6061-T6)",
    alloys: ["6061", "6061-T6", "aluminum"],
    coilOk: true,
    minInsideRadiusXd: 0.75,
    springbackDegAt1xD: { min: 1, max: 3 },
    notes: "Can go tighter than carbon. Watch marking. Any aluminum alloy on coil is in.",
    provenance: shop("src/lib/ask-prompt.ts; design guide copper/aluminum note"),
  },
  {
    id: "brass",
    label: "Brass",
    alloys: ["C260", "C270", "C230", "brass"],
    coilOk: true,
    minInsideRadiusXd: 0.75,
    springbackDegAt1xD: { min: 2, max: 5 },
    notes: "Annealed coil forms; hard coil springs back.",
    provenance: shop("src/lib/materials.ts copperAlloys"),
  },
  {
    id: "copper",
    label: "Copper (C110 / C102)",
    alloys: ["C110", "C102", "copper"],
    coilOk: true,
    minInsideRadiusXd: 0.75,
    springbackDegAt1xD: { min: 1, max: 3 },
    notes: "Soft, marks, excellent conductivity. Keep tools clean.",
    provenance: shop("src/lib/materials.ts copperAlloys"),
  },
];

export const RULES: MachineRuleRow[] = [
  {
    id: "rule-diameter",
    machineId: MACHINE_ID,
    check: "wire_diameter",
    severity: "fail",
    title: "Wire must sit in 4–14 mm",
    expression: "WIRE.minMm ≤ diameterMm ≤ WIRE.maxMm",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: catalog(NUMALLIANCE_TF),
  },
  {
    id: "rule-material",
    machineId: MACHINE_ID,
    check: "material_compatibility",
    severity: "fail",
    title: "Material must be a named coil family",
    expression: "materialId ∈ materials where coilOk",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: shop("src/lib/quoting.ts ESTIMATE_MATERIALS; ask-prompt coil rule"),
  },
  {
    id: "rule-radius",
    machineId: MACHINE_ID,
    check: "min_bend_radius",
    severity: "fail",
    title: "Inside radius vs material × diameter",
    expression: "insideRadiusMm ≥ minInsideRadiusXd × diameterMm",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: shop("/guide/design-for-wire-forming"),
  },
  {
    id: "rule-straight-fail",
    machineId: MACHINE_ID,
    check: "min_straight",
    severity: "fail",
    title: "Straight between bends below 2× diameter",
    expression: "straightMm < 2 × diameterMm → FAIL",
    phase: 1,
    implemented: true,
    confidence: "medium",
    provenance: shop("/processes/3d-cnc-wire-forming minimum leg"),
  },
  {
    id: "rule-straight-review",
    machineId: MACHINE_ID,
    check: "min_straight",
    severity: "review",
    title: "Straight between bends 2–3× diameter",
    expression: "2×D ≤ straightMm < 3×D → REVIEW",
    phase: 1,
    implemented: true,
    confidence: "medium",
    provenance: shop("/guide/design-for-wire-forming"),
  },
  {
    id: "rule-tool-stock",
    machineId: MACHINE_ID,
    check: "tool_availability",
    severity: "review",
    title: "Non-stock diameter needs a pin",
    expression: "stock if diameter matches 3/8, 7/16, or 1/2 in; else REVIEW + tooling charge",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: shop("src/lib/price.ts TOOLING.stock"),
  },
  {
    id: "rule-cutoff",
    machineId: MACHINE_ID,
    check: "cutoff_clearance",
    severity: "review",
    title: "First and last legs vs cutoff",
    expression: "endLegMm < 2 × diameterMm → REVIEW",
    phase: 1,
    implemented: true,
    confidence: "low",
    provenance: estimated("Cutoff tool not measured. 2×D tripwire."),
  },
  {
    id: "rule-closed",
    machineId: MACHINE_ID,
    check: "closed_form",
    severity: "review",
    title: "Closed centerline can trap on the mandrel",
    expression: "closed && gapMm < diameterMm → REVIEW (gap, weld, or strip sequence)",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: shop("/processes/3d-cnc-wire-forming closed forms"),
  },
  {
    id: "rule-envelope",
    machineId: MACHINE_ID,
    check: "machine_envelope",
    severity: "fail",
    title: "Developed length vs workspace tripwires",
    expression: "> 6000 mm FAIL; > 2000 mm REVIEW",
    phase: 1,
    implemented: true,
    confidence: "low",
    provenance: estimated("No published max developed length."),
  },
  {
    id: "rule-max-angle",
    machineId: MACHINE_ID,
    check: "rotation_constraint",
    severity: "review",
    title: "Single-bend wrap above 270°",
    expression: "bendAngleDeg > 270 → REVIEW; > 360 → FAIL",
    phase: 1,
    implemented: true,
    confidence: "medium",
    provenance: shop("S-hook / eye wraps to ~240°"),
  },
  {
    id: "rule-springback",
    machineId: MACHINE_ID,
    check: "springback",
    severity: "info",
    title: "Overbend estimate by family",
    expression: "compensationDeg = family.springbackDegAt1xD (starting table)",
    phase: 1,
    implemented: true,
    confidence: "low",
    provenance: estimated(
      "Starting ranges, not a measured springback table. Replace from first-article data.",
    ),
  },
  {
    id: "rule-wipe-angle",
    machineId: MACHINE_ID,
    check: "bend_head",
    severity: "review",
    title: "Wipe-head corners below about 20°",
    expression: "head = wipe && |angleDeg| < 20 → REVIEW",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: shop(
      "Shop floor — wipe head typical 20–180°",
      "Shallow kinks are possible; they need a desk look. 180–270° wraps stay on this head.",
    ),
  },
  {
    id: "rule-push-ring",
    machineId: MACHINE_ID,
    check: "bend_head",
    severity: "fail",
    title: "Push-head ring tighter than 6 in on 1/2 in",
    expression:
      "head = push && diameter ≈ 12.7 mm && centerlineR < 152.4 mm → FAIL",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: shop(
      "Shop floor — push head min ring R 6 in on 1/2 in",
      "Other wire sizes: REVIEW, do not scale 6 in.",
    ),
  },
  {
    id: "rule-sequence",
    machineId: MACHINE_ID,
    check: "sequence_feasibility",
    severity: "review",
    title: "Reversing bends on a short straight",
    expression: "sign(B_n) ≠ sign(B_n+1) && straight < 3×D → REVIEW",
    phase: 1,
    implemented: true,
    confidence: "medium",
    provenance: shop("Design guide reversing zigzags"),
  },
  {
    id: "rule-secondary-weld",
    machineId: MACHINE_ID,
    check: "secondary_operations",
    severity: "info",
    title: "Closed form without a gap needs a weld or strip plan",
    expression: "closed && !(gapMm > 0) → secondary weld or designed gap",
    phase: 1,
    implemented: true,
    confidence: "high",
    provenance: shop("/processes/3d-cnc-wire-forming"),
  },
  {
    id: "rule-tool-clearance",
    machineId: MACHINE_ID,
    check: "tool_clearance",
    severity: "fail",
    title: "Tool interference (Phase 2)",
    expression: "available_clearance_mm ≥ required_clearance_mm",
    phase: 2,
    implemented: false,
    confidence: "none",
    provenance: unknown("Needs tooling solids and a sequenced collision pass."),
  },
  {
    id: "rule-head-collision",
    machineId: MACHINE_ID,
    check: "bend_head_collision",
    severity: "fail",
    title: "Bend-head envelope (Phase 2)",
    expression: "formed geometry ∩ bend-head solid = ∅",
    phase: 2,
    implemented: false,
    confidence: "none",
    provenance: unknown("Measure the 214TF head."),
  },
  {
    id: "rule-formed-leg",
    machineId: MACHINE_ID,
    check: "formed_leg_collision",
    severity: "fail",
    title: "Previously formed leg vs head (Phase 2)",
    expression: "leg_n intersect head_envelope at bend n+1 is empty",
    phase: 2,
    implemented: false,
    confidence: "none",
    provenance: unknown(
      "Brief example: bend 7, required 28 mm, available 19 mm. That number is not on this floor yet.",
    ),
  },
  {
    id: "rule-feed",
    machineId: MACHINE_ID,
    check: "feed_interference",
    severity: "fail",
    title: "Feed interference (Phase 2)",
    expression: "feed path clear of formed legs and tools",
    phase: 2,
    implemented: false,
    confidence: "none",
    provenance: unknown("Measure feed axis and straightener exit."),
  },
];

export const COLLISION_SCENARIOS: CollisionScenarioRow[] = [
  {
    id: "scene-short-straight-head",
    machineId: MACHINE_ID,
    title: "Previously formed leg enters the bending-head envelope",
    check: "formed_leg_collision",
    phase: 2,
    implemented: false,
    notes:
      "Typical fix: lengthen the straight before the failing bend. Phase 1 uses min_straight as a proxy only.",
    provenance: estimated("Product brief example (28 mm required / 19 mm available)."),
  },
  {
    id: "scene-closed-trap",
    machineId: MACHINE_ID,
    title: "Closed rectangle or ring locks on the mandrel",
    check: "closed_form",
    phase: 1,
    implemented: true,
    notes: "Leave a gap, weld after form, or program a strip sequence.",
    provenance: shop("/processes/3d-cnc-wire-forming"),
  },
  {
    id: "scene-zigzag",
    machineId: MACHINE_ID,
    title: "Reversing zigzag with starved straights",
    check: "sequence_feasibility",
    phase: 1,
    implemented: true,
    notes: "Same problem in-plane on 2D programs.",
    provenance: shop("/guide/design-for-wire-forming"),
  },
];

export function twinTables(): TwinTables {
  return {
    machines: [ROBOMAC_214TF],
    machine_heads: HEADS,
    machine_capabilities: CAPABILITIES,
    machine_tooling: TOOLING_ROWS,
    machine_rules: RULES,
    materials: MATERIALS,
    collision_scenarios: COLLISION_SCENARIOS,
    actual_cycle_times: [],
    actual_setup_times: [],
    scrap_results: [],
  };
}

export const ROBOMAC_MACHINE_ID = MACHINE_ID;
