/**
 * City data for programmatic SEO pages
 * Each city has unique content about local industries and why wire forming matters there
 */

export interface CityData {
  slug: string;
  name: string;
  state: string;
  stateCode: string;
  region: "northeast" | "southeast" | "midwest" | "southwest" | "west";
  population: string;
  nickname?: string;
  keyIndustries: string[];
  industrialFacts: string[];
  wireFormingRelevance: string;
  nearbyManufacturing?: string;
  shippingNote: string;
}

export const cities: CityData[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // MIDWEST - Our home region, strongest relevance
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "chicago",
    name: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    region: "midwest",
    population: "2.7 million",
    nickname: "The Windy City",
    keyIndustries: ["Food processing", "Logistics", "Manufacturing", "Transportation equipment"],
    industrialFacts: [
      "Chicago is the largest railroad hub in North America",
      "Home to major food processing companies requiring sanitary wire baskets",
      "O'Hare handles more cargo than any US airport",
    ],
    wireFormingRelevance: "Chicago's massive food processing and logistics industries demand custom wire baskets, racks, and material handling solutions. From meat processing plants to distribution centers, wire forms keep Chicago's supply chain moving.",
    nearbyManufacturing: "Direct freight from Northeast Ohio reaches Chicago overnight",
    shippingNote: "1-day ground shipping from our Ohio facility",
  },
  {
    slug: "detroit",
    name: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    region: "midwest",
    population: "640,000",
    nickname: "Motor City",
    keyIndustries: ["Automotive", "Defense", "Automation", "Robotics"],
    industrialFacts: [
      "Detroit remains the heart of American automotive manufacturing",
      "Home to GM, Ford, and Stellantis headquarters",
      "Growing automation and robotics sector",
    ],
    wireFormingRelevance: "Automotive wire forms are Detroit's bread and butter—seat frames, exhaust hangers, safety guards, and thousands of brackets that hold vehicles together. We supply Tier 1 and Tier 2 automotive manufacturers throughout Michigan.",
    nearbyManufacturing: "Just 170 miles from our Cleveland facility",
    shippingNote: "Same-day delivery available for rush orders",
  },
  {
    slug: "cleveland",
    name: "Cleveland",
    state: "Ohio",
    stateCode: "OH",
    region: "midwest",
    population: "370,000",
    nickname: "The Forest City",
    keyIndustries: ["Steel", "Manufacturing", "Healthcare", "Polymers"],
    industrialFacts: [
      "Cleveland was once the 5th largest city in America",
      "Historic center of steel and heavy manufacturing",
      "Home to NASA Glenn Research Center",
    ],
    wireFormingRelevance: "This is home. Cleveland's steel heritage means local wire mills, short-haul coil delivery, and generations of metalworking expertise. We're part of Cleveland's manufacturing legacy, forming wire just miles from where it's drawn.",
    nearbyManufacturing: "Local pickup available",
    shippingNote: "Local pickup or same-day delivery",
  },
  {
    slug: "columbus",
    name: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    region: "midwest",
    population: "900,000",
    nickname: "The Arch City",
    keyIndustries: ["Logistics", "Data centers", "Insurance", "Retail headquarters"],
    industrialFacts: [
      "Columbus is the fastest-growing city in the Midwest",
      "Major logistics hub—within 500 miles of 50% of US population",
      "Rapidly expanding data center corridor",
    ],
    wireFormingRelevance: "Columbus's booming data center industry needs cable trays, server rack accessories, and wire management solutions. The city's logistics dominance means distribution centers requiring wire baskets, shelving, and material handling equipment.",
    nearbyManufacturing: "140 miles from our facility—easy day trips for engineering meetings",
    shippingNote: "Next-day ground shipping",
  },
  {
    slug: "cincinnati",
    name: "Cincinnati",
    state: "Ohio",
    stateCode: "OH",
    region: "midwest",
    population: "310,000",
    nickname: "The Queen City",
    keyIndustries: ["Consumer goods", "Aerospace", "Machine tools", "Food & beverage"],
    industrialFacts: [
      "Home to P&G, Kroger, and dozens of Fortune 500 companies",
      "Major aerospace manufacturing hub with GE Aviation",
      "Historic machine tool manufacturing center",
    ],
    wireFormingRelevance: "Cincinnati's consumer goods giants need wire displays, retail fixtures, and packaging solutions. GE Aviation and aerospace suppliers demand precision wire forms for jet engine components and ground support equipment.",
    nearbyManufacturing: "250 miles—direct I-71 corridor",
    shippingNote: "Next-day ground shipping",
  },
  {
    slug: "indianapolis",
    name: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    region: "midwest",
    population: "880,000",
    nickname: "The Crossroads of America",
    keyIndustries: ["Automotive", "Pharmaceuticals", "Logistics", "Advanced manufacturing"],
    industrialFacts: [
      "More interstate highways converge in Indianapolis than any other US city",
      "Major pharmaceutical manufacturing center",
      "Home to Indianapolis Motor Speedway—motorsports manufacturing hub",
    ],
    wireFormingRelevance: "Indianapolis sits at the crossroads of American manufacturing. Pharmaceutical companies need stainless wire baskets for cleanroom applications. Automotive suppliers need everything from seat frames to exhaust hangers. And Indy's racing industry demands precision fabrication.",
    nearbyManufacturing: "300 miles via I-70",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "milwaukee",
    name: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    region: "midwest",
    population: "570,000",
    nickname: "Brew City",
    keyIndustries: ["Heavy machinery", "Brewing", "Medical devices", "Power generation"],
    industrialFacts: [
      "Milwaukee makes more mining and construction equipment than anywhere else",
      "Historic brewing capital with major food processing",
      "Growing medical device manufacturing cluster",
    ],
    wireFormingRelevance: "Milwaukee's heavy equipment manufacturers need rugged wire guards, machine safety enclosures, and industrial baskets. The brewing and food processing industries require sanitary stainless wire solutions. Medical device companies need precision small-gauge forms.",
    nearbyManufacturing: "380 miles via I-90",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "minneapolis",
    name: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    region: "midwest",
    population: "430,000",
    nickname: "Mill City",
    keyIndustries: ["Medical devices", "Food processing", "Electronics", "Retail"],
    industrialFacts: [
      "Minneapolis-St. Paul is the medical device capital of the world",
      "Home to Target, Best Buy, 3M, and General Mills headquarters",
      "Major food processing and agricultural equipment hub",
    ],
    wireFormingRelevance: "The Twin Cities' medical device giants need precision stainless wire forms for surgical instruments, implant delivery systems, and diagnostic equipment. Food processing operations demand sanitary wire baskets and conveyors.",
    nearbyManufacturing: "600 miles—2-day shipping",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "st-louis",
    name: "St. Louis",
    state: "Missouri",
    stateCode: "MO",
    region: "midwest",
    population: "300,000",
    nickname: "Gateway to the West",
    keyIndustries: ["Aerospace", "Automotive", "Brewing", "Agriculture equipment"],
    industrialFacts: [
      "Boeing's defense division is headquartered here",
      "Major automotive manufacturing presence",
      "Anheuser-Busch headquarters and massive brewing operations",
    ],
    wireFormingRelevance: "St. Louis bridges East and West, and our wire forms ship through here to both coasts. Boeing suppliers need aerospace-grade wire forms. Automotive plants need production parts. And the brewing industry needs stainless sanitary equipment.",
    nearbyManufacturing: "500 miles via I-70",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "kansas-city",
    name: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    region: "midwest",
    population: "510,000",
    nickname: "Heart of America",
    keyIndustries: ["Agriculture", "Automotive", "Logistics", "Animal health"],
    industrialFacts: [
      "Kansas City is the #1 freight rail hub in America",
      "Major automotive assembly plants from GM and Ford",
      "Center of the US animal health corridor",
    ],
    wireFormingRelevance: "KC's position as America's rail hub means logistics equipment—wire containers, baskets, and pallets. The animal health industry needs specialized wire forms for veterinary and agricultural applications.",
    shippingNote: "2-day ground shipping",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NORTHEAST - Major industrial corridor
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "new-york",
    name: "New York City",
    state: "New York",
    stateCode: "NY",
    region: "northeast",
    population: "8.3 million",
    nickname: "The Big Apple",
    keyIndustries: ["Finance", "Media", "Fashion", "Food service"],
    industrialFacts: [
      "NYC has more restaurants than any US city",
      "Fashion district requires retail displays and fixtures",
      "Massive building and construction market",
    ],
    wireFormingRelevance: "New York's restaurant industry needs kitchen equipment—wire shelving, cooling racks, and storage baskets. Retail stores need wire displays. Construction projects need safety guards and concrete reinforcement supports.",
    shippingNote: "1-2 day ground shipping via I-80",
  },
  {
    slug: "philadelphia",
    name: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    region: "northeast",
    population: "1.6 million",
    nickname: "The City of Brotherly Love",
    keyIndustries: ["Pharmaceuticals", "Healthcare", "Oil refining", "Food processing"],
    industrialFacts: [
      "Philadelphia has the largest concentration of pharmaceutical companies on the East Coast",
      "Major oil refining hub on the Delaware River",
      "Historic manufacturing center",
    ],
    wireFormingRelevance: "Philly's pharmaceutical giants need stainless wire baskets for cleanroom manufacturing. Oil refineries need industrial guards and safety equipment. The region's food processors demand sanitary wire solutions.",
    shippingNote: "1-day ground shipping via I-76",
  },
  {
    slug: "pittsburgh",
    name: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    region: "northeast",
    population: "300,000",
    nickname: "The Steel City",
    keyIndustries: ["Steel", "Robotics", "Healthcare", "Energy"],
    industrialFacts: [
      "Pittsburgh invented the modern steel industry",
      "Now a leading robotics and AI hub",
      "Major healthcare and university research center",
    ],
    wireFormingRelevance: "Pittsburgh understands steel. The city's robotics companies need precision wire forms for automation. Healthcare institutions need medical-grade stainless products. And the energy sector needs industrial wire solutions for power generation.",
    nearbyManufacturing: "130 miles via I-76—our closest major city",
    shippingNote: "Same-day or next-day delivery",
  },
  {
    slug: "boston",
    name: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    region: "northeast",
    population: "680,000",
    nickname: "The Hub",
    keyIndustries: ["Biotech", "Medical devices", "Defense", "Education"],
    industrialFacts: [
      "Boston-Cambridge is the biotech capital of the world",
      "Major defense contractor presence",
      "World-leading research universities",
    ],
    wireFormingRelevance: "Boston's biotech and medical device companies need precision stainless wire forms for lab equipment, surgical instruments, and diagnostic devices. Defense contractors need wire forms for military applications.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "baltimore",
    name: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    region: "northeast",
    population: "570,000",
    nickname: "Charm City",
    keyIndustries: ["Defense", "Healthcare", "Shipping", "Steel"],
    industrialFacts: [
      "Baltimore's port is the closest Atlantic port to the Midwest",
      "Major defense contractor hub near DC",
      "Historic steel manufacturing at Sparrows Point",
    ],
    wireFormingRelevance: "Baltimore's defense contractors need wire forms for military equipment. The port handles massive volumes of cargo requiring wire containers and pallets. And the region's steel heritage means customers who understand metalworking.",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "newark",
    name: "Newark",
    state: "New Jersey",
    stateCode: "NJ",
    region: "northeast",
    population: "310,000",
    keyIndustries: ["Logistics", "Pharmaceuticals", "Insurance", "Port operations"],
    industrialFacts: [
      "Port Newark is the busiest on the East Coast",
      "Major pharmaceutical manufacturing hub",
      "Amazon's largest East Coast fulfillment center",
    ],
    wireFormingRelevance: "Newark's logistics operations need wire containers, pallets, and material handling equipment. Pharmaceutical companies need stainless wire solutions. Distribution centers need storage and organization products.",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "hartford",
    name: "Hartford",
    state: "Connecticut",
    stateCode: "CT",
    region: "northeast",
    population: "120,000",
    keyIndustries: ["Aerospace", "Insurance", "Defense", "Precision manufacturing"],
    industrialFacts: [
      "Hartford is the jet engine capital—home to Pratt & Whitney",
      "Historic firearms manufacturing center",
      "Major precision manufacturing cluster",
    ],
    wireFormingRelevance: "Hartford's aerospace industry demands precision wire forms for jet engine components. The region's precision manufacturing heritage means customers with exacting standards. Defense contractors need specialized wire solutions.",
    shippingNote: "1-2 day ground shipping",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // SOUTHEAST - Growing manufacturing region
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "atlanta",
    name: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    region: "southeast",
    population: "500,000",
    nickname: "The ATL",
    keyIndustries: ["Logistics", "Automotive", "Food & beverage", "Film production"],
    industrialFacts: [
      "Atlanta's Hartsfield-Jackson is the world's busiest airport",
      "Major automotive assembly presence—Kia, Mercedes nearby",
      "Coca-Cola headquarters and beverage manufacturing hub",
    ],
    wireFormingRelevance: "Atlanta's logistics dominance means massive demand for material handling—wire baskets, containers, and shelving. Automotive plants need production wire forms. Food and beverage companies need sanitary processing equipment.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "charlotte",
    name: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    region: "southeast",
    population: "880,000",
    nickname: "The Queen City",
    keyIndustries: ["Banking", "Automotive", "Energy", "Aerospace"],
    industrialFacts: [
      "Charlotte is America's second-largest banking center",
      "Major NASCAR and motorsports manufacturing hub",
      "Growing aerospace manufacturing cluster",
    ],
    wireFormingRelevance: "Charlotte's automotive and motorsports industries need precision wire forms. Data centers supporting the banking industry need cable management. Aerospace companies need specialized wire solutions.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "nashville",
    name: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    region: "southeast",
    population: "690,000",
    nickname: "Music City",
    keyIndustries: ["Healthcare", "Automotive", "Music industry", "Logistics"],
    industrialFacts: [
      "Nashville is the healthcare management capital of America",
      "Nissan North America headquarters",
      "Fastest-growing major metro in the country",
    ],
    wireFormingRelevance: "Nashville's healthcare companies need wire forms for medical equipment and hospital supplies. Nissan and automotive suppliers need production parts. The region's explosive growth means construction and infrastructure wire products.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "miami",
    name: "Miami",
    state: "Florida",
    stateCode: "FL",
    region: "southeast",
    population: "440,000",
    nickname: "The Magic City",
    keyIndustries: ["Tourism", "Cruise lines", "International trade", "Healthcare"],
    industrialFacts: [
      "Miami is the cruise capital of the world",
      "Major gateway for Latin American trade",
      "Growing healthcare and biotech sector",
    ],
    wireFormingRelevance: "Miami's cruise industry needs galvanized and stainless marine-grade wire products. Tourism infrastructure requires retail displays and hospitality equipment. The port handles Latin American trade requiring wire containers.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "tampa",
    name: "Tampa",
    state: "Florida",
    stateCode: "FL",
    region: "southeast",
    population: "390,000",
    nickname: "The Big Guava",
    keyIndustries: ["Defense", "Healthcare", "Finance", "Tourism"],
    industrialFacts: [
      "MacDill Air Force Base is a major defense hub",
      "Growing financial services sector",
      "Major port for Florida trade",
    ],
    wireFormingRelevance: "Tampa's defense contractors need wire forms for military applications. Healthcare facilities need medical equipment. The tourism industry requires hospitality and food service wire products.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "orlando",
    name: "Orlando",
    state: "Florida",
    stateCode: "FL",
    region: "southeast",
    population: "310,000",
    nickname: "The City Beautiful",
    keyIndustries: ["Tourism", "Simulation", "Aerospace", "Film production"],
    industrialFacts: [
      "Orlando is the theme park capital of the world",
      "Major simulation and training industry hub",
      "Growing aerospace manufacturing presence",
    ],
    wireFormingRelevance: "Orlando's theme parks and attractions need custom wire displays, safety barriers, and queue management. The simulation industry needs precision components. Aerospace companies need specialized wire forms.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "raleigh",
    name: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    region: "southeast",
    population: "470,000",
    nickname: "City of Oaks",
    keyIndustries: ["Technology", "Pharmaceuticals", "Education", "Research"],
    industrialFacts: [
      "Research Triangle Park is one of the largest research parks in the world",
      "Major pharmaceutical and biotech hub",
      "Growing data center corridor",
    ],
    wireFormingRelevance: "The Research Triangle's pharmaceutical companies need cleanroom-compatible stainless wire baskets. Biotech firms need precision lab equipment. Data centers need cable management and server accessories.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "birmingham",
    name: "Birmingham",
    state: "Alabama",
    stateCode: "AL",
    region: "southeast",
    population: "200,000",
    nickname: "The Magic City",
    keyIndustries: ["Steel", "Automotive", "Healthcare", "Banking"],
    industrialFacts: [
      "Birmingham was built on iron and steel—the 'Pittsburgh of the South'",
      "Major automotive supplier hub for Mercedes, Honda, Hyundai plants",
      "Growing healthcare sector",
    ],
    wireFormingRelevance: "Birmingham understands metalworking. The automotive corridor needs production wire forms. Steel heritage means customers who appreciate quality fabrication. Healthcare institutions need medical-grade products.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "charleston-sc",
    name: "Charleston",
    state: "South Carolina",
    stateCode: "SC",
    region: "southeast",
    population: "150,000",
    keyIndustries: ["Aerospace", "Automotive", "Port operations", "Tourism"],
    industrialFacts: [
      "Boeing's 787 Dreamliner final assembly is here",
      "Volvo's only US plant is nearby",
      "Major East Coast port",
    ],
    wireFormingRelevance: "Charleston's Boeing facility and aerospace suppliers need precision wire forms. Volvo and automotive companies need production parts. The port handles materials and equipment requiring wire containers.",
    shippingNote: "2-day ground shipping",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // SOUTHWEST - Growing industrial region
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "houston",
    name: "Houston",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "2.3 million",
    nickname: "Space City",
    keyIndustries: ["Oil & gas", "Aerospace", "Healthcare", "Shipping"],
    industrialFacts: [
      "Houston is the energy capital of the world",
      "NASA Johnson Space Center headquarters",
      "Largest medical center on Earth—Texas Medical Center",
    ],
    wireFormingRelevance: "Houston's energy industry needs wire forms that survive extreme conditions—high temperatures, corrosive environments, offshore applications. NASA contractors need aerospace-grade components. The medical center needs stainless surgical and hospital equipment.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "dallas",
    name: "Dallas",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "1.3 million",
    nickname: "Big D",
    keyIndustries: ["Technology", "Telecommunications", "Defense", "Finance"],
    industrialFacts: [
      "Dallas-Fort Worth has more corporate headquarters than anywhere outside NYC",
      "Major defense contractor hub—Lockheed Martin, Raytheon",
      "Texas Instruments and semiconductor manufacturing",
    ],
    wireFormingRelevance: "Dallas's tech companies need precision components. Defense contractors need specialized wire forms. The telecommunications industry needs cable management and infrastructure products. Data centers need server accessories.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "san-antonio",
    name: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "1.5 million",
    nickname: "Alamo City",
    keyIndustries: ["Military", "Healthcare", "Cybersecurity", "Aerospace"],
    industrialFacts: [
      "San Antonio has the largest military presence of any US city",
      "Major Air Force and Army installations",
      "Growing cybersecurity and aerospace hub",
    ],
    wireFormingRelevance: "Military bases need durable wire products for equipment, storage, and security. Healthcare facilities need medical-grade stainless products. Aerospace companies need precision wire forms.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "austin",
    name: "Austin",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "1 million",
    nickname: "Silicon Hills",
    keyIndustries: ["Technology", "Semiconductors", "Clean energy", "Film"],
    industrialFacts: [
      "Tesla, Apple, Google, Meta, and Samsung all have major facilities here",
      "Growing semiconductor manufacturing hub",
      "One of the fastest-growing tech cities in America",
    ],
    wireFormingRelevance: "Austin's tech giants need cleanroom-compatible components. Semiconductor fabs need specialized wire handling equipment. The clean energy sector needs solar and battery manufacturing components. Data centers need cable management.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    region: "southwest",
    population: "1.6 million",
    nickname: "Valley of the Sun",
    keyIndustries: ["Semiconductors", "Aerospace", "Data centers", "Solar"],
    industrialFacts: [
      "TSMC and Intel are building massive semiconductor fabs here",
      "Major aerospace manufacturing presence",
      "One of the hottest data center markets in America",
    ],
    wireFormingRelevance: "Phoenix's semiconductor boom means demand for cleanroom wire products. Aerospace companies need precision components. Data centers need cable trays and management systems. The solar industry needs mounting and support hardware.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "albuquerque",
    name: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    region: "southwest",
    population: "560,000",
    keyIndustries: ["Defense", "National labs", "Aerospace", "Film"],
    industrialFacts: [
      "Sandia and Los Alamos National Labs are major employers",
      "Kirtland Air Force Base defense hub",
      "Growing aerospace and space industry",
    ],
    wireFormingRelevance: "National labs and defense contractors need specialized wire forms for research and military applications. Aerospace companies need precision components. The unique environment demands products built for high altitude and desert conditions.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "el-paso",
    name: "El Paso",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "680,000",
    keyIndustries: ["Defense", "Manufacturing", "Logistics", "Healthcare"],
    industrialFacts: [
      "Fort Bliss is one of the largest Army installations",
      "Major US-Mexico trade gateway",
      "Growing manufacturing sector",
    ],
    wireFormingRelevance: "Military installations need durable wire products. Cross-border manufacturing means wire forms for maquiladoras and assembly operations. Logistics companies need material handling equipment.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "tucson",
    name: "Tucson",
    state: "Arizona",
    stateCode: "AZ",
    region: "southwest",
    population: "540,000",
    keyIndustries: ["Aerospace", "Defense", "Mining", "Optics"],
    industrialFacts: [
      "Raytheon Missiles is a major employer",
      "University of Arizona optics research hub",
      "Historic copper mining region",
    ],
    wireFormingRelevance: "Defense contractors need precision wire forms for missile and weapons systems. The optics industry needs specialized components. Mining operations need durable industrial wire products.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "denver",
    name: "Denver",
    state: "Colorado",
    stateCode: "CO",
    region: "southwest",
    population: "715,000",
    nickname: "Mile High City",
    keyIndustries: ["Aerospace", "Technology", "Energy", "Outdoor recreation"],
    industrialFacts: [
      "Denver is a major aerospace hub—Lockheed Martin, Ball Aerospace, United Launch Alliance",
      "Growing tech sector with data centers",
      "Renewable energy manufacturing presence",
    ],
    wireFormingRelevance: "Denver's aerospace companies need precision wire forms for satellites, launch vehicles, and defense systems. Tech companies need data center equipment. The outdoor industry needs durable products for extreme conditions.",
    shippingNote: "2-3 day ground shipping",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // WEST COAST - Major manufacturing corridor
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "los-angeles",
    name: "Los Angeles",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "3.9 million",
    nickname: "City of Angels",
    keyIndustries: ["Aerospace", "Entertainment", "Ports", "Fashion"],
    industrialFacts: [
      "LA County has the largest manufacturing base in America",
      "Ports of LA and Long Beach handle 40% of US container imports",
      "Major aerospace and defense hub",
    ],
    wireFormingRelevance: "LA's aerospace giants need precision wire forms. The massive ports need material handling equipment. Entertainment and retail need custom displays. Fashion and apparel need wire fixtures and hangers.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "870,000",
    nickname: "The City by the Bay",
    keyIndustries: ["Technology", "Biotech", "Finance", "Tourism"],
    industrialFacts: [
      "SF and Silicon Valley are the tech capital of the world",
      "Major biotech research and manufacturing hub",
      "Headquarters for countless tech companies",
    ],
    wireFormingRelevance: "Tech companies need precision components for hardware and data centers. Biotech firms need cleanroom-compatible stainless wire products. The city's restaurants and hospitality need food service equipment.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "san-diego",
    name: "San Diego",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "1.4 million",
    nickname: "America's Finest City",
    keyIndustries: ["Defense", "Biotech", "Wireless technology", "Tourism"],
    industrialFacts: [
      "San Diego has the largest concentration of Navy and Marine Corps personnel",
      "Major biotech and medical device hub",
      "Qualcomm and wireless technology center",
    ],
    wireFormingRelevance: "Naval bases need marine-grade wire products. Biotech and medical device companies need stainless precision components. Defense contractors need military-spec wire forms.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "seattle",
    name: "Seattle",
    state: "Washington",
    stateCode: "WA",
    region: "west",
    population: "750,000",
    nickname: "The Emerald City",
    keyIndustries: ["Aerospace", "Technology", "E-commerce", "Maritime"],
    industrialFacts: [
      "Boeing Commercial Airplanes headquarters",
      "Amazon and Microsoft headquarters",
      "Major Pacific shipping hub",
    ],
    wireFormingRelevance: "Boeing and aerospace suppliers need precision wire forms for aircraft. Amazon's massive fulfillment network needs material handling equipment. The maritime industry needs marine-grade wire products.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "portland",
    name: "Portland",
    state: "Oregon",
    stateCode: "OR",
    region: "west",
    population: "650,000",
    nickname: "Rose City",
    keyIndustries: ["Technology", "Outdoor gear", "Semiconductors", "Sustainable products"],
    industrialFacts: [
      "Intel's largest manufacturing complex is nearby",
      "Nike, Columbia, and outdoor industry headquarters",
      "Growing clean tech and sustainable manufacturing",
    ],
    wireFormingRelevance: "Intel and semiconductor companies need cleanroom wire products. Outdoor gear companies need durable wire components. The sustainability focus means demand for recyclable and eco-friendly wire solutions.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "san-jose",
    name: "San Jose",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "1 million",
    nickname: "Capital of Silicon Valley",
    keyIndustries: ["Semiconductors", "Technology", "Clean energy", "Data centers"],
    industrialFacts: [
      "San Jose is the heart of Silicon Valley",
      "Major semiconductor manufacturing hub",
      "Home to Google, Apple, and dozens of tech giants",
    ],
    wireFormingRelevance: "Semiconductor fabs need ultra-clean wire handling equipment. Tech companies need precision components. Data centers need cable management systems. Clean energy companies need solar and battery manufacturing wire products.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "salt-lake-city",
    name: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    region: "west",
    population: "200,000",
    nickname: "The Crossroads of the West",
    keyIndustries: ["Technology", "Outdoor recreation", "Mining", "Aerospace"],
    industrialFacts: [
      "Utah has one of the fastest-growing tech sectors in America",
      "Major outdoor gear and recreation manufacturing",
      "Historic mining and materials industry",
    ],
    wireFormingRelevance: "Tech companies need precision wire components. Outdoor gear manufacturers need durable wire products for extreme conditions. Mining operations need industrial wire solutions. Aerospace companies need precision forms.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "las-vegas",
    name: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    region: "west",
    population: "650,000",
    nickname: "Sin City",
    keyIndustries: ["Hospitality", "Data centers", "Solar", "Events"],
    industrialFacts: [
      "Las Vegas is becoming a major data center hub",
      "Massive solar energy installations in the desert",
      "Convention and trade show capital",
    ],
    wireFormingRelevance: "Data centers need cable trays and management systems. Solar installations need mounting and support wire products. Hotels and casinos need hospitality equipment. Convention centers need displays and fixtures.",
    shippingNote: "3-day ground shipping",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL MIDWEST CITIES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "toledo",
    name: "Toledo",
    state: "Ohio",
    stateCode: "OH",
    region: "midwest",
    population: "270,000",
    nickname: "Glass City",
    keyIndustries: ["Glass", "Automotive", "Solar", "Logistics"],
    industrialFacts: [
      "Toledo is the glass capital of America",
      "Major Jeep manufacturing presence",
      "Growing solar panel manufacturing hub",
    ],
    wireFormingRelevance: "The glass industry needs specialized wire handling and support. Automotive plants need production wire forms. Solar manufacturing needs assembly fixtures. Our proximity means same-day service.",
    nearbyManufacturing: "110 miles—one of our closest markets",
    shippingNote: "Same-day or next-day delivery",
  },
  {
    slug: "akron",
    name: "Akron",
    state: "Ohio",
    stateCode: "OH",
    region: "midwest",
    population: "190,000",
    nickname: "Rubber City",
    keyIndustries: ["Polymers", "Tire manufacturing", "Healthcare", "Logistics"],
    industrialFacts: [
      "Akron was the rubber and tire capital of the world",
      "Now a leading polymer research center",
      "Major healthcare presence with Akron General",
    ],
    wireFormingRelevance: "Polymer and rubber companies need wire reinforcement and processing equipment. Healthcare facilities need medical-grade products. The manufacturing heritage means customers who appreciate quality metalwork.",
    nearbyManufacturing: "40 miles—local delivery available",
    shippingNote: "Same-day delivery",
  },
  {
    slug: "dayton",
    name: "Dayton",
    state: "Ohio",
    stateCode: "OH",
    region: "midwest",
    population: "140,000",
    nickname: "Birthplace of Aviation",
    keyIndustries: ["Aerospace", "Defense", "Healthcare", "Advanced materials"],
    industrialFacts: [
      "Wright-Patterson Air Force Base is a major defense R&D center",
      "Wright Brothers invented the airplane here",
      "Strong aerospace supplier base",
    ],
    wireFormingRelevance: "Defense contractors at Wright-Patterson need precision wire forms. Aerospace suppliers need aircraft components. The region's manufacturing heritage means skilled customers who understand metalworking.",
    nearbyManufacturing: "220 miles via I-70",
    shippingNote: "Next-day ground shipping",
  },
  {
    slug: "grand-rapids",
    name: "Grand Rapids",
    state: "Michigan",
    stateCode: "MI",
    region: "midwest",
    population: "200,000",
    nickname: "Furniture City",
    keyIndustries: ["Furniture", "Automotive", "Aerospace", "Medical devices"],
    industrialFacts: [
      "Grand Rapids is the office furniture capital—Steelcase, Herman Miller, Haworth",
      "Growing aerospace manufacturing hub",
      "Strong medical device sector",
    ],
    wireFormingRelevance: "Furniture manufacturers need wire frames, baskets, and components. Automotive suppliers need production parts. Medical device companies need precision stainless forms. We've supplied Grand Rapids for decades.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "fort-wayne",
    name: "Fort Wayne",
    state: "Indiana",
    stateCode: "IN",
    region: "midwest",
    population: "270,000",
    keyIndustries: ["Defense", "Automotive", "Medical devices", "Food processing"],
    industrialFacts: [
      "Home to defense contractors and General Motors plant",
      "Growing medical device manufacturing hub",
      "Major food processing presence",
    ],
    wireFormingRelevance: "Defense contractors need durable wire products. Automotive plants need production wire forms. Medical device companies need stainless precision components. Food processors need sanitary wire equipment.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "omaha",
    name: "Omaha",
    state: "Nebraska",
    stateCode: "NE",
    region: "midwest",
    population: "490,000",
    keyIndustries: ["Food processing", "Railroads", "Finance", "Data centers"],
    industrialFacts: [
      "Omaha is a major beef processing center",
      "Union Pacific Railroad headquarters",
      "Growing data center hub in the heartland",
    ],
    wireFormingRelevance: "Food processing plants need sanitary stainless wire baskets and conveyors. Railroads need durable industrial products. Data centers need cable management and server accessories.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "wichita",
    name: "Wichita",
    state: "Kansas",
    stateCode: "KS",
    region: "midwest",
    population: "390,000",
    nickname: "Air Capital of the World",
    keyIndustries: ["Aerospace", "Aviation manufacturing", "Defense", "Agriculture"],
    industrialFacts: [
      "More aircraft are built in Wichita than anywhere else",
      "Textron Aviation, Spirit AeroSystems, Learjet",
      "Major Boeing presence",
    ],
    wireFormingRelevance: "Wichita's aircraft manufacturers need precision wire forms for aviation applications. The concentration of aerospace expertise means customers who demand exacting quality. We ship to the Air Capital daily.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "des-moines",
    name: "Des Moines",
    state: "Iowa",
    stateCode: "IA",
    region: "midwest",
    population: "215,000",
    keyIndustries: ["Insurance", "Agriculture", "Food processing", "Data centers"],
    industrialFacts: [
      "Des Moines is a major insurance headquarters hub",
      "John Deere and agricultural equipment manufacturing",
      "Growing data center market due to low energy costs",
    ],
    wireFormingRelevance: "Agricultural equipment manufacturers need durable wire forms. Food processing facilities need sanitary stainless products. Data centers need cable management systems. Insurance companies need office and retail fixtures.",
    shippingNote: "2-day ground shipping",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL SOUTHERN CITIES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "louisville",
    name: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    region: "southeast",
    population: "620,000",
    keyIndustries: ["Logistics", "Automotive", "Healthcare", "Bourbon"],
    industrialFacts: [
      "UPS Worldport—the largest automated package handling facility on Earth",
      "Ford truck manufacturing hub",
      "GE Appliance headquarters",
    ],
    wireFormingRelevance: "UPS's massive logistics operation needs wire containers, sorting equipment, and material handling. Ford and automotive suppliers need production wire forms. GE needs appliance components. The bourbon industry needs barrel handling equipment.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "memphis",
    name: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    region: "southeast",
    population: "630,000",
    keyIndustries: ["Logistics", "Medical devices", "Food processing", "Music"],
    industrialFacts: [
      "FedEx Super Hub makes Memphis the cargo shipping center of America",
      "Major medical device manufacturing—Smith & Nephew, Medtronic",
      "Historic food processing presence",
    ],
    wireFormingRelevance: "FedEx's logistics operations need wire containers and handling equipment. Medical device companies need stainless precision components. Food processors need sanitary wire solutions.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "new-orleans",
    name: "New Orleans",
    state: "Louisiana",
    stateCode: "LA",
    region: "southeast",
    population: "390,000",
    nickname: "The Big Easy",
    keyIndustries: ["Oil & gas", "Shipping", "Tourism", "Food processing"],
    industrialFacts: [
      "Major Gulf Coast oil and gas hub",
      "Port of New Orleans handles significant Mississippi River trade",
      "Massive food processing and seafood industry",
    ],
    wireFormingRelevance: "Oil and gas operations need wire forms that survive harsh Gulf conditions. The port needs material handling equipment. Food processors and restaurants need sanitary stainless wire products.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "jacksonville",
    name: "Jacksonville",
    state: "Florida",
    stateCode: "FL",
    region: "southeast",
    population: "950,000",
    keyIndustries: ["Logistics", "Navy", "Finance", "Healthcare"],
    industrialFacts: [
      "Jacksonville has the largest port complex in the Southeast",
      "Major Navy presence—Naval Station Mayport",
      "Growing logistics and distribution hub",
    ],
    wireFormingRelevance: "Naval operations need marine-grade wire products. The massive port needs material handling equipment. Distribution centers need wire baskets, shelving, and storage solutions.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "richmond",
    name: "Richmond",
    state: "Virginia",
    stateCode: "VA",
    region: "southeast",
    population: "230,000",
    keyIndustries: ["Finance", "Healthcare", "Government", "Manufacturing"],
    industrialFacts: [
      "Major banking and financial services center",
      "Strong healthcare and pharmaceutical presence",
      "Federal Reserve Bank of Richmond",
    ],
    wireFormingRelevance: "Healthcare facilities need medical-grade stainless products. Government agencies need durable equipment. The manufacturing base needs industrial wire forms.",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "greenville",
    name: "Greenville",
    state: "South Carolina",
    stateCode: "SC",
    region: "southeast",
    population: "72,000",
    keyIndustries: ["Automotive", "Aerospace", "Textiles", "Advanced manufacturing"],
    industrialFacts: [
      "BMW's only US manufacturing plant is here",
      "Major tire manufacturing hub—Michelin headquarters",
      "Growing aerospace supplier presence",
    ],
    wireFormingRelevance: "BMW and Michelin need automotive wire forms. Aerospace suppliers need precision components. The textile industry needs processing equipment. The manufacturing renaissance means customers who value quality.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "huntsville",
    name: "Huntsville",
    state: "Alabama",
    stateCode: "AL",
    region: "southeast",
    population: "220,000",
    nickname: "Rocket City",
    keyIndustries: ["Aerospace", "Defense", "NASA", "Technology"],
    industrialFacts: [
      "NASA Marshall Space Flight Center headquarters",
      "Major Redstone Arsenal defense hub",
      "Space launch and missile systems development",
    ],
    wireFormingRelevance: "NASA and aerospace contractors need precision wire forms for space applications. Defense systems require specialized components. The concentration of engineering talent means customers with exacting standards.",
    shippingNote: "2-day ground shipping",
  },
  // More cities to reach 100...
  {
    slug: "boise",
    name: "Boise",
    state: "Idaho",
    stateCode: "ID",
    region: "west",
    population: "235,000",
    keyIndustries: ["Technology", "Semiconductors", "Food processing", "Outdoor recreation"],
    industrialFacts: [
      "Micron Technology headquarters—major semiconductor manufacturer",
      "Growing tech hub in the Mountain West",
      "Significant food processing for Idaho agriculture",
    ],
    wireFormingRelevance: "Semiconductor companies need cleanroom-compatible wire products. Food processors need sanitary stainless equipment. Outdoor recreation companies need durable wire components.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "spokane",
    name: "Spokane",
    state: "Washington",
    stateCode: "WA",
    region: "west",
    population: "230,000",
    keyIndustries: ["Healthcare", "Aerospace", "Mining", "Agriculture"],
    industrialFacts: [
      "Major regional healthcare hub",
      "Aerospace supplier presence",
      "Historic mining and forestry industries",
    ],
    wireFormingRelevance: "Healthcare facilities need medical-grade stainless products. Aerospace suppliers need precision components. Mining operations need durable industrial wire forms.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "fresno",
    name: "Fresno",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "540,000",
    keyIndustries: ["Agriculture", "Food processing", "Logistics", "Healthcare"],
    industrialFacts: [
      "Fresno County is the most productive agricultural county in America",
      "Major food processing and packaging hub",
      "Central Valley distribution center",
    ],
    wireFormingRelevance: "Agricultural operations need durable wire products for harvesting and handling. Food processors need sanitary stainless baskets and conveyors. Distribution centers need material handling equipment.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "sacramento",
    name: "Sacramento",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "525,000",
    nickname: "City of Trees",
    keyIndustries: ["Government", "Healthcare", "Food processing", "Technology"],
    industrialFacts: [
      "State capital with massive government operations",
      "Growing tech presence as Bay Area companies expand",
      "Regional healthcare hub",
    ],
    wireFormingRelevance: "Government facilities need durable equipment. Healthcare systems need medical-grade products. Food processors in the Central Valley need sanitary wire solutions.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "long-beach",
    name: "Long Beach",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "465,000",
    keyIndustries: ["Shipping", "Aerospace", "Oil & gas", "Healthcare"],
    industrialFacts: [
      "Port of Long Beach is the second-busiest in America",
      "Major aerospace manufacturing—Boeing C-17 production",
      "Significant oil industry presence",
    ],
    wireFormingRelevance: "The massive port needs wire containers, pallets, and material handling. Aerospace companies need precision wire forms. Oil operations need industrial-grade products.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "oakland",
    name: "Oakland",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "430,000",
    keyIndustries: ["Shipping", "Manufacturing", "Healthcare", "Food processing"],
    industrialFacts: [
      "Port of Oakland is the largest in Northern California",
      "Historic manufacturing and industrial base",
      "Food processing for Bay Area markets",
    ],
    wireFormingRelevance: "Port operations need material handling equipment. Manufacturing facilities need industrial wire products. Food processors need sanitary stainless solutions.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "bakersfield",
    name: "Bakersfield",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "405,000",
    keyIndustries: ["Oil & gas", "Agriculture", "Logistics", "Renewable energy"],
    industrialFacts: [
      "Bakersfield is in the heart of California's oil fields",
      "Major agricultural hub for fruits and vegetables",
      "Growing solar energy installations",
    ],
    wireFormingRelevance: "Oil operations need wire forms for harsh conditions. Agricultural processors need handling equipment. Solar installations need mounting hardware and supports.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "tulsa",
    name: "Tulsa",
    state: "Oklahoma",
    stateCode: "OK",
    region: "southwest",
    population: "410,000",
    keyIndustries: ["Oil & gas", "Aerospace", "Manufacturing", "Healthcare"],
    industrialFacts: [
      "Historic oil capital—still a major energy hub",
      "American Airlines maintenance base",
      "Growing aerospace manufacturing cluster",
    ],
    wireFormingRelevance: "Oil and gas operations need durable industrial wire products. Aerospace maintenance and manufacturing need precision components. The energy industry heritage means customers who understand metalworking.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "oklahoma-city",
    name: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    region: "southwest",
    population: "680,000",
    nickname: "OKC",
    keyIndustries: ["Oil & gas", "Aerospace", "Government", "Agriculture"],
    industrialFacts: [
      "Tinker Air Force Base is one of the largest military installations",
      "Major oil and natural gas hub",
      "Growing aerospace repair and overhaul presence",
    ],
    wireFormingRelevance: "Military installations need durable wire products. Aerospace maintenance needs precision components. Oil operations need industrial-grade wire forms.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "little-rock",
    name: "Little Rock",
    state: "Arkansas",
    stateCode: "AR",
    region: "southeast",
    population: "205,000",
    keyIndustries: ["Healthcare", "Logistics", "Food processing", "Steel"],
    industrialFacts: [
      "Major regional healthcare hub",
      "Central US logistics location",
      "Historic steel manufacturing presence—Nucor",
    ],
    wireFormingRelevance: "Healthcare facilities need medical-grade products. Distribution centers need material handling equipment. Steel companies understand metalworking and appreciate quality wire forms.",
    shippingNote: "2-day ground shipping",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL CITIES TO REACH 100
  // ═══════════════════════════════════════════════════════════════════════════
  {
    slug: "buffalo",
    name: "Buffalo",
    state: "New York",
    stateCode: "NY",
    region: "northeast",
    population: "280,000",
    nickname: "The Queen City",
    keyIndustries: ["Healthcare", "Advanced manufacturing", "Logistics", "Clean energy"],
    industrialFacts: [
      "Buffalo is experiencing a manufacturing renaissance",
      "Tesla solar panel manufacturing facility",
      "Major cross-border trade hub with Canada",
    ],
    wireFormingRelevance: "Advanced manufacturing needs precision wire components. Clean energy operations need solar mounting hardware. Cross-border logistics requires material handling equipment.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "rochester",
    name: "Rochester",
    state: "New York",
    stateCode: "NY",
    region: "northeast",
    population: "210,000",
    nickname: "Flower City",
    keyIndustries: ["Optics", "Imaging", "Healthcare", "Higher education"],
    industrialFacts: [
      "Historic home of Kodak and Xerox—optics expertise remains",
      "Strong precision manufacturing heritage",
      "Growing biomedical imaging cluster",
    ],
    wireFormingRelevance: "Optics and imaging companies need precision wire components. Healthcare institutions need medical-grade stainless products. The precision manufacturing heritage means customers with exacting standards.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "syracuse",
    name: "Syracuse",
    state: "New York",
    stateCode: "NY",
    region: "northeast",
    population: "150,000",
    nickname: "Salt City",
    keyIndustries: ["Healthcare", "Education", "Technology", "Drones"],
    industrialFacts: [
      "Major drone testing corridor",
      "Strong healthcare and university research presence",
      "Growing technology sector",
    ],
    wireFormingRelevance: "Drone testing facilities need specialized wire components. Healthcare institutions need medical equipment. University research labs need custom wire products.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "albany",
    name: "Albany",
    state: "New York",
    stateCode: "NY",
    region: "northeast",
    population: "100,000",
    keyIndustries: ["Government", "Nanotechnology", "Healthcare", "Education"],
    industrialFacts: [
      "State capital with major government operations",
      "SUNY Poly nanotechnology research hub",
      "Growing semiconductor presence",
    ],
    wireFormingRelevance: "Semiconductor and nanotechnology facilities need cleanroom-compatible components. Government agencies need durable equipment. Healthcare systems need stainless products.",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "providence",
    name: "Providence",
    state: "Rhode Island",
    stateCode: "RI",
    region: "northeast",
    population: "190,000",
    nickname: "Creative Capital",
    keyIndustries: ["Jewelry", "Design", "Healthcare", "Education"],
    industrialFacts: [
      "Historic jewelry manufacturing capital of America",
      "Strong design and creative industries",
      "Major healthcare and education hub",
    ],
    wireFormingRelevance: "Jewelry manufacturing needs fine wire components. Design industries need custom display solutions. Healthcare facilities need medical-grade products.",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "new-haven",
    name: "New Haven",
    state: "Connecticut",
    stateCode: "CT",
    region: "northeast",
    population: "135,000",
    keyIndustries: ["Biotech", "Healthcare", "Education", "Precision manufacturing"],
    industrialFacts: [
      "Yale University biotech spinoffs",
      "Strong healthcare research cluster",
      "Historic manufacturing heritage",
    ],
    wireFormingRelevance: "Biotech companies need precision stainless wire products. Healthcare research needs specialized lab equipment. The manufacturing heritage means skilled customers.",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "scranton",
    name: "Scranton",
    state: "Pennsylvania",
    stateCode: "PA",
    region: "northeast",
    population: "77,000",
    nickname: "The Electric City",
    keyIndustries: ["Distribution", "Healthcare", "Manufacturing", "Back office"],
    industrialFacts: [
      "Major Northeast distribution hub",
      "Growing back-office operations center",
      "Historic manufacturing and coal heritage",
    ],
    wireFormingRelevance: "Distribution centers need wire baskets, shelving, and material handling. Healthcare facilities need medical equipment. Manufacturing operations need industrial wire products.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "allentown",
    name: "Allentown",
    state: "Pennsylvania",
    stateCode: "PA",
    region: "northeast",
    population: "125,000",
    keyIndustries: ["Manufacturing", "Logistics", "Healthcare", "Technology"],
    industrialFacts: [
      "Part of the Lehigh Valley manufacturing corridor",
      "Major distribution hub for the Northeast",
      "Growing technology sector",
    ],
    wireFormingRelevance: "Manufacturing operations need industrial wire forms. Distribution centers need material handling equipment. The Lehigh Valley's industrial expertise means quality-focused customers.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "wilmington-de",
    name: "Wilmington",
    state: "Delaware",
    stateCode: "DE",
    region: "northeast",
    population: "70,000",
    keyIndustries: ["Finance", "Chemicals", "Pharmaceuticals", "Corporate HQ"],
    industrialFacts: [
      "Corporate headquarters capital of America",
      "DuPont and chemical industry heritage",
      "Major credit card operations hub",
    ],
    wireFormingRelevance: "Chemical and pharmaceutical companies need corrosion-resistant wire products. Corporate facilities need office equipment. The chemical heritage means customers who understand materials.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "knoxville",
    name: "Knoxville",
    state: "Tennessee",
    stateCode: "TN",
    region: "southeast",
    population: "190,000",
    keyIndustries: ["Energy research", "Manufacturing", "Healthcare", "Education"],
    industrialFacts: [
      "Oak Ridge National Laboratory nearby",
      "Major advanced manufacturing hub",
      "Growing automotive supplier presence",
    ],
    wireFormingRelevance: "National laboratory research needs precision components. Advanced manufacturing needs industrial wire products. Automotive suppliers need production wire forms.",
    shippingNote: "1-2 day ground shipping",
  },
  {
    slug: "chattanooga",
    name: "Chattanooga",
    state: "Tennessee",
    stateCode: "TN",
    region: "southeast",
    population: "185,000",
    nickname: "Scenic City",
    keyIndustries: ["Automotive", "Technology", "Logistics", "Manufacturing"],
    industrialFacts: [
      "Volkswagen's only US manufacturing plant",
      "World's fastest municipal internet—tech hub",
      "Major logistics corridor intersection",
    ],
    wireFormingRelevance: "Volkswagen and automotive suppliers need production wire forms. Tech companies need precision components. Logistics operations need material handling equipment.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "lexington",
    name: "Lexington",
    state: "Kentucky",
    stateCode: "KY",
    region: "southeast",
    population: "320,000",
    nickname: "Horse Capital of the World",
    keyIndustries: ["Automotive", "Healthcare", "Technology", "Bourbon"],
    industrialFacts: [
      "Toyota's largest manufacturing complex in North America",
      "Major healthcare and pharmaceutical presence",
      "Growing technology sector",
    ],
    wireFormingRelevance: "Toyota and automotive suppliers need high-volume wire forms. Healthcare and pharmaceutical companies need stainless products. The bourbon industry needs specialized processing equipment.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "savannah",
    name: "Savannah",
    state: "Georgia",
    stateCode: "GA",
    region: "southeast",
    population: "150,000",
    keyIndustries: ["Ports", "Aerospace", "Manufacturing", "Tourism"],
    industrialFacts: [
      "Port of Savannah is the fastest-growing in the US",
      "Gulfstream Aerospace headquarters",
      "Growing manufacturing hub",
    ],
    wireFormingRelevance: "The massive port needs wire containers and material handling. Gulfstream needs aerospace-grade wire forms. Manufacturing operations need industrial products.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "mobile",
    name: "Mobile",
    state: "Alabama",
    stateCode: "AL",
    region: "southeast",
    population: "190,000",
    keyIndustries: ["Aerospace", "Shipbuilding", "Steel", "Ports"],
    industrialFacts: [
      "Airbus final assembly plant",
      "Major shipbuilding—Austal USA",
      "Deep water port operations",
    ],
    wireFormingRelevance: "Airbus needs aerospace-grade wire components. Shipbuilding needs marine-grade wire products. Port operations need material handling equipment.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "baton-rouge",
    name: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    region: "southeast",
    population: "225,000",
    keyIndustries: ["Petrochemicals", "Government", "Healthcare", "Education"],
    industrialFacts: [
      "Major petrochemical corridor",
      "State capital operations",
      "Strong university research presence",
    ],
    wireFormingRelevance: "Petrochemical plants need corrosion-resistant wire products for harsh environments. Government facilities need durable equipment. Healthcare systems need medical-grade stainless.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "shreveport",
    name: "Shreveport",
    state: "Louisiana",
    stateCode: "LA",
    region: "southeast",
    population: "190,000",
    keyIndustries: ["Oil & gas", "Healthcare", "Gaming", "Film"],
    industrialFacts: [
      "Major oil and gas hub for the region",
      "Regional healthcare center",
      "Growing film production industry",
    ],
    wireFormingRelevance: "Oil and gas operations need durable industrial wire products. Healthcare facilities need medical equipment. Film production needs custom display and rigging solutions.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "jackson-ms",
    name: "Jackson",
    state: "Mississippi",
    stateCode: "MS",
    region: "southeast",
    population: "155,000",
    keyIndustries: ["Healthcare", "Government", "Distribution", "Manufacturing"],
    industrialFacts: [
      "State capital and regional healthcare hub",
      "Central distribution location for the South",
      "Growing manufacturing presence",
    ],
    wireFormingRelevance: "Healthcare facilities need medical-grade products. Distribution centers need material handling equipment. Manufacturing operations need industrial wire forms.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "augusta",
    name: "Augusta",
    state: "Georgia",
    stateCode: "GA",
    region: "southeast",
    population: "200,000",
    keyIndustries: ["Cybersecurity", "Military", "Healthcare", "Manufacturing"],
    industrialFacts: [
      "US Army Cyber Command headquarters at Fort Eisenhower",
      "Major cybersecurity workforce hub",
      "Growing healthcare and education sector",
    ],
    wireFormingRelevance: "Military installations need durable wire products. Cybersecurity data centers need cable management. Healthcare facilities need medical-grade equipment.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "columbia-sc",
    name: "Columbia",
    state: "South Carolina",
    stateCode: "SC",
    region: "southeast",
    population: "135,000",
    keyIndustries: ["Government", "Military", "Healthcare", "Education"],
    industrialFacts: [
      "State capital with major military presence",
      "Fort Jackson—largest basic training installation",
      "Growing university research hub",
    ],
    wireFormingRelevance: "Military bases need durable equipment and storage solutions. Government facilities need industrial products. Healthcare systems need medical-grade wire forms.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "madison",
    name: "Madison",
    state: "Wisconsin",
    stateCode: "WI",
    region: "midwest",
    population: "270,000",
    keyIndustries: ["Biotechnology", "Government", "Healthcare", "Technology"],
    industrialFacts: [
      "State capital and major biotech hub",
      "University of Wisconsin research cluster",
      "Growing technology and startup scene",
    ],
    wireFormingRelevance: "Biotech companies need precision stainless wire products. Healthcare facilities need medical equipment. Technology companies need custom wire components.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "green-bay",
    name: "Green Bay",
    state: "Wisconsin",
    stateCode: "WI",
    region: "midwest",
    population: "105,000",
    nickname: "Titletown",
    keyIndustries: ["Paper & packaging", "Food processing", "Manufacturing", "Healthcare"],
    industrialFacts: [
      "Major paper and packaging manufacturing hub",
      "Significant food processing presence",
      "Strong manufacturing workforce",
    ],
    wireFormingRelevance: "Paper and packaging operations need industrial wire equipment. Food processing needs sanitary stainless products. Manufacturing operations need industrial wire forms.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "rockford",
    name: "Rockford",
    state: "Illinois",
    stateCode: "IL",
    region: "midwest",
    population: "150,000",
    nickname: "Forest City",
    keyIndustries: ["Aerospace", "Automotive", "Fasteners", "Machine tools"],
    industrialFacts: [
      "Aerospace manufacturing hub—Collins Aerospace",
      "Historic fastener and machine tool capital",
      "Strong precision manufacturing heritage",
    ],
    wireFormingRelevance: "Aerospace companies need precision wire components. The fastener industry understands wire metalworking. Machine tool expertise means customers with high standards.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "peoria",
    name: "Peoria",
    state: "Illinois",
    stateCode: "IL",
    region: "midwest",
    population: "115,000",
    keyIndustries: ["Heavy equipment", "Healthcare", "Logistics", "Agriculture"],
    industrialFacts: [
      "Caterpillar Inc. world headquarters",
      "Major healthcare hub for central Illinois",
      "Agricultural equipment manufacturing",
    ],
    wireFormingRelevance: "Caterpillar and heavy equipment makers need rugged wire guards and components. Healthcare facilities need medical equipment. Agricultural operations need durable wire products.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "south-bend",
    name: "South Bend",
    state: "Indiana",
    stateCode: "IN",
    region: "midwest",
    population: "105,000",
    keyIndustries: ["Automotive", "Technology", "Healthcare", "Education"],
    industrialFacts: [
      "Historic manufacturing hub—Studebaker heritage",
      "Notre Dame research and technology spinoffs",
      "Growing technology sector",
    ],
    wireFormingRelevance: "Automotive suppliers need production wire forms. Technology companies need precision components. The manufacturing heritage means skilled customers.",
    nearbyManufacturing: "200 miles from our facility",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "evansville",
    name: "Evansville",
    state: "Indiana",
    stateCode: "IN",
    region: "midwest",
    population: "120,000",
    keyIndustries: ["Automotive", "Plastics", "Healthcare", "Logistics"],
    industrialFacts: [
      "Toyota manufacturing presence",
      "Major plastics and packaging hub",
      "Regional logistics center",
    ],
    wireFormingRelevance: "Toyota and automotive suppliers need production wire forms. Plastics companies need processing equipment. Logistics operations need material handling products.",
    shippingNote: "1-day ground shipping",
  },
  {
    slug: "springfield-mo",
    name: "Springfield",
    state: "Missouri",
    stateCode: "MO",
    region: "midwest",
    population: "170,000",
    nickname: "Queen City of the Ozarks",
    keyIndustries: ["Healthcare", "Manufacturing", "Education", "Distribution"],
    industrialFacts: [
      "Major regional healthcare hub—CoxHealth, Mercy",
      "Bass Pro Shops headquarters",
      "Growing distribution presence",
    ],
    wireFormingRelevance: "Healthcare facilities need medical equipment. Manufacturing operations need industrial wire products. Distribution centers need material handling solutions.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "sioux-falls",
    name: "Sioux Falls",
    state: "South Dakota",
    stateCode: "SD",
    region: "midwest",
    population: "195,000",
    keyIndustries: ["Healthcare", "Finance", "Agriculture", "Data centers"],
    industrialFacts: [
      "Major regional healthcare hub—Sanford Health, Avera",
      "Growing financial services and data centers",
      "Agricultural processing center",
    ],
    wireFormingRelevance: "Healthcare systems need medical-grade stainless products. Data centers need cable management. Agricultural processing needs industrial wire equipment.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "fargo",
    name: "Fargo",
    state: "North Dakota",
    stateCode: "ND",
    region: "midwest",
    population: "125,000",
    keyIndustries: ["Technology", "Healthcare", "Agriculture", "Manufacturing"],
    industrialFacts: [
      "Growing technology and startup hub",
      "Major regional healthcare center",
      "Agricultural equipment manufacturing",
    ],
    wireFormingRelevance: "Technology companies need custom wire components. Healthcare facilities need medical equipment. Agricultural equipment makers need durable wire products.",
    shippingNote: "2-day ground shipping",
  },
  {
    slug: "billings",
    name: "Billings",
    state: "Montana",
    stateCode: "MT",
    region: "west",
    population: "120,000",
    nickname: "Magic City",
    keyIndustries: ["Oil refining", "Healthcare", "Agriculture", "Transportation"],
    industrialFacts: [
      "Major oil refining hub for the region",
      "Regional healthcare center",
      "Transportation and logistics gateway to Montana",
    ],
    wireFormingRelevance: "Oil refineries need industrial wire guards and equipment. Healthcare facilities need medical-grade products. Agricultural operations need durable wire forms.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "anchorage",
    name: "Anchorage",
    state: "Alaska",
    stateCode: "AK",
    region: "west",
    population: "290,000",
    keyIndustries: ["Oil & gas", "Military", "Transportation", "Tourism"],
    industrialFacts: [
      "Major oil and gas operations hub",
      "Strategic military presence",
      "Cargo hub for Asia-North America routes",
    ],
    wireFormingRelevance: "Oil and gas operations need wire products for extreme conditions. Military bases need durable equipment. The harsh environment demands rugged construction.",
    shippingNote: "Air freight or 5+ day ground shipping",
  },
  {
    slug: "honolulu",
    name: "Honolulu",
    state: "Hawaii",
    stateCode: "HI",
    region: "west",
    population: "350,000",
    keyIndustries: ["Military", "Tourism", "Healthcare", "Shipping"],
    industrialFacts: [
      "Major Pacific military hub—Pearl Harbor",
      "Tourism infrastructure requirements",
      "Pacific shipping gateway",
    ],
    wireFormingRelevance: "Military installations need marine-grade wire products. Tourism infrastructure needs hospitality equipment. Shipping operations need material handling.",
    shippingNote: "Ocean or air freight—5+ days",
  },
  {
    slug: "reno",
    name: "Reno",
    state: "Nevada",
    stateCode: "NV",
    region: "west",
    population: "265,000",
    nickname: "The Biggest Little City",
    keyIndustries: ["Technology", "Logistics", "Data centers", "Gaming"],
    industrialFacts: [
      "Tesla Gigafactory and major tech hub",
      "Major West Coast distribution center",
      "Growing data center market",
    ],
    wireFormingRelevance: "Tesla and tech companies need precision wire components. Distribution centers need material handling. Data centers need cable trays and management.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "colorado-springs",
    name: "Colorado Springs",
    state: "Colorado",
    stateCode: "CO",
    region: "southwest",
    population: "485,000",
    nickname: "Olympic City USA",
    keyIndustries: ["Military", "Aerospace", "Technology", "Tourism"],
    industrialFacts: [
      "Multiple military installations—Peterson, Schriever, NORAD",
      "Space and defense contractor hub",
      "Growing technology sector",
    ],
    wireFormingRelevance: "Military and defense contractors need specialized wire products. Aerospace companies need precision components. Space systems require high-quality wire forms.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "fort-worth",
    name: "Fort Worth",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "940,000",
    nickname: "Cowtown",
    keyIndustries: ["Aerospace", "Defense", "Logistics", "Healthcare"],
    industrialFacts: [
      "Lockheed Martin F-35 production",
      "Bell Helicopter manufacturing",
      "Major logistics and distribution hub",
    ],
    wireFormingRelevance: "Lockheed Martin and aerospace companies need precision wire forms. Bell Helicopter needs aviation components. The defense concentration means demanding customers.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "mesa",
    name: "Mesa",
    state: "Arizona",
    stateCode: "AZ",
    region: "southwest",
    population: "505,000",
    keyIndustries: ["Aerospace", "Manufacturing", "Healthcare", "Technology"],
    industrialFacts: [
      "Boeing Apache helicopter production",
      "Growing aerospace manufacturing cluster",
      "Major healthcare and education presence",
    ],
    wireFormingRelevance: "Boeing needs aerospace-grade wire components. Manufacturing operations need industrial products. Healthcare facilities need medical-grade equipment.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "henderson",
    name: "Henderson",
    state: "Nevada",
    stateCode: "NV",
    region: "west",
    population: "320,000",
    keyIndustries: ["Healthcare", "Technology", "Distribution", "Manufacturing"],
    industrialFacts: [
      "Growing healthcare and medical device sector",
      "Technology company presence",
      "Strategic distribution location",
    ],
    wireFormingRelevance: "Healthcare and medical device companies need precision stainless products. Technology operations need custom components. Distribution centers need material handling.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "stockton",
    name: "Stockton",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "320,000",
    keyIndustries: ["Agriculture", "Logistics", "Healthcare", "Manufacturing"],
    industrialFacts: [
      "Major Central Valley agricultural hub",
      "Inland port and logistics center",
      "Growing healthcare presence",
    ],
    wireFormingRelevance: "Agricultural operations need processing equipment. Port and logistics need material handling. Healthcare facilities need medical-grade products.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "irvine",
    name: "Irvine",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "310,000",
    keyIndustries: ["Technology", "Medical devices", "Finance", "Education"],
    industrialFacts: [
      "Major technology and medical device hub",
      "Corporate headquarters concentration",
      "Strong university research presence",
    ],
    wireFormingRelevance: "Medical device companies need precision stainless wire forms. Technology companies need custom components. Corporate facilities need quality equipment.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "chula-vista",
    name: "Chula Vista",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "275,000",
    keyIndustries: ["Defense", "Healthcare", "Technology", "Cross-border trade"],
    industrialFacts: [
      "Close to major military installations",
      "Growing technology presence",
      "US-Mexico border trade gateway",
    ],
    wireFormingRelevance: "Defense contractors need specialized wire products. Healthcare facilities need medical equipment. Cross-border manufacturing needs wire components.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "tacoma",
    name: "Tacoma",
    state: "Washington",
    stateCode: "WA",
    region: "west",
    population: "220,000",
    keyIndustries: ["Shipping", "Military", "Healthcare", "Manufacturing"],
    industrialFacts: [
      "Major Pacific Northwest port",
      "Joint Base Lewis-McChord nearby",
      "Historic manufacturing heritage",
    ],
    wireFormingRelevance: "Port operations need material handling equipment. Military bases need durable products. Manufacturing operations need industrial wire forms.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "modesto",
    name: "Modesto",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "215,000",
    keyIndustries: ["Food processing", "Agriculture", "Healthcare", "Distribution"],
    industrialFacts: [
      "Major food processing hub—E&J Gallo",
      "Central Valley agricultural center",
      "Regional healthcare and distribution",
    ],
    wireFormingRelevance: "Food processing needs sanitary stainless wire baskets and equipment. Agricultural operations need handling products. Distribution needs material handling.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "santa-rosa",
    name: "Santa Rosa",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "180,000",
    keyIndustries: ["Wine production", "Healthcare", "Technology", "Tourism"],
    industrialFacts: [
      "Heart of Sonoma County wine country",
      "Growing healthcare and tech presence",
      "Clean energy initiatives",
    ],
    wireFormingRelevance: "Wineries need stainless wire processing equipment. Healthcare facilities need medical products. Clean energy needs mounting hardware.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "huntington-beach",
    name: "Huntington Beach",
    state: "California",
    stateCode: "CA",
    region: "west",
    population: "200,000",
    nickname: "Surf City USA",
    keyIndustries: ["Oil & gas", "Aerospace", "Healthcare", "Tourism"],
    industrialFacts: [
      "Historic oil production area",
      "Aerospace and defense contractor presence",
      "Major tourism and hospitality",
    ],
    wireFormingRelevance: "Oil operations need industrial wire products. Aerospace needs precision components. Tourism infrastructure needs hospitality equipment.",
    shippingNote: "3-4 day ground shipping",
  },
  {
    slug: "glendale-az",
    name: "Glendale",
    state: "Arizona",
    stateCode: "AZ",
    region: "southwest",
    population: "250,000",
    keyIndustries: ["Healthcare", "Manufacturing", "Sports", "Retail"],
    industrialFacts: [
      "Major healthcare and medical hub",
      "Growing manufacturing presence",
      "Sports and entertainment complex",
    ],
    wireFormingRelevance: "Healthcare facilities need medical-grade products. Manufacturing needs industrial wire forms. Sports facilities need custom equipment.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "chandler",
    name: "Chandler",
    state: "Arizona",
    stateCode: "AZ",
    region: "southwest",
    population: "275,000",
    keyIndustries: ["Semiconductors", "Technology", "Data centers", "Healthcare"],
    industrialFacts: [
      "Intel semiconductor fabrication hub",
      "Major technology company presence",
      "Growing data center market",
    ],
    wireFormingRelevance: "Semiconductor fabs need cleanroom-compatible wire products. Tech companies need precision components. Data centers need cable management.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "scottsdale",
    name: "Scottsdale",
    state: "Arizona",
    stateCode: "AZ",
    region: "southwest",
    population: "260,000",
    keyIndustries: ["Healthcare", "Technology", "Finance", "Tourism"],
    industrialFacts: [
      "Major healthcare and wellness destination",
      "Growing technology hub",
      "Luxury resort and tourism center",
    ],
    wireFormingRelevance: "Healthcare facilities need medical equipment. Technology companies need precision components. Hospitality needs custom fixtures and displays.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "gilbert",
    name: "Gilbert",
    state: "Arizona",
    stateCode: "AZ",
    region: "southwest",
    population: "265,000",
    keyIndustries: ["Technology", "Healthcare", "Education", "Retail"],
    industrialFacts: [
      "Rapidly growing technology presence",
      "Major healthcare expansion",
      "Strong education sector",
    ],
    wireFormingRelevance: "Technology companies need custom wire components. Healthcare facilities need medical-grade products. Educational institutions need equipment.",
    shippingNote: "3-day ground shipping",
  },
  {
    slug: "laredo",
    name: "Laredo",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "260,000",
    keyIndustries: ["Trade", "Logistics", "Manufacturing", "Healthcare"],
    industrialFacts: [
      "Largest inland port on US-Mexico border",
      "Major cross-border manufacturing gateway",
      "Customs and logistics hub",
    ],
    wireFormingRelevance: "Cross-border manufacturing needs wire components. Logistics operations need material handling. The massive trade volume means constant equipment needs.",
    shippingNote: "2-3 day ground shipping",
  },
  {
    slug: "corpus-christi",
    name: "Corpus Christi",
    state: "Texas",
    stateCode: "TX",
    region: "southwest",
    population: "325,000",
    nickname: "Sparkling City by the Sea",
    keyIndustries: ["Oil refining", "Petrochemicals", "Shipping", "Military"],
    industrialFacts: [
      "Major Gulf Coast refining hub",
      "Deep water port operations",
      "Naval Air Station Corpus Christi",
    ],
    wireFormingRelevance: "Refineries need corrosion-resistant wire products. Port operations need material handling. Military needs durable equipment.",
    shippingNote: "2-3 day ground shipping",
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((city) => city.slug === slug);
}

export function getCitiesByRegion(region: CityData["region"]): CityData[] {
  return cities.filter((city) => city.region === region);
}

export function getCitiesByState(stateCode: string): CityData[] {
  return cities.filter((city) => city.stateCode === stateCode);
}
